"use client";

// ── Sub-Objective Room View (v2) ──
//
// Renders the 4 lanes (Pain → Features → Outcomes → Objective)
// using the new causal-chain card components. Adds:
//
//   • Shared-cause pill strip above the Pain lane (with count badges)
//   • Influence-rank sort + Root ⭐ badge on the top pain
//   • Keystone badge on the feature countering the most pains
//   • Inline expand-on-click cards with root causes / first principles
//   • Cross-lane cause↔pain highlight when hovering a shared pill
//
// Correlation side panel still lives on the right; edges feed
// the "addressed by" / "counters pains" lists inside expanded cards.

import { useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState, useTransition } from "react";
import { RefreshCw } from "lucide-react";
import { Sparkle } from "@/components/objective/icons/sparkle";
import { appleVibe } from "@/lib/apple-vibe-tokens";
import { CorrelationSidePanel } from "./correlation-side-panel";
import { PainCard, type PainCardItem } from "./cards/pain-card";
import { FeatureCard, type FeatureCardItem } from "./cards/feature-card";
import { OutcomeCard, type OutcomeCardItem } from "./cards/outcome-card";
import { SharedCausesStrip } from "./cards/shared-causes-strip";
import { PortfolioStrip } from "./cards/portfolio-strip";
import { computeChains } from "@/lib/objective-canvas/compute-chains";
import {
  normalizeRoomCategories,
  type RoomCategories,
} from "@/lib/objective-canvas/generate-categories";
import type { PipelineMode } from "./mode-pill";

export interface LayerItem {
  id: string;
  name: string;
  description: string | null;
  entity_type: string;
  /** v2 — pain: { negative_outcome, root_causes[], influence_rank }
   *        feature: { positive_outcome, first_principles[] }
   *        outcome: { measured_by }
   *  Tier 3 — every layer item also carries `sub_category` here
   *  (a slug into room_categories[lane]) when categorization is
   *  enabled for this room.
   *  Falls through to description-only rendering for legacy
   *  entities that pre-date the migration. */
  causal_chain?: Record<string, unknown> | null;
}

export interface RoomEdge {
  id: string;
  source_entity_id: string;
  target_entity_id: string;
  relationship_type: string;
  strength: number | null;
  polarity: string | null;
  conditions: string | null;
  approved_at?: string | null;
  /** LLM-named mechanism (specific lever) lives under
   *  agent_feedback.mechanism. Optional — surfaces in the side
   *  panel as a small pill above the rationale. */
  agent_feedback?: Record<string, unknown> | null;
}

export interface RoomLane {
  slug: "pain" | "features" | "outcomes" | "objective";
  label: string;
  color: string;
  items: LayerItem[];
}

interface Props {
  spaceId: string;
  subObjectiveId: string;
  lanes: RoomLane[];
  edges: RoomEdge[];
  generatedAt: string | null;
  pipelineMode: PipelineMode;
  /** Tier 3 — adaptive sub-categories generated by the pre-room
   *  step. Drives lane card chips, chain archetype labels, and
   *  the portfolio strip. Empty `{}` is tolerated — categories
   *  just won't render. */
  roomCategoriesRaw?: unknown;
}

export function SubObjectiveRoomView({
  spaceId,
  subObjectiveId,
  lanes,
  edges,
  generatedAt,
  pipelineMode,
  roomCategoriesRaw,
}: Props) {
  const roomCategories: RoomCategories = useMemo(
    () => normalizeRoomCategories(roomCategoriesRaw),
    [roomCategoriesRaw],
  );

  /** Resolve sub_category slug → { label, color } for chip rendering. */
  function categoryFor(
    lane: keyof RoomCategories,
    slug: string | null | undefined,
  ): { label: string; color: string } | null {
    if (!slug) return null;
    const hit = roomCategories[lane].find((c) => c.slug === slug);
    return hit ? { label: hit.label, color: hit.color } : null;
  }
  const router = useRouter();
  const [error, setError] = useState<string | null>(null);
  const [busy, startTransition] = useTransition();
  const [highlightedCauses, setHighlightedCauses] = useState<Set<string>>(
    new Set(),
  );
  // Hover-to-link: which card is currently hovered (or null). Linked
  // ids are derived from this + the edges map.
  const [hoveredEntityId, setHoveredEntityId] = useState<string | null>(null);
  const [approvedEdgeIds, setApprovedEdgeIds] = useState<Set<string>>(() => {
    return new Set(
      edges.filter((e) => e.approved_at != null).map((e) => e.id),
    );
  });

  const isEmpty = lanes.every(
    (l) =>
      l.items.length === 0 ||
      (l.items.length === 1 && l.slug === "objective"),
  );

  // ── Index every entity by id so panel hover can map id → layer
  // Tier 3 — also includes the sub_category slug so compute-chains
  // can populate the per-chain category triple → archetype labels.
  const entityIndex = useMemo(() => {
    const map = new Map<
      string,
      {
        id: string;
        name: string;
        layer: "pain" | "features" | "outcomes" | "objective";
        subCategorySlug?: string | null;
      }
    >();
    for (const lane of lanes) {
      for (const item of lane.items) {
        const cc = (item.causal_chain ?? {}) as Record<string, unknown>;
        const slug =
          typeof cc.sub_category === "string" && cc.sub_category.length > 0
            ? cc.sub_category
            : null;
        map.set(item.id, {
          id: item.id,
          name: item.name,
          layer: lane.slug,
          subCategorySlug: slug,
        });
      }
    }
    return map;
  }, [lanes]);

  // ── Derive typed lane items from causal_chain payloads ──
  // Each item's sub_category slug is captured here so the card
  // chip + portfolio strip + chain archetype derivation share one
  // source of truth.
  function readSlug(cc: Record<string, unknown>): string | null {
    return typeof cc.sub_category === "string" && cc.sub_category.length > 0
      ? cc.sub_category
      : null;
  }

  const painItems = useMemo(
    () =>
      lanes
        .find((l) => l.slug === "pain")!
        .items.map((it) => {
          const cc = (it.causal_chain ?? {}) as Record<string, unknown>;
          return {
            id: it.id,
            name: it.name,
            negative_outcome:
              typeof cc.negative_outcome === "string"
                ? cc.negative_outcome
                : it.description ?? undefined,
            root_causes: Array.isArray(cc.root_causes)
              ? (cc.root_causes as unknown[])
                  .filter((s): s is string => typeof s === "string")
                  .slice(0, 4)
              : [],
            influence_rank:
              typeof cc.influence_rank === "number"
                ? cc.influence_rank
                : 2.5,
            sub_category_slug: readSlug(cc),
          };
        })
        .sort((a, b) => b.influence_rank - a.influence_rank),
    [lanes],
  );

  const featureItems = useMemo(
    () =>
      lanes
        .find((l) => l.slug === "features")!
        .items.map((it) => {
          const cc = (it.causal_chain ?? {}) as Record<string, unknown>;
          return {
            id: it.id,
            name: it.name,
            positive_outcome:
              typeof cc.positive_outcome === "string"
                ? cc.positive_outcome
                : it.description ?? undefined,
            first_principles: Array.isArray(cc.first_principles)
              ? (cc.first_principles as unknown[])
                  .filter((s): s is string => typeof s === "string")
                  .slice(0, 4)
              : [],
            sub_category_slug: readSlug(cc),
          };
        }),
    [lanes],
  );

  const outcomeItems = useMemo(
    () =>
      lanes
        .find((l) => l.slug === "outcomes")!
        .items.map((it) => {
          const cc = (it.causal_chain ?? {}) as Record<string, unknown>;
          return {
            id: it.id,
            name: it.name,
            measured_by:
              typeof cc.measured_by === "string"
                ? cc.measured_by
                : it.description ?? undefined,
            sub_category_slug: readSlug(cc),
          };
        }),
    [lanes],
  );

  const objectiveItems = useMemo(
    () => lanes.find((l) => l.slug === "objective")?.items ?? [],
    [lanes],
  );

  // ── Shared root-cause counts across pains ──
  const painSharedCounts = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const p of painItems) {
      for (const c of p.root_causes) {
        counts[c] = (counts[c] ?? 0) + 1;
      }
    }
    return counts;
  }, [painItems]);

  const sharedPainsList = useMemo(
    () =>
      Object.entries(painSharedCounts)
        .filter(([, count]) => count >= 2)
        .map(([cause, count]) => ({ cause, count }))
        .sort((a, b) => b.count - a.count),
    [painSharedCounts],
  );

  // ── Same for feature first-principles ──
  const featureSharedCounts = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const f of featureItems) {
      for (const p of f.first_principles) {
        counts[p] = (counts[p] ?? 0) + 1;
      }
    }
    return counts;
  }, [featureItems]);
  const [highlightedPrinciples, setHighlightedPrinciples] = useState<
    Set<string>
  >(new Set());

  // ── Edge-derived addressed-by / counters maps ──
  // Pain → list of features that address it (sorted by strength).
  const addressedByMap = useMemo(() => {
    const map = new Map<
      string,
      Array<{ id: string; name: string; pct: number }>
    >();
    for (const e of edges) {
      const src = entityIndex.get(e.source_entity_id);
      const tgt = entityIndex.get(e.target_entity_id);
      if (!src || !tgt) continue;
      // pain → feature OR feature → pain both count
      const pain =
        src.layer === "pain" ? src : tgt.layer === "pain" ? tgt : null;
      const feat =
        src.layer === "features"
          ? src
          : tgt.layer === "features"
            ? tgt
            : null;
      if (!pain || !feat) continue;
      const list = map.get(pain.id) ?? [];
      list.push({
        id: feat.id,
        name: feat.name,
        pct: Math.round((e.strength ?? 0) * 100),
      });
      map.set(pain.id, list);
    }
    for (const v of map.values()) v.sort((a, b) => b.pct - a.pct);
    return map;
  }, [edges, entityIndex]);

  // Feature → list of pains it counters.
  const countersPainsMap = useMemo(() => {
    const map = new Map<
      string,
      Array<{ id: string; name: string; pct: number }>
    >();
    for (const e of edges) {
      const src = entityIndex.get(e.source_entity_id);
      const tgt = entityIndex.get(e.target_entity_id);
      if (!src || !tgt) continue;
      const pain =
        src.layer === "pain" ? src : tgt.layer === "pain" ? tgt : null;
      const feat =
        src.layer === "features"
          ? src
          : tgt.layer === "features"
            ? tgt
            : null;
      if (!pain || !feat) continue;
      const list = map.get(feat.id) ?? [];
      list.push({
        id: pain.id,
        name: pain.name,
        pct: Math.round((e.strength ?? 0) * 100),
      });
      map.set(feat.id, list);
    }
    for (const v of map.values()) v.sort((a, b) => b.pct - a.pct);
    return map;
  }, [edges, entityIndex]);

  // Outcome → list of features that produce it (feature → outcome edges).
  const producedByMap = useMemo(() => {
    const map = new Map<
      string,
      Array<{ id: string; name: string; pct: number }>
    >();
    for (const e of edges) {
      const src = entityIndex.get(e.source_entity_id);
      const tgt = entityIndex.get(e.target_entity_id);
      if (!src || !tgt) continue;
      const out =
        src.layer === "outcomes" ? src : tgt.layer === "outcomes" ? tgt : null;
      const feat =
        src.layer === "features"
          ? src
          : tgt.layer === "features"
            ? tgt
            : null;
      if (!out || !feat) continue;
      const list = map.get(out.id) ?? [];
      list.push({
        id: feat.id,
        name: feat.name,
        pct: Math.round((e.strength ?? 0) * 100),
      });
      map.set(out.id, list);
    }
    for (const v of map.values()) v.sort((a, b) => b.pct - a.pct);
    return map;
  }, [edges, entityIndex]);

  // Outcome → list of pains it dissolves (pain → outcome edges).
  const outcomeDissolvesMap = useMemo(() => {
    const map = new Map<
      string,
      Array<{ id: string; name: string; pct: number }>
    >();
    for (const e of edges) {
      const src = entityIndex.get(e.source_entity_id);
      const tgt = entityIndex.get(e.target_entity_id);
      if (!src || !tgt) continue;
      const out =
        src.layer === "outcomes" ? src : tgt.layer === "outcomes" ? tgt : null;
      const pain =
        src.layer === "pain" ? src : tgt.layer === "pain" ? tgt : null;
      if (!out || !pain) continue;
      const list = map.get(out.id) ?? [];
      list.push({
        id: pain.id,
        name: pain.name,
        pct: Math.round((e.strength ?? 0) * 100),
      });
      map.set(out.id, list);
    }
    for (const v of map.values()) v.sort((a, b) => b.pct - a.pct);
    return map;
  }, [edges, entityIndex]);

  // Outcomes that have an edge to the objective anchor → "rolls up".
  const rollsUpSet = useMemo(() => {
    const set = new Set<string>();
    for (const e of edges) {
      const src = entityIndex.get(e.source_entity_id);
      const tgt = entityIndex.get(e.target_entity_id);
      if (!src || !tgt) continue;
      if (src.layer === "outcomes" && tgt.layer === "objective")
        set.add(src.id);
      else if (tgt.layer === "outcomes" && src.layer === "objective")
        set.add(tgt.id);
    }
    return set;
  }, [edges, entityIndex]);

  // Identify the keystone feature (counters most pains).
  const keystoneFeatureId = useMemo(() => {
    let best: string | null = null;
    let bestCount = 0;
    for (const f of featureItems) {
      const cnt = (countersPainsMap.get(f.id) ?? []).length;
      if (cnt > bestCount) {
        bestCount = cnt;
        best = f.id;
      }
    }
    return bestCount >= 2 ? best : null;
  }, [featureItems, countersPainsMap]);

  // Top pain by influence (root).
  const rootPainId = painItems[0]?.id ?? null;

  // ── Linked entities derived from hover ──
  // When a card is hovered, walk the edges and collect every entity
  // id on the other end. Those cards get the glow ring + survive
  // dim. Empty set when nothing is hovered.
  const linkedIds = useMemo(() => {
    if (!hoveredEntityId) return new Set<string>();
    const out = new Set<string>([hoveredEntityId]);
    for (const e of edges) {
      if (e.source_entity_id === hoveredEntityId) out.add(e.target_entity_id);
      else if (e.target_entity_id === hoveredEntityId)
        out.add(e.source_entity_id);
    }
    return out;
  }, [hoveredEntityId, edges]);
  const hoverActive = hoveredEntityId !== null;

  // ── Influence-rank → indent bucket for the pain lane ──
  // Root-tier pains (rank ≥ 4) sit flush at the left. Mid-tier (2-3)
  // indent 8px. Terminal (<2) indent 16px. Conveys downstream-flow
  // without losing card width.
  function indentForRank(rank: number): number {
    if (rank >= 4) return 0;
    if (rank >= 2) return 8;
    return 16;
  }

  // ── Autopilot auto-fire ──
  const autoFiredRef = useRef(false);
  useEffect(() => {
    if (autoFiredRef.current) return;
    if (pipelineMode !== "autopilot") return;
    if (generatedAt) return;
    autoFiredRef.current = true;
    void generate("initial");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pipelineMode, generatedAt]);

  function generate(mode: "initial" | "regenerate") {
    setError(null);
    startTransition(async () => {
      try {
        const res = await fetch("/api/brainstorm/room/generate", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ spaceId, subObjectiveId, mode }),
        });
        const json = await res.json();
        if (!res.ok) {
          const base = json?.error ?? "Generation failed. Try again.";
          setError(json?.detail ? `${base} — ${json.detail}` : base);
          return;
        }
        router.refresh();
      } catch (err) {
        setError(
          err instanceof Error ? err.message : "Network error. Try again.",
        );
      }
    });
  }

  function handleApprovalChange(edgeId: string, approved: boolean) {
    setApprovedEdgeIds((prev) => {
      const next = new Set(prev);
      if (approved) next.add(edgeId);
      else next.delete(edgeId);
      return next;
    });
  }

  function handleSharedCauseHover(cause: string | null) {
    setHighlightedCauses(cause ? new Set([cause]) : new Set());
  }

  const hasEdges = edges.length > 0;
  const approvedCount = approvedEdgeIds.size;

  return (
    <div style={{ fontFamily: appleVibe.font.stack }}>
      {/* Header bar with Generate / Regenerate */}
      <div className="mb-6 flex items-center justify-between gap-3">
        <div>
          <div
            className="text-[10.5px] font-semibold uppercase tracking-[0.14em]"
            style={{ color: appleVibe.text.tertiary }}
          >
            4-stage room
          </div>
          {generatedAt ? (
            <p
              className="mt-1 text-[12.5px] font-light"
              style={{ color: appleVibe.text.secondary }}
            >
              Cards collapsed by default. Click any card to reveal its
              root causes / first principles and the connections it
              participates in.
            </p>
          ) : (
            <p
              className="mt-1 text-[12.5px] font-light"
              style={{ color: appleVibe.text.secondary }}
            >
              We&rsquo;ll spin out pain points first, then outcomes, then
              the features that bridge them. Cross-layer correlations
              live in the side panel.
            </p>
          )}
          {generatedAt && approvedCount > 0 && (
            <p
              className="mt-1 text-[11.5px] font-light"
              style={{ color: appleVibe.text.secondary }}
            >
              {approvedCount} correlation{approvedCount === 1 ? "" : "s"}{" "}
              approved.
            </p>
          )}
        </div>
        <div className="flex flex-shrink-0 items-center gap-2">
          {generatedAt && (
            <button
              type="button"
              onClick={() => generate("regenerate")}
              disabled={busy}
              className="inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[11.5px] font-semibold"
              style={{
                background: appleVibe.surface.chip,
                color: appleVibe.text.secondary,
                cursor: busy ? "wait" : "pointer",
              }}
            >
              <RefreshCw className="h-3 w-3" strokeWidth={2} />
              Regenerate
            </button>
          )}
          {!generatedAt && (
            <button
              type="button"
              onClick={() => generate("initial")}
              disabled={busy}
              className="inline-flex items-center gap-1.5 rounded-2xl px-4 py-2 text-[12.5px] font-semibold"
              style={{
                background: appleVibe.accent.primary,
                color: appleVibe.text.onAccent,
                borderRadius: appleVibe.radius.md,
                cursor: busy ? "wait" : "pointer",
                opacity: busy ? 0.7 : 1,
              }}
            >
              <Sparkle className="h-3.5 w-3.5" />
              <span>{busy ? "Generating…" : "Generate the room"}</span>
            </button>
          )}
        </div>
      </div>

      {error && (
        <div
          role="alert"
          className="mb-4 rounded-xl px-3.5 py-2.5 text-[12.5px]"
          style={{
            background: "rgba(220,38,38,0.06)",
            border: "1px solid rgba(220,38,38,0.18)",
            color: "rgba(127,29,29,0.95)",
          }}
        >
          {error}
        </div>
      )}

      {/* Portfolio strip — Tier 3 macro diagnostic. Compact line
          always visible; click to expand for coverage + gap warnings.
          Hidden entirely when this room has no categories. */}
      <PortfolioStrip
        categories={roomCategories}
        painItems={painItems.map((p) => ({
          id: p.id,
          subCategorySlug: p.sub_category_slug,
        }))}
        featureItems={featureItems.map((f) => ({
          id: f.id,
          subCategorySlug: f.sub_category_slug,
        }))}
        outcomeItems={outcomeItems.map((o) => ({
          id: o.id,
          subCategorySlug: o.sub_category_slug,
        }))}
        chains={computeChains(edges, entityIndex)}
        approvedEdgeIds={approvedEdgeIds}
      />

      {/* Three-column layout — Objective lane removed (it just
          duplicated the sub-objective title rendered in the page
          header). The "rolls up to" rollup banner on the page
          header carries the parent-objective link instead. */}
      <div className="flex flex-col gap-5 lg:flex-row lg:items-start">
        <div className="min-w-0 flex-1">
          <div
            className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"
            // Dim non-linked cards while hovering one — gives the
            // glow ring its companion contrast cue.
            style={{
              opacity: 1,
            }}
            data-hover-active={hoverActive ? "true" : undefined}
          >
            {/* PAIN lane */}
            <Lane
              slug="pain"
              label={lanes.find((l) => l.slug === "pain")!.label}
              color={lanes.find((l) => l.slug === "pain")!.color}
              count={painItems.length}
              loading={busy && isEmpty}
            >
              <SharedCausesStrip
                shared={sharedPainsList}
                highlighted={highlightedCauses}
                onHover={handleSharedCauseHover}
              />
              {painItems.length === 0 && !busy && <EmptyHint />}
              <ul className="flex flex-col gap-2">
                {painItems.map((p) => {
                  const isLinked = hoverActive && linkedIds.has(p.id);
                  const isDimmedByHover = hoverActive && !isLinked;
                  return (
                    <div
                      key={p.id}
                      style={{
                        opacity: isDimmedByHover ? 0.35 : 1,
                        transition: "opacity 180ms ease-out",
                      }}
                    >
                      <PainCard
                        item={p}
                        isRoot={p.id === rootPainId}
                        sharedCounts={painSharedCounts}
                        highlightedCauses={highlightedCauses}
                        onHoverCause={handleSharedCauseHover}
                        addressedBy={addressedByMap.get(p.id) ?? []}
                        linked={isLinked}
                        onHover={setHoveredEntityId}
                        indent={indentForRank(p.influence_rank)}
                        subCategory={categoryFor("friction", p.sub_category_slug)}
                      />
                    </div>
                  );
                })}
              </ul>
            </Lane>

            {/* FEATURE lane */}
            <Lane
              slug="features"
              label={lanes.find((l) => l.slug === "features")!.label}
              color={lanes.find((l) => l.slug === "features")!.color}
              count={featureItems.length}
              loading={busy && isEmpty}
            >
              {featureItems.length === 0 && !busy && <EmptyHint />}
              <ul className="flex flex-col gap-2">
                {featureItems.map((f) => {
                  const isLinked = hoverActive && linkedIds.has(f.id);
                  const isDimmedByHover = hoverActive && !isLinked;
                  return (
                    <div
                      key={f.id}
                      style={{
                        opacity: isDimmedByHover ? 0.35 : 1,
                        transition: "opacity 180ms ease-out",
                      }}
                    >
                      <FeatureCard
                        item={f}
                        isKeystone={f.id === keystoneFeatureId}
                        sharedCounts={featureSharedCounts}
                        highlightedPrinciples={highlightedPrinciples}
                        onHoverPrinciple={(p) =>
                          setHighlightedPrinciples(
                            p ? new Set([p]) : new Set(),
                          )
                        }
                        countersPains={countersPainsMap.get(f.id) ?? []}
                        linked={isLinked}
                        onHover={setHoveredEntityId}
                        subCategory={categoryFor(
                          "mechanism",
                          f.sub_category_slug,
                        )}
                      />
                    </div>
                  );
                })}
              </ul>
            </Lane>

            {/* OUTCOME lane */}
            <Lane
              slug="outcomes"
              label={lanes.find((l) => l.slug === "outcomes")!.label}
              color={lanes.find((l) => l.slug === "outcomes")!.color}
              count={outcomeItems.length}
              loading={busy && isEmpty}
            >
              {outcomeItems.length === 0 && !busy && <EmptyHint />}
              <ul className="flex flex-col gap-2">
                {outcomeItems.map((o) => {
                  const isLinked = hoverActive && linkedIds.has(o.id);
                  const isDimmedByHover = hoverActive && !isLinked;
                  return (
                    <div
                      key={o.id}
                      style={{
                        opacity: isDimmedByHover ? 0.35 : 1,
                        transition: "opacity 180ms ease-out",
                      }}
                    >
                      <OutcomeCard
                        item={o}
                        linked={isLinked}
                        onHover={setHoveredEntityId}
                        producedBy={producedByMap.get(o.id) ?? []}
                        dissolves={outcomeDissolvesMap.get(o.id) ?? []}
                        rollsUp={rollsUpSet.has(o.id)}
                        subCategory={categoryFor("result", o.sub_category_slug)}
                      />
                    </div>
                  );
                })}
              </ul>
            </Lane>
          </div>
        </div>

        {/* Always render the side panel — even with 0 edges. The
            empty state inside the panel surfaces a "Generate
            correlations" CTA so a soft-failed correlation step is
            recoverable without regenerating the entire room. */}
        {generatedAt && (
          <CorrelationSidePanel
            spaceId={spaceId}
            subObjectiveId={subObjectiveId}
            edges={edges}
            entityIndex={entityIndex}
            approvedEdgeIds={approvedEdgeIds}
            onApprovalChange={handleApprovalChange}
            // Panel→cards hover-to-link: panel sets the same
            // hoveredEntityId state the cards do, so linkedIds
            // derivation works in both directions.
            onHoverEntity={setHoveredEntityId}
            laneLabels={{
              pain: lanes.find((l) => l.slug === "pain")!.label,
              features: lanes.find((l) => l.slug === "features")!.label,
              outcomes: lanes.find((l) => l.slug === "outcomes")!.label,
              objective: lanes.find((l) => l.slug === "objective")!.label,
            }}
            detail={{
              rootCausesById: new Map(
                painItems.map((p) => [p.id, p.root_causes]),
              ),
              firstPrinciplesById: new Map(
                featureItems.map((f) => [f.id, f.first_principles]),
              ),
              measuredByById: new Map(
                outcomeItems.map((o) => [o.id, o.measured_by ?? null]),
              ),
            }}
            roomCategories={roomCategories}
          />
        )}
      </div>

    </div>
  );
}

// ── Lane shell ─────────────────────────────────────────────────────

function Lane({
  slug,
  label,
  color,
  count,
  loading,
  children,
}: {
  slug: "pain" | "features" | "outcomes" | "objective";
  label: string;
  color: string;
  count: number;
  loading: boolean;
  children: React.ReactNode;
}) {
  void slug;
  return (
    <div
      className="flex min-h-[260px] flex-col rounded-3xl p-4"
      style={{
        background: appleVibe.surface.card,
        border: `1px solid ${appleVibe.stroke.hairline}`,
        borderRadius: appleVibe.radius.xl,
      }}
    >
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span
            className="h-2.5 w-2.5 flex-shrink-0 rounded-full"
            style={{ background: color }}
            aria-hidden
          />
          <h3
            className="text-[13px] font-semibold tracking-tight"
            style={{ color: appleVibe.text.primary }}
          >
            {label}
          </h3>
        </div>
        <span
          className="rounded-full px-1.5 py-0.5 text-[10px] font-semibold"
          style={{
            background: appleVibe.surface.chip,
            color: appleVibe.text.tertiary,
          }}
        >
          {count}
        </span>
      </div>

      <div className="mt-3 flex-1">
        {loading ? (
          <div className="flex flex-col gap-2">
            <SkeletonItem />
            <SkeletonItem />
          </div>
        ) : (
          children
        )}
      </div>
    </div>
  );
}

function SkeletonItem() {
  return (
    <div
      className="h-14 rounded-2xl"
      style={{
        background: appleVibe.surface.chip,
        borderRadius: appleVibe.radius.md,
      }}
    />
  );
}

function EmptyHint() {
  return (
    <div
      className="rounded-2xl border border-dashed px-3 py-3 text-center text-[11.5px] font-light"
      style={{
        borderColor: appleVibe.stroke.hairline,
        color: appleVibe.text.tertiary,
        borderRadius: appleVibe.radius.md,
      }}
    >
      empty
    </div>
  );
}
