"use client";

// ── Learning loop card ──────────────────────────────────────────────
//
// P1.1 (operational whiteboard): the strategy's StrategyLearningLoop
// rendered as a tldraw shape inside the Twin room. This is the most
// operationally valuable field generated by strategy LLMs — leading
// indicators (with green/yellow/red thresholds), pivot criteria,
// persistence signals — and until now it was invisible on the canvas.
//
// Today the same data is rendered as nodes inside the off-canvas
// strategy-page's whiteboard-view (build-whiteboard-model.ts:422-459).
// This shape surfaces it on the actual tldraw canvas next to the
// twin-snapshot, closing the post-approval dashboard gap.
//
// Card layout (360 × 360):
//   ┌─────────────────────────────────────┐
//   │  [●] LEARNING LOOP   captured 1h ago│  ← header (accent rail + eyebrow)
//   ├─────────────────────────────────────┤
//   │  📊 Lagging indicator                │
//   │  <metric>           → <target>       │
//   │  by <deadline>                       │  ← lagging block (prominent)
//   ├─────────────────────────────────────┤
//   │  Leading indicators                  │
//   │  [G/Y/R] <metric>           <cadence>│
//   │  [G/Y/R] <metric>           <cadence>│
//   │  [G/Y/R] <metric>           <cadence>│  ← up to 4 rows
//   │  [G/Y/R] <metric>           <cadence>│
//   ├─────────────────────────────────────┤
//   │  Review weekly · 3 pivot criteria    │
//   │  · 2 persistence signals             │  ← footer chips
//   └─────────────────────────────────────┘

import { useMemo } from "react";
import {
  BaseBoxShapeUtil,
  HTMLContainer,
  T,
  type RecordProps,
  type TLResizeInfo,
  resizeBox,
} from "tldraw";
import { Activity, Target, Compass, RefreshCcw, Shield } from "lucide-react";
import type { LearningLoopCardShape } from "./types";

export const LEARNING_LOOP_DEFAULT_W = 360;
export const LEARNING_LOOP_DEFAULT_H = 360;

interface LeadingIndicator {
  metric: string;
  cadence: "daily" | "weekly" | "biweekly" | "monthly" | string;
  green_reading?: string;
  yellow_reading?: string;
  red_reading?: string;
  measurement_method?: string;
  /** Optional live status — set externally when a tracker resolves. */
  status?: "green" | "yellow" | "red" | "unknown";
}

interface PivotCriterion {
  signal: string;
  response?:
    | "revise_diagnosis"
    | "revise_bottleneck"
    | "revise_policy"
    | "abandon"
    | "accelerate"
    | string;
  specific_action?: string;
  timeline?: string;
}

const STATUS_COLOR: Record<NonNullable<LeadingIndicator["status"]>, string> = {
  green: "#10B981",
  yellow: "#F59E0B",
  red: "#EF4444",
  unknown: "#94A3B8",
};

export class LearningLoopCardShapeUtil extends BaseBoxShapeUtil<LearningLoopCardShape> {
  static override type = "learning-loop-card" as const;
  static override props: RecordProps<LearningLoopCardShape> = {
    w: T.number,
    h: T.number,
    spaceId: T.string,
    capturedAt: T.string,
    laggingMetric: T.string,
    laggingTarget: T.string,
    laggingDeadline: T.string,
    leadingIndicatorsJson: T.string,
    metricCheckCadence: T.string,
    reviewCadence: T.string,
    totalCycles: T.number,
    pivotCriteriaJson: T.string,
    persistenceCount: T.number,
    accent: T.string,
  };

  override canResize = () => true;
  override canEdit = () => false;

  override onResize = (
    shape: LearningLoopCardShape,
    info: TLResizeInfo<LearningLoopCardShape>,
  ) => resizeBox(shape, info);

  getDefaultProps(): LearningLoopCardShape["props"] {
    return {
      w: LEARNING_LOOP_DEFAULT_W,
      h: LEARNING_LOOP_DEFAULT_H,
      spaceId: "",
      capturedAt: new Date().toISOString(),
      laggingMetric: "",
      laggingTarget: "",
      laggingDeadline: "",
      leadingIndicatorsJson: "[]",
      metricCheckCadence: "",
      reviewCadence: "",
      totalCycles: 0,
      pivotCriteriaJson: "[]",
      persistenceCount: 0,
      accent: "#7C3AED",
    };
  }

  component(shape: LearningLoopCardShape) {
    return <LearningLoopCardView shape={shape} />;
  }

  indicator(shape: LearningLoopCardShape) {
    return <rect width={shape.props.w} height={shape.props.h} rx={10} ry={10} />;
  }
}

function LearningLoopCardView({ shape }: { shape: LearningLoopCardShape }) {
  const {
    w,
    h,
    accent,
    capturedAt,
    laggingMetric,
    laggingTarget,
    laggingDeadline,
    leadingIndicatorsJson,
    metricCheckCadence,
    reviewCadence,
    totalCycles,
    pivotCriteriaJson,
    persistenceCount,
  } = shape.props;

  const { leadingIndicators, pivotCriteria } = useMemo(() => {
    let leading: LeadingIndicator[] = [];
    let pivots: PivotCriterion[] = [];
    try {
      const parsedLeading = JSON.parse(leadingIndicatorsJson);
      if (Array.isArray(parsedLeading)) leading = parsedLeading.slice(0, 4);
    } catch {
      /* keep empty on malformed json */
    }
    try {
      const parsedPivot = JSON.parse(pivotCriteriaJson);
      if (Array.isArray(parsedPivot)) pivots = parsedPivot;
    } catch {
      /* keep empty on malformed json */
    }
    return { leadingIndicators: leading, pivotCriteria: pivots };
  }, [leadingIndicatorsJson, pivotCriteriaJson]);

  const capturedAgo = useMemo(() => formatAgo(capturedAt), [capturedAt]);

  const hasLagging = laggingMetric.trim().length > 0;

  return (
    <HTMLContainer
      style={{
        width: w,
        height: h,
        background: "white",
        borderRadius: 10,
        border: "1px solid rgba(15,23,42,0.08)",
        boxShadow:
          "0 1px 2px rgba(15,23,42,0.04), 0 4px 16px -8px rgba(15,23,42,0.08)",
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
        pointerEvents: "all",
      }}
    >
      {/* ── Header ── */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          padding: "10px 14px",
          borderBottom: "1px solid rgba(15,23,42,0.06)",
          gap: 8,
        }}
      >
        <div
          style={{
            width: 22,
            height: 22,
            borderRadius: 6,
            background: `${accent}22`,
            color: accent,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Activity size={13} />
        </div>
        <div
          style={{
            fontSize: 9.5,
            fontWeight: 700,
            letterSpacing: "0.12em",
            textTransform: "uppercase",
            color: accent,
            flex: 1,
          }}
        >
          Learning Loop
        </div>
        <span
          style={{
            fontSize: 10,
            color: "rgba(15,23,42,0.4)",
            fontFamily: "ui-monospace, monospace",
          }}
        >
          {capturedAgo}
        </span>
      </div>

      {/* ── Lagging indicator block ── */}
      <div
        style={{
          padding: "10px 14px",
          background: `${accent}08`,
          borderBottom: "1px solid rgba(15,23,42,0.04)",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 5,
            fontSize: 8.5,
            fontWeight: 700,
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            color: "rgba(15,23,42,0.45)",
            marginBottom: 4,
          }}
        >
          <Target size={11} /> Lagging indicator
        </div>
        {hasLagging ? (
          <>
            <div
              style={{
                fontSize: 12.5,
                fontWeight: 600,
                color: "#0F172A",
                marginBottom: 2,
                lineHeight: 1.3,
              }}
            >
              {laggingMetric}
            </div>
            <div
              style={{
                fontSize: 11,
                color: "rgba(15,23,42,0.6)",
              }}
            >
              → {laggingTarget || "no target set"}
              {laggingDeadline ? ` · by ${laggingDeadline}` : ""}
            </div>
          </>
        ) : (
          <div
            style={{
              fontSize: 11,
              fontStyle: "italic",
              color: "rgba(15,23,42,0.4)",
            }}
          >
            No lagging indicator captured
          </div>
        )}
      </div>

      {/* ── Leading indicators ── */}
      <div
        style={{
          padding: "8px 14px",
          flex: 1,
          overflow: "hidden",
          display: "flex",
          flexDirection: "column",
          gap: 4,
        }}
      >
        <div
          style={{
            fontSize: 8.5,
            fontWeight: 700,
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            color: "rgba(15,23,42,0.45)",
            marginBottom: 2,
          }}
        >
          Leading indicators · {leadingIndicators.length}
        </div>
        {leadingIndicators.length === 0 ? (
          <div
            style={{
              fontSize: 11,
              fontStyle: "italic",
              color: "rgba(15,23,42,0.4)",
            }}
          >
            No leading indicators captured
          </div>
        ) : (
          leadingIndicators.map((li, i) => (
            <LeadingRow key={`${li.metric}-${i}`} indicator={li} />
          ))
        )}
      </div>

      {/* ── Footer ── */}
      <div
        style={{
          padding: "8px 14px",
          borderTop: "1px solid rgba(15,23,42,0.06)",
          display: "flex",
          alignItems: "center",
          gap: 6,
          flexWrap: "wrap",
          fontSize: 10,
          color: "rgba(15,23,42,0.55)",
        }}
      >
        {(reviewCadence || metricCheckCadence) && (
          <span
            style={chipStyle}
            title={
              metricCheckCadence
                ? `Check metrics ${metricCheckCadence}`
                : undefined
            }
          >
            <RefreshCcw size={9} style={{ marginRight: 3 }} />
            Review {reviewCadence || metricCheckCadence}
            {totalCycles > 0 ? ` · ${totalCycles} cycles` : ""}
          </span>
        )}
        {pivotCriteria.length > 0 && (
          <span
            style={chipStyle}
            title={pivotCriteria
              .slice(0, 3)
              .map((p) => p.signal)
              .join(" · ")}
          >
            <Compass size={9} style={{ marginRight: 3 }} />
            {pivotCriteria.length} pivot
            {pivotCriteria.length === 1 ? "" : "s"}
          </span>
        )}
        {persistenceCount > 0 && (
          <span style={chipStyle}>
            <Shield size={9} style={{ marginRight: 3 }} />
            {persistenceCount} persistence
          </span>
        )}
      </div>
    </HTMLContainer>
  );
}

const chipStyle: React.CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  padding: "2px 7px",
  borderRadius: 999,
  background: "rgba(15,23,42,0.04)",
  fontSize: 9.5,
  fontWeight: 500,
};

function LeadingRow({ indicator }: { indicator: LeadingIndicator }) {
  const status = indicator.status ?? "unknown";
  const color = STATUS_COLOR[status as keyof typeof STATUS_COLOR] ?? STATUS_COLOR.unknown;
  // Tooltip shows the full G/Y/R thresholds so the user can see the
  // decision rule without expanding the card.
  const tooltip = [
    indicator.green_reading ? `Green: ${indicator.green_reading}` : null,
    indicator.yellow_reading ? `Yellow: ${indicator.yellow_reading}` : null,
    indicator.red_reading ? `Red: ${indicator.red_reading}` : null,
    indicator.measurement_method
      ? `Method: ${indicator.measurement_method}`
      : null,
  ]
    .filter(Boolean)
    .join("\n");

  return (
    <div
      title={tooltip || undefined}
      style={{
        display: "flex",
        alignItems: "center",
        gap: 7,
        padding: "3px 0",
        borderBottom: "1px solid rgba(15,23,42,0.03)",
      }}
    >
      <span
        style={{
          width: 8,
          height: 8,
          borderRadius: "50%",
          background: color,
          flexShrink: 0,
        }}
        aria-hidden
      />
      <span
        style={{
          flex: 1,
          fontSize: 11,
          color: "#0F172A",
          overflow: "hidden",
          textOverflow: "ellipsis",
          whiteSpace: "nowrap",
        }}
      >
        {indicator.metric}
      </span>
      <span
        style={{
          fontSize: 9.5,
          color: "rgba(15,23,42,0.5)",
          fontFamily: "ui-monospace, monospace",
          textTransform: "lowercase",
        }}
      >
        {indicator.cadence}
      </span>
    </div>
  );
}

function formatAgo(iso: string): string {
  try {
    const t = new Date(iso).getTime();
    if (Number.isNaN(t)) return "";
    const ms = Date.now() - t;
    const s = Math.floor(ms / 1000);
    if (s < 60) return "just now";
    const m = Math.floor(s / 60);
    if (m < 60) return `${m}m ago`;
    const hr = Math.floor(m / 60);
    if (hr < 24) return `${hr}h ago`;
    const d = Math.floor(hr / 24);
    return `${d}d ago`;
  } catch {
    return "";
  }
}
