// ── Brainstorm Sessions — CRUD helpers ──────────────────────────────
//
// Thin wrappers over the brainstorm_sessions table (migration
// 20260907_brainstorm_sessions.sql). One row = one user press of
// `Brainstorm`; columns are JSONB blobs typed by session-types.ts.
//
// Conventions match src/lib/objective-canvas/decision-log.ts:
//   • `db: any` — the supabase client is passed loose so the same
//     helpers work for the user-RLS client (route handlers) and the
//     service-role client (runner orchestrator).
//   • Telemetry / non-blocking ops soft-fail with console.warn — they
//     must NEVER break the user-facing flow.
//   • PRIMARY mutations (create, settle) throw on failure — the runner
//     needs to know if the session row didn't land so it can degrade
//     gracefully or surface an error in the panel.
//
// Spec: BRAINSTORM_MODULE_SPEC.md §5.

import { logDecision } from "@/lib/objective-canvas/decision-log";
import type {
  BrainstormCleanup,
  BrainstormCompletedMetadata,
  BrainstormGeneration,
  BrainstormPlan,
  BrainstormRanking,
  BrainstormSession,
  BrainstormSessionStatus,
  BrainstormStartedMetadata,
  BrainstormTargetKind,
  BrainstormUserIdea,
} from "./session-types";

// ── Create ──────────────────────────────────────────────────────────

export interface CreateSessionArgs {
  userId: string;
  spaceId: string;
  targetKind: BrainstormTargetKind;
  subObjectiveId?: string | null;
  entityId?: string | null;
  /** Auto-generated by the panel ("Brainstorm · 2026-05-29 · creative+contrarian+gap_fill")
   *  but caller can override. User can rename later. */
  title?: string | null;
  /** tldraw page id the panel created on the existing objective board.
   *  Stored here so reopen / collapse / library re-open all find it. */
  tldrawPageId?: string | null;
}

/** Insert a fresh brainstorm session row in `running` status. Plan is
 *  empty until Stage 1 commits via commitPlan(). Throws on failure —
 *  the runner cannot proceed without a session id. */
export async function createSession(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any,
  args: CreateSessionArgs,
): Promise<BrainstormSession> {
  const { data, error } = await db
    .from("brainstorm_sessions")
    .insert({
      user_id: args.userId,
      space_id: args.spaceId,
      target_kind: args.targetKind,
      sub_objective_id: args.subObjectiveId ?? null,
      entity_id: args.entityId ?? null,
      title: args.title ?? null,
      tldraw_page_id: args.tldrawPageId ?? null,
      plan: {},
      generations: [],
      user_added_ideas: [],
      status: "running" satisfies BrainstormSessionStatus,
    })
    .select("*")
    .single();
  if (error || !data) {
    throw new Error(
      `[brainstorm/sessions] create failed: ${error?.message ?? "no row returned"}`,
    );
  }
  return data as BrainstormSession;
}

// ── Stage 1: commit plan + log brainstorm_started ──────────────────

export interface CommitPlanArgs {
  userId: string;
  spaceId: string;
  sessionId: string;
  plan: BrainstormPlan;
}

/** Persist the locked 3-intent plan and fire the brainstorm_started
 *  decision_log event. Returns true on success — failure here is
 *  soft (the runner can still try the divergence loop, it just won't
 *  re-hydrate the plan on reload). */
export async function commitPlan(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any,
  args: CommitPlanArgs,
): Promise<boolean> {
  try {
    const { error } = await db
      .from("brainstorm_sessions")
      .update({ plan: args.plan })
      .eq("id", args.sessionId);
    if (error) {
      console.warn("[brainstorm/sessions] commit plan failed:", error.message);
      return false;
    }
  } catch (err) {
    console.warn(
      "[brainstorm/sessions] commit plan threw:",
      err instanceof Error ? err.message : String(err),
    );
    return false;
  }

  // Audible decision_log event — soft-fails on its own.
  const metadata: BrainstormStartedMetadata = {
    session_id: args.sessionId,
    target_kind: "sub_objective_picker", // Phase 1
    planned_intents: args.plan.intents,
    intent_reasons: args.plan.reasons,
  };
  void logDecision(db, {
    userId: args.userId,
    spaceId: args.spaceId,
    action: "brainstorm_started",
    metadata: metadata as unknown as Record<string, unknown>,
  });

  return true;
}

// ── Stage 2: append a divergence batch ──────────────────────────────

/** Append one /propose result to the session's generations[] array.
 *  Read-modify-write so concurrent appends serialise — the runner
 *  fires intents sequentially, so contention is not expected. Returns
 *  the new generations length on success, null on failure. */
export async function appendGeneration(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any,
  sessionId: string,
  generation: BrainstormGeneration,
): Promise<number | null> {
  try {
    const { data: row, error: readErr } = await db
      .from("brainstorm_sessions")
      .select("generations")
      .eq("id", sessionId)
      .single();
    if (readErr || !row) {
      console.warn(
        "[brainstorm/sessions] append generation read failed:",
        readErr?.message ?? "no row",
      );
      return null;
    }
    const existing = (row.generations as BrainstormGeneration[]) ?? [];
    const next = [...existing, generation];
    const { error: writeErr } = await db
      .from("brainstorm_sessions")
      .update({ generations: next })
      .eq("id", sessionId);
    if (writeErr) {
      console.warn(
        "[brainstorm/sessions] append generation write failed:",
        writeErr.message,
      );
      return null;
    }
    return next.length;
  } catch (err) {
    console.warn(
      "[brainstorm/sessions] append generation threw:",
      err instanceof Error ? err.message : String(err),
    );
    return null;
  }
}

// ── Stage 3: cleanup pass result ────────────────────────────────────

export async function setCleanup(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any,
  sessionId: string,
  cleanup: BrainstormCleanup,
): Promise<boolean> {
  try {
    const { error } = await db
      .from("brainstorm_sessions")
      .update({ cleanup })
      .eq("id", sessionId);
    if (error) {
      console.warn("[brainstorm/sessions] set cleanup failed:", error.message);
      return false;
    }
    return true;
  } catch (err) {
    console.warn(
      "[brainstorm/sessions] set cleanup threw:",
      err instanceof Error ? err.message : String(err),
    );
    return false;
  }
}

// ── Stage 4: ranking + settle + log brainstorm_completed ───────────

export interface SettleArgs {
  userId: string;
  spaceId: string;
  sessionId: string;
  ranking: BrainstormRanking;
  /** Brief one-liner for the library row, e.g. "12 candidates, top 3
   *  pinned, 2 user ideas added". Computed by the runner. */
  outcomeSummary: string;
}

/** Atomically: set ranking, flip status='settled', stamp settled_at,
 *  and fire brainstorm_completed. Critical mutation — throws if the
 *  row update fails (the panel needs settled state to render Stage 5). */
export async function settle(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any,
  args: SettleArgs,
): Promise<void> {
  const settledAt = new Date().toISOString();
  const { error } = await db
    .from("brainstorm_sessions")
    .update({
      ranking: args.ranking,
      status: "settled" satisfies BrainstormSessionStatus,
      settled_at: settledAt,
      outcome_summary: args.outcomeSummary,
    })
    .eq("id", args.sessionId);
  if (error) {
    throw new Error(`[brainstorm/sessions] settle failed: ${error.message}`);
  }

  // Per-ribbon tally for the audible event.
  let nTop = 0;
  let nExplore = 0;
  let nTray = 0;
  for (const c of args.ranking.candidates) {
    if (c.ribbon === "green") nTop++;
    else if (c.ribbon === "amber") nExplore++;
    else nTray++;
  }

  const metadata: BrainstormCompletedMetadata = {
    session_id: args.sessionId,
    n_candidates: args.ranking.candidates.length,
    n_top: nTop,
    n_explore: nExplore,
    n_tray: nTray,
    latency_ms: args.ranking.latency_ms,
  };
  void logDecision(db, {
    userId: args.userId,
    spaceId: args.spaceId,
    action: "brainstorm_completed",
    metadata: metadata as unknown as Record<string, unknown>,
  });
}

// ── Stage 5: user-added ideas ───────────────────────────────────────

/** Append a sticky-note idea the user dropped on the brainstorm page.
 *  The runner / panel may later score it via patchUserIdea(). Soft-
 *  fails (the sticky still renders client-side from local state). */
export async function appendUserIdea(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any,
  sessionId: string,
  idea: BrainstormUserIdea,
): Promise<boolean> {
  try {
    const { data: row, error: readErr } = await db
      .from("brainstorm_sessions")
      .select("user_added_ideas")
      .eq("id", sessionId)
      .single();
    if (readErr || !row) {
      console.warn(
        "[brainstorm/sessions] append idea read failed:",
        readErr?.message ?? "no row",
      );
      return false;
    }
    const existing = (row.user_added_ideas as BrainstormUserIdea[]) ?? [];
    const next = [...existing, idea];
    const { error: writeErr } = await db
      .from("brainstorm_sessions")
      .update({ user_added_ideas: next })
      .eq("id", sessionId);
    if (writeErr) {
      console.warn(
        "[brainstorm/sessions] append idea write failed:",
        writeErr.message,
      );
      return false;
    }
    return true;
  } catch (err) {
    console.warn(
      "[brainstorm/sessions] append idea threw:",
      err instanceof Error ? err.message : String(err),
    );
    return false;
  }
}

/** Patch a single user idea (typically: after the critique pass scores
 *  it). Soft-fails — the score chip on the sticky just won't appear. */
export async function patchUserIdea(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any,
  sessionId: string,
  ideaId: string,
  patch: Partial<BrainstormUserIdea>,
): Promise<boolean> {
  try {
    const { data: row, error: readErr } = await db
      .from("brainstorm_sessions")
      .select("user_added_ideas")
      .eq("id", sessionId)
      .single();
    if (readErr || !row) {
      console.warn(
        "[brainstorm/sessions] patch idea read failed:",
        readErr?.message ?? "no row",
      );
      return false;
    }
    const existing = (row.user_added_ideas as BrainstormUserIdea[]) ?? [];
    const next = existing.map((i) => (i.id === ideaId ? { ...i, ...patch } : i));
    const { error: writeErr } = await db
      .from("brainstorm_sessions")
      .update({ user_added_ideas: next })
      .eq("id", sessionId);
    if (writeErr) {
      console.warn(
        "[brainstorm/sessions] patch idea write failed:",
        writeErr.message,
      );
      return false;
    }
    return true;
  } catch (err) {
    console.warn(
      "[brainstorm/sessions] patch idea threw:",
      err instanceof Error ? err.message : String(err),
    );
    return false;
  }
}

// ── Lifecycle ──────────────────────────────────────────────────────

/** Flip the session to `abandoned`. Used when the user closes the
 *  panel before settle, or the runner errored hard mid-pipeline. */
export async function abandon(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any,
  sessionId: string,
): Promise<boolean> {
  try {
    const { error } = await db
      .from("brainstorm_sessions")
      .update({
        status: "abandoned" satisfies BrainstormSessionStatus,
        settled_at: new Date().toISOString(),
      })
      .eq("id", sessionId);
    if (error) {
      console.warn("[brainstorm/sessions] abandon failed:", error.message);
      return false;
    }
    return true;
  } catch (err) {
    console.warn(
      "[brainstorm/sessions] abandon threw:",
      err instanceof Error ? err.message : String(err),
    );
    return false;
  }
}

/** Toggle the library pin. Pinned sessions surface in the brainstorm
 *  library lens; unpinned sessions are still readable by id (e.g. via
 *  the page's tldraw page id) but don't appear in the list view. */
export async function setPinned(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any,
  sessionId: string,
  pinned: boolean,
): Promise<boolean> {
  try {
    const { error } = await db
      .from("brainstorm_sessions")
      .update({ pinned })
      .eq("id", sessionId);
    if (error) {
      console.warn(
        "[brainstorm/sessions] set pinned failed:",
        error.message,
      );
      return false;
    }
    return true;
  } catch (err) {
    console.warn(
      "[brainstorm/sessions] set pinned threw:",
      err instanceof Error ? err.message : String(err),
    );
    return false;
  }
}

// ── Reads ──────────────────────────────────────────────────────────

/** Fetch a single session by id (for re-opening from library or
 *  re-hydrating the panel after navigation). Returns null on miss
 *  or RLS reject. */
export async function getSession(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any,
  sessionId: string,
): Promise<BrainstormSession | null> {
  try {
    const { data, error } = await db
      .from("brainstorm_sessions")
      .select("*")
      .eq("id", sessionId)
      .single();
    if (error || !data) {
      console.warn(
        "[brainstorm/sessions] get failed:",
        error?.message ?? "no row",
      );
      return null;
    }
    return data as BrainstormSession;
  } catch (err) {
    console.warn(
      "[brainstorm/sessions] get threw:",
      err instanceof Error ? err.message : String(err),
    );
    return null;
  }
}

export interface ListSessionsArgs {
  spaceId?: string;
  /** Library view: only pinned sessions across all the user's spaces. */
  onlyPinned?: boolean;
  /** Default 50, max 200. */
  limit?: number;
}

/** List sessions for the library lens / picker history dropdown. RLS
 *  scopes to the current user. Returns newest-first by started_at.
 *  Pinned-only mode uses the dedicated partial index. */
export async function listSessions(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any,
  args: ListSessionsArgs = {},
): Promise<BrainstormSession[]> {
  const limit = Math.min(Math.max(args.limit ?? 50, 1), 200);
  try {
    let q = db
      .from("brainstorm_sessions")
      .select("*")
      .order("started_at", { ascending: false })
      .limit(limit);
    if (args.spaceId) q = q.eq("space_id", args.spaceId);
    if (args.onlyPinned) q = q.eq("pinned", true);
    const { data, error } = await q;
    if (error) {
      console.warn("[brainstorm/sessions] list failed:", error.message);
      return [];
    }
    return (data ?? []) as BrainstormSession[];
  } catch (err) {
    console.warn(
      "[brainstorm/sessions] list threw:",
      err instanceof Error ? err.message : String(err),
    );
    return [];
  }
}
