// ── Layer Ontology types ─────────────────────────────────────────
//
// Per-space layer hierarchy that replaces the hardcoded
// `knowledge_layer` enum (internal/conceptual/external/bridge) for
// domain-rigorous KG modeling. See:
//   - supabase/migrations/20260615_layer_ontology.sql (DDL)
//   - src/types/layer.ts (legacy enum, still supported as fallback)
//
// Ontologies come from three sources:
//   1. starter (template) — pre-built, picked by planner
//   2. research_agent — deep-research agent generates a custom one
//      grounded in the user's prompt + papers + scope
//   3. user_authored — researcher hand-types
// (plus "hybrid" for mixed origins.)

/** One layer in a per-space ontology. Mirrors the layer object stored
 *  in layer_ontology_templates.layers JSONB and the layer_ontology
 *  row schema. */
export interface OntologyLayerDefinition {
  ordinal: number;
  slug: string;
  label: string;
  description: string;
  /** Hex color used by KGNodeShape for layer-aware visual rendering. */
  color: string;
  /** Free-text array of node kinds this layer typically contains.
   *  Drives the +Variable button's contextual kind picker. */
  typical_node_kinds: string[];
  /** Optional examples shown in the Plan Review Card so users can
   *  judge whether the layer fits their intent. */
  example_nodes?: string[];
}

/** Provenance of a per-space layer row. */
export type OntologySource =
  | "starter"
  | "research_agent"
  | "user_authored"
  | "hybrid";

/** Trace recorded when a layer is generated by the research agent. */
export interface OntologyResearchTrace {
  agent_model: string;
  prompt_hash: string;
  /** Free-text array of source identifiers (paper titles, URLs,
   *  user-uploaded ingested_file ids). */
  sources_consulted: string[];
  reasoning_summary: string;
  generated_at: string;
  /** 0..1 self-rated confidence in the layer choice. */
  planner_confidence: number;
}

/** Pre-built starter ontology row. */
export interface LayerOntologyTemplate {
  id: string;
  slug: string;
  label: string;
  description: string;
  domain_tags: string[];
  /** JSONB shape: { version: number, layers: OntologyLayerDefinition[] } */
  layers: {
    version: number;
    layers: OntologyLayerDefinition[];
  };
  author: string;
  source_citations: string[];
  status: "active" | "experimental" | "deprecated";
  created_at: string;
  updated_at: string;
}

/** Materialized per-space layer row. */
export interface LayerOntologyRow {
  id: string;
  space_id: string;
  user_id: string;
  ordinal: number;
  slug: string;
  label: string;
  description: string | null;
  color: string | null;
  typical_node_kinds: string[];
  ontology_source: OntologySource;
  template_id: string | null;
  research_trace: OntologyResearchTrace | null;
  source_plan_id: string | null;
  created_at: string;
  updated_at: string;
}

// ── D-track Phase α — layer dependency cascades ─────────────────────
//
// Mirrors the `layer_dependencies` table (migration 20260720). Each
// row is one durable layer→layer cascade claim. See the migration's
// header for the distinction from `bridges` (entity-level) and
// `cross_layer_analysis` on synthesis_data (tension detection).
//
// Bidirectional cascades are encoded as two separate rows (A→B + B→A).
// The migration's unique constraint allows this; the strategy engine
// treats them as a feedback pair when both are present and `kind` is
// `reinforcing` on either side.

/** Closed enum of inter-layer propagation semantics. Matches the
 *  CHECK constraint on layer_dependencies.kind. */
export type LayerDependencyKind =
  | "causal"        // A causes B (one-way mechanistic)
  | "modulatory"    // A scales the response of B
  | "inhibitory"    // A suppresses B
  | "compensatory"  // A buffers B against perturbation
  | "reinforcing";  // A and B form a positive feedback

/** Provenance for the row's authorship. */
export type LayerDependencySource =
  | "llm_inferred"
  | "user_authored"
  | "evidence_derived"
  | "hybrid";

export interface LayerDependencyRow {
  id: string;
  space_id: string;
  user_id: string;
  /** FK to layer_ontology.id — the layer whose changes propagate. */
  from_layer_id: string;
  /** FK to layer_ontology.id — the layer that is affected. */
  to_layer_id: string;
  kind: LayerDependencyKind;
  /** 0..1; strategy engine multiplies this against intervention
   *  magnitude when projecting cascade effects. */
  strength: number;
  /** Human-readable lag ("minutes", "weeks", "varies"). Nullable when
   *  the LLM declines to commit to a temporal estimate. */
  lag_label: string | null;
  /** Numeric lag estimate in hours. Nullable when uncertain. Used by
   *  the trajectory-fan projection math when present. */
  lag_hours: number | null;
  /** 1-2 sentences naming the mechanism behind the propagation. */
  mechanism: string;
  /** Optional supporting evidence summary (free-text). */
  evidence_summary: string | null;
  /** 0..1 — how confident the source is in this cascade claim. */
  confidence: number;
  source: LayerDependencySource;
  /** When `source === "llm_inferred"`, names the synthesis step that
   *  emitted the row (e.g. "synthesize-cascade-prediction"). Useful
   *  for audit + re-running just that step. */
  source_synthesis_step: string | null;
  generated_at: string;
  updated_at: string;
}
