// ── Layer Ontology types ─────────────────────────────────────────
//
// Per-space layer hierarchy that replaces the hardcoded
// `knowledge_layer` enum (internal/conceptual/external/bridge) for
// domain-rigorous KG modeling. See:
//   - supabase/migrations/20260615_layer_ontology.sql (DDL)
//   - src/types/layer.ts (legacy enum, still supported as fallback)
//
// Ontologies come from three sources:
//   1. starter (template) — pre-built, picked by planner
//   2. research_agent — deep-research agent generates a custom one
//      grounded in the user's prompt + papers + scope
//   3. user_authored — researcher hand-types
// (plus "hybrid" for mixed origins.)

/** One layer in a per-space ontology. Mirrors the layer object stored
 *  in layer_ontology_templates.layers JSONB and the layer_ontology
 *  row schema. */
export interface OntologyLayerDefinition {
  ordinal: number;
  slug: string;
  label: string;
  description: string;
  /** Hex color used by KGNodeShape for layer-aware visual rendering. */
  color: string;
  /** Free-text array of node kinds this layer typically contains.
   *  Drives the +Variable button's contextual kind picker. */
  typical_node_kinds: string[];
  /** Optional examples shown in the Plan Review Card so users can
   *  judge whether the layer fits their intent. */
  example_nodes?: string[];
}

/** Provenance of a per-space layer row. */
export type OntologySource =
  | "starter"
  | "research_agent"
  | "user_authored"
  | "hybrid";

/** Trace recorded when a layer is generated by the research agent. */
export interface OntologyResearchTrace {
  agent_model: string;
  prompt_hash: string;
  /** Free-text array of source identifiers (paper titles, URLs,
   *  user-uploaded ingested_file ids). */
  sources_consulted: string[];
  reasoning_summary: string;
  generated_at: string;
  /** 0..1 self-rated confidence in the layer choice. */
  planner_confidence: number;
}

/** Pre-built starter ontology row. */
export interface LayerOntologyTemplate {
  id: string;
  slug: string;
  label: string;
  description: string;
  domain_tags: string[];
  /** JSONB shape: { version: number, layers: OntologyLayerDefinition[] } */
  layers: {
    version: number;
    layers: OntologyLayerDefinition[];
  };
  author: string;
  source_citations: string[];
  status: "active" | "experimental" | "deprecated";
  created_at: string;
  updated_at: string;
}

/** Materialized per-space layer row. */
export interface LayerOntologyRow {
  id: string;
  space_id: string;
  user_id: string;
  ordinal: number;
  slug: string;
  label: string;
  description: string | null;
  color: string | null;
  typical_node_kinds: string[];
  ontology_source: OntologySource;
  template_id: string | null;
  research_trace: OntologyResearchTrace | null;
  source_plan_id: string | null;
  created_at: string;
  updated_at: string;
}
