// Rich synthesis data stored in spaces.synthesis_data JSONB column
// Generated by Pass 3 synthesis agent

export interface WhenMatters {
  situation: string;
  impact: string;
  intensity: "high" | "mid" | "low";
}

export interface ActionAlternative {
  when: string;
  approach: string;
  tradeoff: string;
}

export type InsightStatus = "accepted" | "investigating" | "dismissed" | null;

export interface RichLeveragePoint {
  entity_id: string;
  entity_name?: string;
  summary: string;
  reasoning: string[];
  how_it_works: string[];
  when_matters: WhenMatters[];
  action: {
    primary: string;
    alternatives: ActionAlternative[];
  };
  connections: string[];
  insight_status?: InsightStatus;
}

export interface RichRiskPoint {
  entity_id: string;
  entity_name?: string;
  blast_radius: number;
  summary: string;
  reasoning: string[];
  how_it_fails: string[];
  when_matters: WhenMatters[];
  mitigation: {
    primary: string;
    alternatives: ActionAlternative[];
  };
  connections: string[];
  insight_status?: InsightStatus;
}

export interface RichBottleneck {
  entity_id: string;
  blast_radius: number;
  summary: string;
  reasoning: string[];
  /** Enhancement 1: What opens up if this bottleneck is resolved */
  counterfactual_unlock?: string;
  /** Enhancement 1: Alternative constraints considered and why they were rejected */
  candidates_considered?: Array<{
    candidate: string;
    entity_id: string;
    why_not: string;
  }>;
  when_matters: WhenMatters[];
}

export interface RichFeedbackLoop {
  name: string;
  type: "positive" | "negative";
  steps: string[];
  intervention_at: number;
  explanation: string;
  how_to: string;
  when_active: WhenMatters[];
}

export interface RichScenario {
  name: string;
  conditions: string;
  outcome_label: string;
  outcome_value: string;
  probability: "likely" | "possible" | "unlikely";
}

export interface RichDiscoveredConnection {
  source_entity_id: string;
  target_entity_id: string;
  strength: "strong" | "moderate" | "speculative";
  reasoning: string;
}

export interface RichContradiction {
  assumption_text: string;
  conclusion_text: string;
  severity: "critical" | "moderate" | "minor";
  description: string;
}

export interface RichOpenQuestion {
  question: string;
  why_it_matters: string;
  what_changes?: string;
  related_entity_ids?: string[];

  // Phase 4b: answers + ranking
  /** User-supplied answer to the question (free text). */
  user_answer?: string;
  /** ISO timestamp when the user submitted the answer. */
  answered_at?: string;
  /** LLM-assigned priority — used for sort order in the UI. */
  priority?: "critical" | "high" | "medium";
  /** One-sentence rationale from the LLM explaining the priority. */
  ranking_reason?: string;
}

export interface ActionTag {
  t: string;
  c: string;
}

export interface ActionSupportingChain {
  axiom_ids?: string[];
  leverage_entity_ids?: string[];
  risk_entity_ids?: string[];
  bottleneck_entity_id?: string | null;
  hidden_signal_refs?: string[];
  cycle_refs?: string[];
  insight_convergence_ids?: string[];
  rationale?: string;
}

export interface ActionItemRich {
  text: string;
  why: string;
  tags: ActionTag[];
  dynamic_role?: "clears_threshold" | "starts_loop" | "accelerates_loop" | "linear_improvement" | "can_defer";
  cost_of_delay?: string;
  /** Provenance: upstream insight IDs that motivate this action */
  supporting_chain?: ActionSupportingChain;
}

export interface ActionTimeframe {
  label: string;
  badge: string;
  actions: ActionItemRich[];
}

export interface ActionPath {
  label: string;
  description: string;
  icon: string;
  color: string;
  timeframes: ActionTimeframe[];
}

export interface RichActionPlan {
  paths: ActionPath[];
}

export interface WorthConsidering {
  type: "analogy" | "framework" | "blind_spot" | "resource" | "precedent";
  title: string;
  description: string;
  confidence: "high" | "moderate" | "speculative";
  connected_entities: string[];
  source_note: string;
  relevance_score?: number; // 1-10, how directly applicable
  ranking_reason?: string; // why this ranks where it does
  source_origin?: "external_research" | "llm_synthesis" | "bridge_analysis"; // Phase 6 Gap 6: where this item came from
}

export type AxiomVisibility = "EXPLICIT" | "IMPLICIT" | "HIDDEN";
export type AxiomLoadBearing = "critical" | "important" | "moderate";
export type AxiomScope = "node" | "edge" | "chain" | "frame";
export type AxiomConfidence = "high" | "medium" | "low";

export interface Axiom {
  axiom_id: string;
  visibility: AxiomVisibility;
  load_bearing: AxiomLoadBearing;
  scope: AxiomScope;
  claim: string;
  if_false: string;
  rests_on: string[];
  scope_anchor: string;
  validation_path: string;
  confidence: AxiomConfidence;
}

export interface AssumptionInversion {
  /**
   * What the inversion targets:
   * - "axiom"          — the inversion inverts a load-bearing axiom (highest leverage: if the axiom fails, the whole analysis shifts)
   * - "leverage_point" — the inversion challenges a leverage point's implicit causal assumption
   * - "risk_point"     — the inversion challenges whether a risk is actually the risk (vs. a symptom)
   * - "master_bottleneck" — the inversion challenges whether the named bottleneck is the real binding constraint
   */
  target_type: "axiom" | "leverage_point" | "risk_point" | "master_bottleneck";
  /** For entity-targeted inversions: the entity_id. For axiom-targeted: the axiom_id (e.g. A2). */
  target_entity_id: string;
  original_assumption: string;
  inverted_claim: string;
  case_for_inversion: string;
  what_would_change: string;
  test: string;
  plausibility: "unlikely_but_consequential" | "coin_flip" | "more_likely_than_stated";
  /**
   * Provenance: where this inversion came from.
   * - "llm_synthesis"      — produced by the full synthesis LLM pass (highest quality, domain-grounded)
   * - "auto_from_research" — heuristic stub generated at research time from a high-impact signal
   * - "auto_from_axiom"    — heuristic stub generated from a HIDDEN or critical axiom
   * Undefined = legacy / unknown, treat as llm_synthesis for display.
   */
  source?: "llm_synthesis" | "auto_from_research" | "auto_from_axiom";
}

export type ConvergenceSignalType =
  | "axiom"
  | "bottleneck"
  | "leverage"
  | "risk"
  | "signal"
  | "inversion"
  | "blind_spot"
  | "open_question";

export interface ConvergenceSignal {
  type: ConvergenceSignalType;
  id: string;
  summary: string;
  entity_ids: string[];
}

export interface StrategyCoverageGap {
  kind: "critical_axiom" | "hidden_axiom" | "critical_risk" | "high_impact_signal";
  id: string;
  label: string;
  why_important: string;
}

export interface StrategyCoverageAudit {
  overall_coverage: number; // 0-100
  addressed_ids: string[];
  gaps: StrategyCoverageGap[];
  totals: {
    critical_axioms: number;
    hidden_axioms: number;
    critical_risks: number;
    high_impact_signals: number;
  };
  addressed_counts: {
    critical_axioms: number;
    hidden_axioms: number;
    critical_risks: number;
    high_impact_signals: number;
  };
}

export interface InsightConvergence {
  cluster_id: string;
  concern_label: string;
  shared_entity_ids: string[];
  signal_count: number;
  distinct_type_count: number;
  strength: "strong" | "moderate" | "weak";
  signals: ConvergenceSignal[];
  has_hidden_axiom: boolean;
}

export interface SignalToAction {
  signal: string;
  source: "hidden_signal" | "discovered_connection" | "domain_inference";
  connected_entities: string[];
  why_it_matters: string;
  linked_action: string;
  if_ignored: string;
}

export interface CrossContextInsight {
  insight: string;
  internal_entities: string[];
  external_entities: string[];
  confidence: "high" | "moderate" | "low";
  authority_level?: "high" | "moderate" | "low" | "unverified"; // Phase 6 Gap 5: strongest authority backing this insight
}

// Phase 6 Gap 4: Research provenance surfaced to UI
export interface ResearchProvenance {
  searches_performed: number;
  entities_from_search: number;
  entities_from_training: number;
  research_depth: string;
  top_sources: Array<{ domain: string; count: number }>;
  authority_distribution: { high: number; moderate: number; low: number; unverified: number };
  /** Whether findings are web-verified, training-only (fallback), or mixed */
  research_mode?: "web_verified" | "training_only" | "mixed";
}

export interface GoalTrajectoryEstimate {
  estimated_weeks: number;
  confidence: "high" | "moderate" | "low";
  critical_path: string[];
}

// ── Post-synthesis validation types (Gaps 1, 5) ──

export interface GoalFitnessIssue {
  type: "off_path_leverage" | "bottleneck_not_blocking_goal" | "no_goal_actions" | "off_path_risk";
  severity: "error" | "warning";
  message: string;
  entity_id?: string;
}

export interface GoalFitnessResult {
  score: number; // 0-100
  on_critical_path: string[];
  off_critical_path: string[];
  bottleneck_blocks_goal: boolean;
  action_plan_addresses_goal: boolean;
  issues: GoalFitnessIssue[];
}

export type QualityFlag =
  | "shallow_leverage"
  | "generic_actions"
  | "overconfident"
  | "ungrounded_risk"
  | "missing_dynamics"
  | "stale_evidence"
  | "weak_external_coverage"
  | "unexpanded_critical"
  | "missing_epistemic_framework"
  | "causal_level_mismatch"
  /** A leverage/risk/bottleneck shipped without an entity_name or with
   *  an empty summary. Forces the rail to fall back to placeholder
   *  strings ("Bottleneck") or to render the same text in both the
   *  title and the body. Always blocks ship. */
  | "missing_insight_name"
  | "empty_insight_summary"
  /** Summary is generic enough that it would apply to any random
   *  business / research problem — the synthesis prompt explicitly
   *  forbids this. Detected via banned-phrase + n-gram-overlap heuristic. */
  | "parroting_summary";

export interface SynthesisQualityScore {
  overall: number; // 0-100
  dimensions: {
    depth: number;
    specificity: number;
    utility_grounding: number;
    evidence_quality: number;
    actionability: number;
    external_coverage: number;
  };
  flags: QualityFlag[];
}

/**
 * Independent post-strategy judgment from a separate LLM call. Rates
 * the generated strategy against the synthesis it was built from on
 * four narrow dimensions, returns red flags + an overall verdict.
 *
 * NOT the same as `recommendation.provenance` — that's self-reported
 * by the strategy LLM. This is an outside opinion.
 */
export interface StrategyEffectivenessCheck {
  /** Did the strategy explicitly address the master bottleneck? */
  bottleneck_addressed: boolean;
  /** 1-sentence reasoning. */
  bottleneck_reasoning: string;

  /** Are critical-load-bearing axioms grounded in the strategy's logic? */
  critical_axioms_grounded: boolean;
  axioms_reasoning: string;

  /** Did the strategy engage with strong insight convergences? */
  convergences_used: boolean;
  convergences_reasoning: string;

  /** 0-100 — how well does the strategy serve the active goal. */
  goal_alignment_score: number;
  goal_reasoning: string;

  /** Concrete concerns the judge surfaced (e.g. "ignores risk-point
   *  R4 which has blast_radius 5", "no action targets the leverage
   *  point C7 that synthesis identified"). Empty = no red flags. */
  red_flags: string[];

  /** Overall verdict — closer to "should the user trust this" than
   *  to a precise numeric score. */
  overall_quality: "strong" | "acceptable" | "shallow" | "broken";

  /** 2-3 sentence holistic assessment of the strategy. */
  reasoning: string;

  /** When the check ran (ISO timestamp). */
  checked_at: string;
}

export interface SynthesisData {
  // Core findings
  master_bottleneck: RichBottleneck | null;
  leverage_points: RichLeveragePoint[];
  risk_points: RichRiskPoint[];

  // Dynamics
  feedback_loops?: RichFeedbackLoop[];

  // Projections
  scenarios?: RichScenario[];

  // Discoveries
  discovered_connections?: RichDiscoveredConnection[];
  contradictions?: RichContradiction[];
  open_questions?: RichOpenQuestion[];

  // Action
  action_plan?: RichActionPlan;
  sequencing_rationale?: string;

  // External knowledge
  worth_considering?: WorthConsidering[];
  cross_context_insights?: CrossContextInsight[];

  // Novelty mechanisms (contrarian inversions + hidden-signal linking)
  assumption_inversions?: AssumptionInversion[];
  signal_to_action?: SignalToAction[];

  // Tier 7: load-bearing axioms extracted from decomposition
  axioms?: Axiom[];

  // Tier 3 cross-reference: compounding/exponential edges that don't belong to any
  // traced cycle — likely missed feedback loops worth investigating.
  candidate_cycles?: Array<{
    edge: { source: string; target: string; dynamics: string };
    reason: string;
  }>;

  // Mini-axioms emitted during /expand — 1-3 per expanded entity, grouped here
  // for cross-entity visibility. Each references its parent_entity_id.
  expansion_axioms?: Array<{
    claim: string;
    visibility: "EXPLICIT" | "IMPLICIT" | "HIDDEN";
    load_bearing: "critical" | "important" | "moderate";
    rests_on_components: string[];
    if_false: string;
    validation_path: string;
    parent_entity_id: string;
  }>;

  // Post-synthesis cross-mechanism clustering (insights from different mechanisms pointing at the same concern).
  // Named `insight_convergences` to disambiguate from `interaction_metadata.convergences` (graph-category level).
  insight_convergences?: InsightConvergence[];

  // Strategy coverage audit: post-synthesis gap check — do actions address every critical axiom / hidden axiom / critical risk / high-impact signal?
  strategy_coverage?: StrategyCoverageAudit;

  // Post-generation strategy coherence validation. Stamped by /api/pipeline/synthesize
  // when validateStrategyCoherence runs against the finalized recommendation.
  // 0-100 score plus the rule-based issues that contributed to the deduction —
  // surfaced in the dashboard meter + drawer so users can audit the rigor.
  coherence_score?: number;
  coherence_issues?: import("../lib/pipeline/validate-strategy-coherence").CoherenceIssue[];

  // Pipeline audit trail — append-only log of what ran, was cached, was skipped
  analysis_runs?: import("./analysis-runs").AnalysisRun[];

  // Decomposition fingerprint at last synthesis — used to short-circuit re-synth when graph hasn't changed
  decomp_fingerprint?: string;

  // Research cache keyed by (depth + space fingerprint) — avoids redundant web-research on iteration
  research_cache?: import("../lib/pipeline/cache").ResearchCache;

  // Goal-aware (populated when an improvement goal exists)
  goal_trajectory_estimate?: GoalTrajectoryEstimate;

  // Auto-detected objectives (populated after synthesis when no active goal)
  suggested_objectives?: import("./goals").SuggestedObjective[];

  /**
   * Phase B: per-goal research log. Keyed by improvement_goals.id. Updated by
   * `execute-goal-research` Inngest handler whenever a bound researcher runs.
   * Used by the Coordinator's recency suppression term and by the UI to show
   * "last researched N minutes ago" per goal.
   */
  goal_research_history?: Record<string, {
    last_research_at: string;   // ISO
    last_run_id: string | null; // agent_runs.id
    total_runs: number;
    cumulative_findings: number;
    last_priority_score?: number | null;
    last_reason?: string | null;
  }>;

  // Phase 8: Epistemic routing layer classification
  epistemic_classification?: import("./epistemic").EpistemicClassification;
  preliminary_objectives?: import("./epistemic").PreliminaryObjective[];

  // Change detection (populated after re-synthesis, comparing old vs new)
  last_change?: import("./twin").ChangeDetection;

  // Phase 6: Research provenance for UI display
  research_provenance?: ResearchProvenance;

  // Phase 7B: Strategic recommendation (macro strategy + micro tactics)
  // Tier 2 of strategy rework: this field becomes a backward-compat alias
  // to strategy_batch.strategies[0] (the primary). New code should prefer
  // strategy_batch directly so it can iterate the full multi-objective
  // fan-out. Older readers (UI view models, validators) keep working
  // against this field unchanged.
  strategic_recommendation?: import("./strategy").StrategicRecommendationData;

  /**
   * Tier 2: multi-objective strategy fan-out. One StrategyBatchEntry per
   * active objective (top-level goal + children, capped at
   * MAX_OBJECTIVES_PER_BATCH). Absent on legacy spaces — readers should
   * fall back to `strategic_recommendation` in that case.
   */
  strategy_batch?: import("./strategy-batch").StrategyBatch;

  // Stale synthesis detection (populated by critique cascade check)
  stale_report?: import("../lib/twin/cascade-propagation").StaleReport;
  is_stale?: boolean;
  /** Phase 4b: human-readable reason for why the strategy is stale (e.g. "User answered a critical question"). */
  strategy_stale_reason?: string;

  /**
   * Phase 4c-final: per-construct posterior beliefs that UPF's selector
   * uses to attenuate expected info-bits. Updated inline whenever the user
   * makes an observation (answers a question, records a metric, …). Keyed
   * by ProxyDescriptor.construct_id. Zero-migration: lives in the same
   * JSONB column as the rest of synthesis.
   */
  construct_posteriors?: Record<string, import("../lib/upf/posterior").ConstructPosterior>;

  // Post-synthesis validation scores
  quality_score?: SynthesisQualityScore;
  goal_fitness?: GoalFitnessResult;

  // ── Post-strategy effectiveness check (LLM-as-judge) ──
  //
  // Runs AFTER strategy generation completes. Takes the synthesis +
  // the generated strategy and asks an LLM judge: did the strategy
  // actually do what synthesis identified as necessary? Specifically:
  // does it address the master bottleneck, ground in critical axioms,
  // engage with strong convergences, align with the active goal?
  //
  // The strategy generator's `provenance` already tracks backlinks
  // (axioms_respected, convergences_addressed, etc.) but those are
  // self-reported by the same LLM that wrote the strategy. This
  // check is an independent judgment from a separate LLM call with
  // a narrow rubric — closer to "automatic editor" than "self-rating."
  //
  // Optional; absent for runs before this field shipped or when the
  // judge call failed (soft-fail design — strategy still ships).
  strategy_effectiveness_check?: StrategyEffectivenessCheck;

  // Gap-driven regeneration metadata (tracks if synthesis was re-run to fix quality issues)
  regen_metadata?: {
    attempted: boolean;
    original_score: number;
    regen_score: number | null;
    flags_addressed: string[];
    kept: "original" | "regen";
    regen_at: string;
  };

  // Multi-perspective analysis: quick vs deep delta
  quick_synthesis_snapshot?: import("./execution-brief").QuickSynthesisSnapshot;
  perspective_delta?: import("./execution-brief").PerspectiveDelta;

  // Phase B (typed clarifier answers, 2026-05). User commitments
  // captured at intake via the pre-flight clarifier, grouped by the
  // typed slot the question was generated to fill. The same answers
  // ALSO live in open_questions[] with user_answer set — that path
  // feeds the Phase 4b banner + synthesize dedup. This typed map is
  // for new readers (canvas seed shapes, expand context_hint, twin
  // boundary frames) that need to ask "what did the user say about
  // X?" without text-matching prose. Soft-typed via Partial so
  // legacy spaces without the field continue to load. See
  // src/types/clarifier-answer.ts for slot semantics per mode.
  user_assertions?: Partial<
    Record<
      import("./clarifier-answer").AnswerSlot,
      Array<{
        value: string;
        question: string;
        answered_at: string;
      }>
    >
  >;

  // Signal intelligence (trajectory-influencing signal detection)
  signal_extraction?: import("../lib/intelligence/signal-extraction").SignalExtractionResult;
  research_triggers?: import("../lib/intelligence/research-triggers").ResearchTriggerResult;

  // Research intelligence (from domain-expert / research pipeline)
  hidden_signals?: HiddenSignalData[];
  continuation_signals?: ContinuationSignalData[];

  // Lazy-loaded execution briefs (keyed by recommendation ID)
  execution_briefs?: Record<string, import("./execution-brief").ExecutionBrief>;

  // Convergence workspace: pre-ranked findings list
  findings?: import("./finding").Finding[];

  // Subsystems — typed compositional units extracted post-synthesis. Each
  // subsystem groups entities + edges + cycles + axioms into a recognizable
  // functional unit (loop, leverage_cluster, invariant_chain, etc.) that
  // strategy generation operates on as a typed atom rather than free text.
  subsystems?: import("./subsystems").Subsystem[];

  // Causal Chains (L4 invariant → goal contribution trajectories)
  causal_chains?: import("./causal-chains").CausalChain[];
  // Calculation traces keyed by chain id
  calculation_traces?: Record<string, import("./causal-chains").CalculationTrace>;
  // Baseline questions (when Effect Propagator needs user input), keyed by chain id
  baseline_questions?: Record<string, import("./causal-chains").BaselineQuestion[]>;

  // Per-agent user overrides (keyed by agent ID)
  agent_overrides?: Record<string, import("./intelligence").AgentOverrides>;
}

// ── Research intelligence types surfaced from synthesis_data JSONB ──

export interface HiddenSignalData {
  signal_name: string;
  signal_type:
    | "mediating_variable"
    | "analogous_dynamic"
    | "structural_risk"
    | "missing_metric";
  description: string;
  trajectory_impact: number;
  related_internal_entities?: string[];
  detection_method: string;
  analogous_precedent?: string | null;
  discovered_at?: string;
}

export interface ContinuationSignalData {
  type: "critical_bridge_found" | "contradiction_detected" | "high_impact_gap" | "validation_needed";
  description: string;
  follow_up_queries?: string[];
  priority: "critical" | "high" | "medium";
}
