// Rich synthesis data stored in spaces.synthesis_data JSONB column
// Generated by Pass 2 structuring prompt

export interface WhenMatters {
  situation: string;
  impact: string;
  intensity: "high" | "mid" | "low";
}

export interface ActionAlternative {
  when: string;
  approach: string;
  tradeoff: string;
}

export interface RichLeveragePoint {
  entity_id: string;
  summary: string;
  reasoning: string[];
  how_it_works: string[];
  when_matters: WhenMatters[];
  action: {
    primary: string;
    alternatives: ActionAlternative[];
  };
  connections: string[];
}

export interface RichRiskPoint {
  entity_id: string;
  blast_radius: number;
  summary: string;
  reasoning: string[];
  how_it_fails: string[];
  when_matters: WhenMatters[];
  mitigation: {
    primary: string;
    alternatives: ActionAlternative[];
  };
  connections: string[];
}

export interface RichBottleneck {
  entity_id: string;
  blast_radius: number;
  summary: string;
  reasoning: string[];
  when_matters: WhenMatters[];
}

export interface SynthesisData {
  leverage_points: RichLeveragePoint[];
  risk_points: RichRiskPoint[];
  master_bottleneck: RichBottleneck | null;
}
