// Rich synthesis data stored in spaces.synthesis_data JSONB column
// Generated by Pass 3 synthesis agent

export interface WhenMatters {
  situation: string;
  impact: string;
  intensity: "high" | "mid" | "low";
}

export interface ActionAlternative {
  when: string;
  approach: string;
  tradeoff: string;
}

export interface RichLeveragePoint {
  entity_id: string;
  entity_name?: string;
  summary: string;
  reasoning: string[];
  how_it_works: string[];
  when_matters: WhenMatters[];
  action: {
    primary: string;
    alternatives: ActionAlternative[];
  };
  connections: string[];
}

export interface RichRiskPoint {
  entity_id: string;
  entity_name?: string;
  blast_radius: number;
  summary: string;
  reasoning: string[];
  how_it_fails: string[];
  when_matters: WhenMatters[];
  mitigation: {
    primary: string;
    alternatives: ActionAlternative[];
  };
  connections: string[];
}

export interface RichBottleneck {
  entity_id: string;
  blast_radius: number;
  summary: string;
  reasoning: string[];
  when_matters: WhenMatters[];
}

export interface RichFeedbackLoop {
  name: string;
  type: "positive" | "negative";
  steps: string[];
  intervention_at: number;
  explanation: string;
  how_to: string;
  when_active: WhenMatters[];
}

export interface RichScenario {
  name: string;
  conditions: string;
  outcome_label: string;
  outcome_value: string;
  probability: "likely" | "possible" | "unlikely";
}

export interface RichDiscoveredConnection {
  source_entity_id: string;
  target_entity_id: string;
  strength: "strong" | "moderate" | "speculative";
  reasoning: string;
}

export interface RichContradiction {
  assumption_text: string;
  conclusion_text: string;
  severity: "critical" | "moderate" | "minor";
  description: string;
}

export interface RichOpenQuestion {
  question: string;
  why_it_matters: string;
  what_changes?: string;
  related_entity_ids?: string[];
}

export interface ActionTag {
  t: string;
  c: string;
}

export interface ActionItemRich {
  text: string;
  why: string;
  tags: ActionTag[];
  dynamic_role?: "clears_threshold" | "starts_loop" | "accelerates_loop" | "linear_improvement" | "can_defer";
  cost_of_delay?: string;
}

export interface ActionTimeframe {
  label: string;
  badge: string;
  actions: ActionItemRich[];
}

export interface ActionPath {
  label: string;
  description: string;
  icon: string;
  color: string;
  timeframes: ActionTimeframe[];
}

export interface RichActionPlan {
  paths: ActionPath[];
}

export interface WorthConsidering {
  type: "analogy" | "framework" | "blind_spot" | "resource" | "precedent";
  title: string;
  description: string;
  confidence: "high" | "moderate" | "speculative";
  connected_entities: string[];
  source_note: string;
}

export interface SynthesisData {
  // Core findings
  master_bottleneck: RichBottleneck | null;
  leverage_points: RichLeveragePoint[];
  risk_points: RichRiskPoint[];

  // Dynamics
  feedback_loops?: RichFeedbackLoop[];

  // Projections
  scenarios?: RichScenario[];

  // Discoveries
  discovered_connections?: RichDiscoveredConnection[];
  contradictions?: RichContradiction[];
  open_questions?: RichOpenQuestion[];

  // Action
  action_plan?: RichActionPlan;

  // External knowledge
  worth_considering?: WorthConsidering[];
}
