// ── Objective Canvas — middle-out 4-stage room generator (v2) ──
//
// Generates the contents of one sub-objective's room with a real
// causal chain per item:
//
//   PAIN POINT     root_causes[] →  pain title (effect)  →  negative_outcome
//   FEATURE        first_principles[] →  feature title  →  positive_outcome
//   OUTCOME        title + measured_by (a concrete signal)
//   OBJECTIVE      a single anchor (the sub-objective title)
//
// Middle-out order: pain points first (they anchor the bottom);
// outcomes next (anchored by pains + the objective); features last
// (anchored by both ends). After entities exist a separate pass
// produces ranked cross-layer correlation edges.
//
// We also surface a room-level `top_negative_outcome`: the single
// most-impactful downstream consequence across all pain points,
// used as the room's header anchor ("Counters: …").

import { llmJSON } from "@/lib/llm";
import type { ObjectiveAnnotation } from "./generate-annotations";

interface LayerRow {
  id: string;
  slug: string;
  label: string;
}

/** A single annotation seed surfaced on a generated item. The LLM
 *  picks 0-3 of these per item via 1-based indices into the
 *  numbered ANNOTATION LENS block. The route persists the resolved
 *  records (not just indices) so the UI can render chips without
 *  re-loading annotations. */
export interface AnnotationProvenance {
  /** 1-based index into the lens list — kept so the UI can also
   *  cross-reference to the parent objective's annotation strip. */
  index: number;
  /** Verbatim phrase from the objective the annotation anchored on. */
  phrase: string;
  /** Which structural facet drove the seed — used by the chip to
   *  color/icon the provenance ("fragility → friction", "analogy →
   *  mechanism", "dimension → outcome"). */
  facet: "fragility" | "analogy" | "tension" | "dimension" | "inference" | "reading";
  /** Phase 2 — canonical concept identity for the source annotation
   *  (slugify(concept ?? phrase)). The route resolves this from the
   *  lens at persist time so cross-room analyses can group items by
   *  hard-keyed concept identity instead of text-matching `phrase`.
   *  Optional for back-compat with pre-Phase-2 persisted items. */
  concept_slug?: string;
  /** Phase 2 — canonical concept noun phrase (when the LLM emitted one).
   *  Renders next to the chip when present; the slug is the join key. */
  concept?: string | null;
}

export interface RoomCategoryEnum {
  /** slug → label. The LLM must pick one slug per item from this map. */
  friction: Record<string, string>;
  mechanism: Record<string, string>;
  result: Record<string, string>;
}

export interface RoomContext {
  spaceId: string;
  userId: string;
  subObjectiveId: string;
  subObjectiveTitle: string;
  subObjectiveDescription: string | null;
  coreObjectiveText: string;
  clarifyingAnswers: Array<{ question: string; answer: string }>;
  layersBySlug: Map<"pain" | "features" | "outcomes" | "objective", LayerRow>;
  /** Tier 3 — adaptive sub-categories generated by the pre-room
   *  step. When empty, items are emitted with sub_category=null
   *  (legacy behavior). When populated, each item MUST be tagged
   *  with one slug from its lane's enum. */
  categories?: RoomCategoryEnum;
  /** Commit-2 research integration — pre-built RESEARCH CONTEXT
   *  block from research-service.buildRagBlock(). When present
   *  (and non-empty), prepended to every stage's user prompt so
   *  the LLM grounds items in real sources and emits citations[]
   *  per item. When absent / empty, generation falls back to
   *  pure first-principles reasoning with no citations. */
  ragBlock?: string;
  /** Annotation Lens integration — the parent objective's
   *  annotations (extracted by generateObjectiveAnnotations) become
   *  the semantic substrate every lane is generated against.
   *  fragility → friction seeds, analogy → mechanism seeds,
   *  dimension → outcome seeds. When present, the LLM is asked to
   *  emit derived_from_annotations[] per item; the route persists
   *  the resolved provenance into causal_chain so the room UI can
   *  surface chips on each card. Empty / undefined → fallback to
   *  legacy pure-research generation. */
  annotations?: ObjectiveAnnotation[];
  /** Wire 1 (K2) — operational constraints. When provided, every
   *  stage prompt sees the user's time / budget / team / risk /
   *  compliance situation and emits items that respect it. Without
   *  this the room ideates as if every user is a funded enterprise.
   *  Optional + back-compat — missing means generation respects the
   *  user's situation only through other (less direct) signals. */
  constraintsBlock?: string;
  /** Wire 4 (K2) — cached cross-room signals to RESPECT during new
   *  room generation. Recurring mechanisms / themes / orphan
   *  annotations across sibling rooms in this space. Prevents the
   *  4th room from re-proposing what the system has already flagged
   *  as recurring across the other 3. Empty / undefined when no
   *  prior analysis exists (first room generated in a space). */
  crossRoomFindingsBlock?: string;
  /** Wire 2 (K4) — RecentLearnings rendered into a prompt block by
   *  buildLearningsBlock(). Closes the amnesia loop: a user who
   *  concluded "streak gamification didn't move retention" sees
   *  future generations RESPECT that learning instead of re-
   *  proposing the same losing mechanism. Empty / undefined when
   *  no concluded or abandoned experiments exist yet. */
  learningsBlock?: string;
  /** Cross-room data awareness (built by buildSiblingDataBlock). Surfaces
   *  sibling sub-objectives (the other capabilities in this app) + the
   *  data tokens already produced/consumed across sibling rooms, so this
   *  room COORDINATES with siblings and REUSES shared data tokens instead
   *  of generating as an isolated silo — the prerequisite for a real
   *  cross-room data-flow graph. Empty / undefined for the first room. */
  siblingDataBlock?: string;
}

// ── Output shapes ──────────────────────────────────────────────────

export interface PainItem {
  name: string;
  /** What this pain leads to downstream — a single concrete state. */
  negative_outcome: string;
  /** 2-4 short noun phrases (≤6 words each) — the underlying causes. */
  root_causes: string[];
  /** 0-5 LLM self-assessment of how central this pain is. Higher =
   *  this pain influences / contributes to more other pains. The
   *  highest-ranked pain in the room renders with the Root ⭐ badge. */
  influence_rank: number;
  /** Tier 3 — sub-category slug picked from RoomCategories.friction.
   *  null when categories weren't provided for this room. */
  sub_category?: string | null;
  /** Commit-2 research integration — 1-based indices into the
   *  RESEARCH CONTEXT source list that informed this item. Empty
   *  when the item is pure first-principles or research is
   *  unavailable. */
  citations?: number[];
  /** Annotation Lens — resolved provenance entries the LLM tagged
   *  this item with (index/phrase/facet). Empty when no annotations
   *  applied. */
  derived_from_annotations?: AnnotationProvenance[];
}

export interface FeatureItem {
  name: string;
  /** What this feature produces when it lands — single concrete state. */
  positive_outcome: string;
  /** 2-4 short noun phrases (≤6 words each) — why this works. */
  first_principles: string[];
  /** Arc 3.2 (two-phase grounding) — DECLARED causal bindings. Each
   *  feature names WHICH pain root-cause it counters (addresses[]) and
   *  WHICH outcome indicator it moves (moves[]). room/generate turns
   *  these into Pain→Feature + Feature→Outcome edges DIRECTLY (declared-
   *  primary), so the chain reflects the mechanism's stated causal
   *  intent rather than being re-inferred post-hoc by the correlation
   *  pass. Optional — soft-fail / legacy paths omit them. */
  addresses?: Array<{ pain: string; root_cause: string }>;
  moves?: Array<{
    outcome: string;
    indicator: string;
    direction: "increase" | "decrease";
  }>;
  /** Tier 3 — sub-category slug picked from RoomCategories.mechanism. */
  sub_category?: string | null;
  /** Commit-2 — 1-based source indices informing this feature. */
  citations?: number[];
  /** Annotation Lens — resolved provenance entries. */
  derived_from_annotations?: AnnotationProvenance[];
  /** Foundation B — feature-level data I/O. The data units this feature
   *  CONSUMES (reads as input) and PRODUCES (emits as output), as
   *  snake_case tokens, declared at generation against the shared
   *  data-unit registry + sibling tokens. Makes a feature the OPERATOR on
   *  the cross-room data-flow graph (token = data node, feature =
   *  transform). Coarser than mechanism_spec.runtime_flow (step-level);
   *  the deep spec refines them later. Optional / legacy-safe. */
  consumes?: string[];
  produces?: string[];
}

export interface OutcomeItem {
  name: string;
  /** A concrete proxy / signal that says "yes this happened".
   *  Single-line legacy field kept for backward compat — items
   *  generated before Phase 8 only carry this. New items carry
   *  the richer indicators[] (below) AND measured_by (synthesizes
   *  the indicators into one sentence). */
  measured_by: string;
  /** Phase 8 — 2-4 concrete indicators / criteria that prove the
   *  outcome happened. Mirrors PainItem.root_causes structure
   *  (3-5 root causes) so the Category Card's PROBLEM | OUTCOME
   *  juxtaposition reads symmetrically. Each entry is a short
   *  noun phrase (≤8 words) describing one observable signal.
   *
   *  Backward-compat: when missing, callers fall through to
   *  [measured_by]. */
  indicators: string[];
  /** Arc 3.2 (two-phase grounding) — per-indicator measurement
   *  scaffold so RESULTS are measurable at generation, not just named.
   *  Each entry carries the LLM's suggested unit + measurement_method
   *  + direction (which way is GOOD). room/generate seeds these into
   *  causal_chain.indicator_baselines (source:"llm"), leaving the
   *  actual baseline_value/target_value for the user's BaselineEditor.
   *  Optional — soft-fail / legacy paths omit it. */
  indicator_specs?: Array<{
    indicator: string;
    unit?: string;
    measurement_method?: string;
    direction?: "increase" | "decrease";
  }>;
  /** Tier 3 — sub-category slug picked from RoomCategories.result. */
  sub_category?: string | null;
  /** Commit-2 — 1-based source indices informing this outcome. */
  citations?: number[];
  /** Annotation Lens — resolved provenance entries. */
  derived_from_annotations?: AnnotationProvenance[];
}

// ── Shared scaffolding ─────────────────────────────────────────────

const ANTI_PLATITUDE = `ANTI-PLATITUDE: every item references something specific from the sub-objective or clarifying answers. Items that could appear unchanged on a different sub-objective MUST be rewritten.`;

/** Shared citation rule injected into every stage prompt when RAG
 *  context is present. The 1-based indices match the source list
 *  rendered in buildRagBlock(). Strict: don't invent ids. */
const CITATION_RULE = `CITATIONS: For each item, include a citations[] array of 1-based source indices from the RESEARCH CONTEXT block above when the item is informed by those sources. Use ONLY indices that exist in the source list — never invent. Empty array [] when the item is pure first-principles. Cite 0-3 sources per item; quality over quantity.`;

/** Render the RAG block + citation rule for prompt prepend. When
 *  no rag block is provided, returns empty strings so callers can
 *  template uniformly without conditional logic. */
function ragSection(ctx: RoomContext): {
  ragBlock: string;
  citationRule: string;
} {
  if (!ctx.ragBlock || ctx.ragBlock.length === 0) {
    return { ragBlock: "", citationRule: "" };
  }
  return {
    ragBlock: `\n\n${ctx.ragBlock}\n`,
    citationRule: `\n\n${CITATION_RULE}\n`,
  };
}

/** Shared annotation-provenance rule injected into every stage prompt
 *  when the ANNOTATION LENS block is present. The LLM must tie each
 *  generated item back to ≥1 annotation when one applies — and may
 *  emit [] when nothing in the lens covers the item. Indices are
 *  1-based into the lens list; the `facet` field tells the UI which
 *  structural slot of the annotation drove the seed. */
const ANNOTATION_PROVENANCE_RULE = `ANNOTATION PROVENANCE: For each item, include a derived_from_annotations[] array. Each entry: { index: 1-based index into the ANNOTATION LENS above, facet: which structural slot of that annotation drove this item — one of "fragility" | "analogy" | "tension" | "dimension" | "inference" | "reading" }. Prefer mappings: fragility → friction (pain) items; analogy / mechanism → feature items; dimension / inference → outcome items; tension can seed any lane. Cite 0-3 annotations per item — quality over quantity. NEVER invent indices outside the lens. Empty array [] is acceptable when no annotation directly seeds this item.

CONCEPT IDENTITY (Phase 2): When an annotation in the lens above shows a "concept:" line, that concept is the CANONICAL name for the underlying idea across the entire workspace. If an item you generate embodies that same idea, MIRROR the canonical concept name in your item's name (or use it verbatim as a sub-string) — do NOT invent a new paraphrase. Example: lens entry says concept: "Vivid experience" → if you generate a feature about sensory-rich engagement, call it "Vivid experience layer" not "Immersive sensory engagement". This lets cross-room synthesis identify shared concepts and the glossary trace-back resolve to a single definition.`;

/** Render the ANNOTATION LENS block + provenance rule for prompt
 *  prepend. Compact, max ~8 annotations, weight-sorted desc so the
 *  most load-bearing readings come first. When no annotations are
 *  available, returns empty strings (generation falls back to
 *  research + clarifying-only). */
function annotationLensSection(ctx: RoomContext): {
  lensBlock: string;
  provenanceRule: string;
  hasAnnotations: boolean;
} {
  const anns = ctx.annotations ?? [];
  if (anns.length === 0) {
    return { lensBlock: "", provenanceRule: "", hasAnnotations: false };
  }
  // Sort by weight desc + cap at 8 — keeps token cost bounded while
  // preserving the structural diversity the cleaner already enforces.
  const ranked = [...anns]
    .sort((a, b) => (b.weight ?? 0.5) - (a.weight ?? 0.5))
    .slice(0, 8);

  const lines: string[] = ["ANNOTATION LENS (the parent-objective semantic substrate this room must reason against):"];
  ranked.forEach((a, i) => {
    const idx = i + 1;
    const lane = a.layer_tag ? ` lane:${a.layer_tag}` : "";
    const w = typeof a.weight === "number" ? a.weight.toFixed(2) : "—";
    lines.push(`  [${idx}] "${a.phrase}" (weight ${w}${lane})`);
    // Phase 2 — surface the canonical concept identity. When an item
    // generated downstream embodies the same idea, use this concept
    // name (NOT a fresh paraphrase) so cross-room analyses can
    // identify shared concepts by text + the glossary popover resolves
    // the trace-back. The slug is the deterministic join key; the
    // concept string is what the LLM should mirror in its item names.
    if (a.concept) {
      lines.push(`        concept: "${a.concept}" [slug:${a.concept_slug}]`);
    }
    if (a.reading) {
      lines.push(`        reading: ${a.reading}`);
    }
    if (a.fragility?.when) {
      const sign = a.fragility.sign ? ` · early sign: ${a.fragility.sign}` : "";
      lines.push(`        fragility: when ${a.fragility.when}${sign}`);
    }
    const topAnalogy = a.analogies?.[0];
    if (topAnalogy?.why_same) {
      const ref = topAnalogy.referent ? `like ${topAnalogy.referent} ` : "";
      const dom = topAnalogy.domain ? `(${topAnalogy.domain}) ` : "";
      lines.push(`        analogy: ${ref}${dom}— ${topAnalogy.why_same}`);
    }
    if (a.dimensions?.length) {
      const dims = a.dimensions
        .slice(0, 3)
        .map((d) => d.name)
        .filter(Boolean)
        .join(" · ");
      if (dims) lines.push(`        dimensions: ${dims}`);
    }
    if (a.tensions?.length) {
      const t = a.tensions[0];
      lines.push(`        ${t.kind} with "${t.phrase}": ${t.note}`);
    }
  });

  return {
    lensBlock: `\n\n${lines.join("\n")}\n`,
    provenanceRule: `\n\n${ANNOTATION_PROVENANCE_RULE}\n`,
    hasAnnotations: true,
  };
}

const TITLE_RULES = `TITLE: noun phrase, ≤6 words. Do NOT start with action verbs (develop/implement/create/design/build/enhance/establish). Title-case OK; no terminal punctuation.`;

function clarifyingBlock(
  answers: RoomContext["clarifyingAnswers"],
): string {
  if (answers.length === 0) return "";
  return `\n\nCLARIFYING ANSWERS:\n${answers
    .map((a, i) => `  ${i + 1}. ${a.question} → ${a.answer}`)
    .join("\n")}`;
}

// ── Stage A: Pain points (with causal chain) ───────────────────────

interface PainShape {
  items?: Array<{
    name?: unknown;
    negative_outcome?: unknown;
    root_causes?: unknown;
    influence_rank?: unknown;
    sub_category?: unknown;
    citations?: unknown;
    derived_from_annotations?: unknown;
  }>;
  top_negative_outcome?: unknown;
  lane_labels?: {
    pain?: unknown;
    features?: unknown;
    outcomes?: unknown;
    objective?: unknown;
  };
}

/** Builds the categories block injected into stage prompts. Returns
 *  empty string when no categories are configured for this room. */
function categoryBlock(
  ctx: RoomContext,
  lane: keyof RoomCategoryEnum,
): { instructions: string; slugs: string[] } {
  const cats = ctx.categories?.[lane];
  if (!cats) return { instructions: "", slugs: [] };
  const entries = Object.entries(cats);
  if (entries.length === 0) return { instructions: "", slugs: [] };
  const list = entries
    .map(([slug, label]) => `    "${slug}" → ${label}`)
    .join("\n");
  const slugs = entries.map(([slug]) => slug);
  return {
    slugs,
    instructions: `\n\nSUB-CATEGORIES (every item in this lane MUST be tagged with one of these slugs — pick the best fit; never invent new slugs):\n${list}\n`,
  };
}

/** Adaptive lane labels — the four bucket nouns chosen by the LLM
 *  to match the sub-objective's domain. Empty strings collapse to
 *  the canonical fallbacks in the room view. */
export interface LaneLabels {
  pain: string;
  features: string;
  outcomes: string;
  objective: string;
}

interface PainPassResult {
  items: PainItem[];
  /** Single line synthesizing the worst downstream consequence
   *  across all pains — the room header anchor. */
  top_negative_outcome: string;
  /** Domain-specific 4 lane labels (≤2 words each). */
  lane_labels: LaneLabels;
}

async function generatePainPoints(
  ctx: RoomContext,
): Promise<PainPassResult> {
  const system = `You map the load-bearing pain points a sub-objective must address — with their causal chain made explicit.

A pain point is an observable EFFECT in the user's world. Every pain has TWO ENDS we want named:
  • root_causes — the underlying reasons it exists. 2-4 short noun phrases (≤6 words each). Concrete and orthogonal. These are what a SOLUTION would attack.
  • negative_outcome — what this pain leads to downstream if not addressed. Single line, one concrete state.

Also include an INFLUENCE_RANK (0-5): how much does this pain feed / amplify other pains? A pain that causes 3 other pains scores high; an isolated pain scores low.

ROOM SYNTHESIS:
After listing the pains, produce a single TOP_NEGATIVE_OUTCOME: the worst downstream consequence the room exists to counter, synthesizing across all pains. One short line — used as the room's header anchor.

LANE LABELS (adaptive):
Also pick four short noun labels that match the user's DOMAIN — these rename the four lanes of the room so they speak the user's language. Each label is ≤2 words, title-case, no terminal punctuation:
  • lane_labels.pain      → the bucket name for "problems / frictions / symptoms" in this domain
  • lane_labels.features  → the bucket name for "solutions / mechanisms / levers / bets" in this domain
  • lane_labels.outcomes  → the bucket name for "results / states / wins" in this domain
  • lane_labels.objective → name the umbrella anchor for this domain (often "Objective" or "Goal")

Examples by domain:
  App / product:        { pain: "Frictions",  features: "Features",    outcomes: "Outcomes",         objective: "Objective" }
  Curriculum / course:  { pain: "Gaps",       features: "Lessons",     outcomes: "Skills",           objective: "Mastery"   }
  Clinical / therapy:   { pain: "Symptoms",   features: "Mechanisms",  outcomes: "Functional gains", objective: "Recovery"  }
  Strategy / business:  { pain: "Frictions",  features: "Bets",        outcomes: "Wins",             objective: "Goal"      }
  Research:             { pain: "Open Qs",    features: "Investigations", outcomes: "Findings",      objective: "Thesis"    }
  Workout / health:     { pain: "Limits",     features: "Movements",   outcomes: "Capacities",       objective: "Goal"      }
  Operations:           { pain: "Frictions",  features: "Levers",      outcomes: "Throughput",       objective: "Target"    }

Pick labels FROM the user's actual domain. Never invent jargon. Stay specific.

PAIN RULES:
- 3-5 pains, ordered by influence_rank descending.
- ${TITLE_RULES}
- Pain titles name the EFFECT ("Low engagement depth"), not the cause ("Generic results") and not the outcome ("Superficial browsing"). Those go in the root_causes and negative_outcome fields respectively.

SUB-OBJECTIVE SCOPE TEST (mandatory — apply to EVERY pain before emitting it):
Each pain must be a SPECIFIC manifestation WITHIN this sub-objective's strategic facet — not a generic pain that could appear in any sub-objective.

Self-test: "If I removed this sub-objective's title and framing, would this pain make sense as a pain in a completely DIFFERENT sub-objective?"
  • YES it's generic → REJECT. You're describing a parent-objective-level pain, not a sub-objective-scoped one. Tighten the framing until the pain only makes sense inside THIS sub-objective.
  • NO it only manifests inside this sub-objective's scope → KEEP.

❌ EXAMPLE — too generic (parent sub-objective = "Goal-Driven Search Optimization"):
   "Information overload"        — applies to every search sub-objective
   "Poor user engagement"        — applies to every product sub-objective
   "Slow performance"            — applies to anything with software
✅ EXAMPLE — scoped (parent sub-objective = "Goal-Driven Search Optimization"):
   "Search results misaligned with stated goals"    — specific to goal-matching
   "Users abandon search after first non-goal result" — observable inside this scope
   "Goal updates lag behind result re-ranking"      — concrete to the goal-→-search pipeline

NEGATIVE_OUTCOME RULES (critical — read carefully):
- Must be the DOWNSTREAM CONSEQUENCE of the pain, not a paraphrase of the title.
- Self-test: if removing the title's key noun makes the negative_outcome still meaningful and informative, you've done it right. If they read as synonyms, REWRITE.
- BAD (synonyms — REJECT):
    title: "Low Interface Engagement"     → negative_outcome: "Users lose interest quickly"
    title: "Poor Personalization"         → negative_outcome: "Users feel disconnected"
- GOOD (downstream — KEEP):
    title: "Low Interface Engagement"     → negative_outcome: "Product churn within the first session"
    title: "Poor Personalization"         → negative_outcome: "Users never reach an aha moment"
    title: "Slow Onboarding"              → negative_outcome: "Trial users abandon before activating value"
- Single line, ≤14 words, concrete and observable.

SHARED ROOT CAUSES (required, not optional):
- If two pains share an underlying mechanism, you MUST use the IDENTICAL verbatim root_cause string in both items. Don't paraphrase. Don't pluralize. Don't re-case.
- Aim for 1-2 root causes that recur across ≥2 pains. The shared-cause UI pill above the lane EXISTS to surface these — if no root_causes overlap, the user sees no systemic insight.

${ANTI_PLATITUDE}

Return strict JSON.`;

  const painCats = categoryBlock(ctx, "friction");
  const rag = ragSection(ctx);
  const lens = annotationLensSection(ctx);
  const itemProps: Record<string, unknown> = {
    name: { type: "string" },
    negative_outcome: { type: "string" },
    root_causes: { type: "array", items: { type: "string" } },
    influence_rank: { type: "number" },
  };
  const itemRequired: string[] = [
    "name",
    "negative_outcome",
    "root_causes",
    "influence_rank",
  ];
  if (painCats.slugs.length > 0) {
    itemProps.sub_category = { type: "string", enum: painCats.slugs };
    itemRequired.push("sub_category");
  }
  if (rag.ragBlock.length > 0) {
    itemProps.citations = { type: "array", items: { type: "number" } };
    itemRequired.push("citations");
  }
  if (lens.hasAnnotations) {
    itemProps.derived_from_annotations = {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          index: { type: "number" },
          facet: {
            type: "string",
            enum: [
              "fragility",
              "analogy",
              "tension",
              "dimension",
              "inference",
              "reading",
            ],
          },
        },
        required: ["index", "facet"],
      },
    };
    itemRequired.push("derived_from_annotations");
  }

  const user = `PARENT OBJECTIVE:\n"""\n${ctx.coreObjectiveText}\n"""\n\nSUB-OBJECTIVE (room scope):\n"""\n${ctx.subObjectiveTitle}${
    ctx.subObjectiveDescription
      ? `\n\n${ctx.subObjectiveDescription}`
      : ""
  }\n"""${clarifyingBlock(ctx.clarifyingAnswers)}${ctx.constraintsBlock ?? ""}${ctx.crossRoomFindingsBlock ?? ""}${ctx.learningsBlock ?? ""}${painCats.instructions}${lens.lensBlock}${lens.provenanceRule}${rag.ragBlock}${rag.citationRule}

Generate 3-5 pain points with full causal chains, plus the single TOP_NEGATIVE_OUTCOME for the room.${
    painCats.slugs.length > 0
      ? " Each pain must include sub_category — the slug of the friction sub-category it belongs to."
      : ""
  }${
    rag.ragBlock.length > 0
      ? " Each pain must include citations[] — 1-based source indices (use ONLY indices from the RESEARCH CONTEXT list above)."
      : ""
  }${
    lens.hasAnnotations
      ? " Each pain must include derived_from_annotations[] — prefer fragility / tension facets here, since pains are the surface where the objective's pre-mortem and value-conflicts show up first."
      : ""
  }`;

  const raw = await llmJSON<PainShape>({
    system,
    user,
    responseSchema: {
      name: "pain_points_v2",
      schema: {
        type: "object",
        additionalProperties: false,
        properties: {
          top_negative_outcome: { type: "string" },
          lane_labels: {
            type: "object",
            additionalProperties: false,
            properties: {
              pain: { type: "string" },
              features: { type: "string" },
              outcomes: { type: "string" },
              objective: { type: "string" },
            },
            required: ["pain", "features", "outcomes", "objective"],
          },
          items: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: itemProps,
              required: itemRequired,
            },
          },
        },
        required: ["items", "top_negative_outcome", "lane_labels"],
      },
    },
    temperature: 0.5,
    maxTokens: 2400,
  });

  const items = cleanPains(raw?.items, ctx);
  const top =
    typeof raw?.top_negative_outcome === "string"
      ? raw.top_negative_outcome.trim().slice(0, 200)
      : "";
  const lane_labels = cleanLaneLabels(raw?.lane_labels);
  return { items, top_negative_outcome: top, lane_labels };
}

// ── Stage B: Outcomes ──────────────────────────────────────────────

interface OutcomeShape {
  items?: Array<{
    name?: unknown;
    measured_by?: unknown;
    /** Phase 8 — 2-4 observable indicators. */
    indicators?: unknown;
    /** Arc 3.2 — per-indicator measurement scaffold. */
    indicator_specs?: unknown;
    sub_category?: unknown;
    citations?: unknown;
    derived_from_annotations?: unknown;
  }>;
}

async function generateOutcomes(
  ctx: RoomContext,
  painPoints: PainItem[],
): Promise<OutcomeItem[]> {
  const system = `You name the outcomes the sub-objective should produce — anchored on both ends.

An OUTCOME is what's OBSERVABLY TRUE about the USER (or their world) when the sub-objective lands. Outcomes describe a STATE or a BEHAVIOR — never a capability the system has.

CRITICAL — OUTCOME ≠ FEATURE:
- Outcomes describe what HAPPENS to the user. Features describe what the system DOES.
- A feature can produce an outcome, but they are NEVER the same object.
- ❌ NEVER restate a feature name as an outcome. If a feature is "Gamification Layer", the outcome is NOT "Integrated Gamification Features" — the outcome is "Users complete 5+ topic dives per session" or "Self-reported curiosity score 4/5".
- ❌ NEVER name an outcome after a system capability ("Simplified User Interface", "Personalized Dashboard"). Those are features.
- ✅ Outcomes start with the user: "Users return next day at 70%+", "Self-reported flow during sessions", "Time-to-first-aha drops below 90 seconds".
- Self-test: read your outcome aloud. If it sounds like something an engineer would build, it's a feature — rewrite as the user's experienced state.

For each outcome include MEASURED_BY: ONE short proxy/signal that says "yes this happened" (e.g. "8+ min/session", "85% return next day", "self-reported flow 4/5"). One short line — this is the headline signal.

Phase 8 — Each outcome ALSO carries INDICATORS: 2-4 concrete observable criteria that PROVE the outcome happened. Where measured_by is the headline, indicators[] are the load-bearing criteria a reader would check to verify. Mirrors how each pain carries root_causes (the underlying components of the effect).

INDICATOR RULES:
- 2-4 entries, each a short noun phrase (≤8 words).
- Each indicator is OBSERVABLE — something a tracking dashboard or user report could verify. NOT meta ("user is happy"); concrete ("session length crosses 8 minutes 3× per week").
- Orthogonal — don't list the same signal twice in slightly different words.
- Together they SHOULD bracket measured_by: if all indicators hold, measured_by is true.

Example for outcome "Sustained deep-dive sessions":
  measured_by: "8+ min average session length"
  indicators: ["sessions ≥ 8 min", "≥3 deep-dive sessions/week", "≥60% sessions exit on a saved artifact", "<25% bounces before second hop"]

MEASUREMENT SCAFFOLD (Arc 3.2 — makes results MEASURABLE, not just named):
For EVERY indicator, also emit an indicator_specs entry: {
  indicator           — the indicator text VERBATIM (must match an entry in indicators[]),
  unit                — the measurement unit ("min/session", "% of sessions", "score 1-10", "count/week"),
  measurement_method  — how you'd actually capture it ("session analytics", "daily self-report", "wearable", "GAD-7 instrument"),
  direction           — "increase" or "decrease": which way is GOOD for this indicator.
}
This is what lets the user set a real baseline → target later. Be concrete about unit + method — "vibes" is not a measurement method.

OUTCOME RULES:
- 3-5 outcomes, ordered by how directly they signal sub-objective success.
- ${TITLE_RULES}
- name describes the user-side STATE or BEHAVIOR, not the action and not a feature. "Sustained deep-dive sessions" ✅. "Increase session length" ❌ (action). "Engagement Tracking" ❌ (feature).
- Avoid feature-style nouns ("Engine", "Dashboard", "Layer", "Interface", "System", "Tool", "Feature", "Mechanism") in outcome titles — they signal you're naming a system part instead of a user state.

SUB-OBJECTIVE SCOPE TEST (mandatory — apply to EVERY outcome before emitting it):
Each outcome must be a USER STATE that this SPECIFIC sub-objective produces — not a generic win that any sub-objective would deliver.

Self-test: "If I removed this sub-objective's framing, would this outcome make sense as a win in a completely DIFFERENT sub-objective?"
  • YES it's generic → REJECT. You're naming a parent-objective-level win, not a sub-objective-specific one. Tighten until the outcome could only result from THIS sub-objective's mechanism.
  • NO it's specifically downstream of THIS sub-objective's work → KEEP.

❌ EXAMPLE — too generic (parent sub-objective = "Goal-Driven Search Optimization"):
   "Increased user satisfaction"   — applies to any successful product
   "Higher engagement"             — applies to any feature that works
   "Better financial outcomes"     — applies to any monetization sub-objective
✅ EXAMPLE — scoped (parent sub-objective = "Goal-Driven Search Optimization"):
   "Users find their stated goal in ≤3 results"
   "Search-to-action rate within goal context climbs 40%+"
   "Self-reported relevance scores match user-set goal weight"

${ANTI_PLATITUDE}

Return strict JSON.`;

  const outcomeCats = categoryBlock(ctx, "result");
  const ragO = ragSection(ctx);
  const lensO = annotationLensSection(ctx);
  const outcomeProps: Record<string, unknown> = {
    name: { type: "string" },
    measured_by: { type: "string" },
    // Phase 8 — 2-4 observable indicators mirroring pain.root_causes
    // so the Category Card right half can render symmetrically.
    indicators: { type: "array", items: { type: "string" } },
    // Arc 3.2 — per-indicator measurement scaffold. One entry per
    // indicator with unit + method + direction so results are
    // measurable at generation (seeded into indicator_baselines).
    indicator_specs: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          indicator: { type: "string" },
          unit: { type: "string" },
          measurement_method: { type: "string" },
          direction: { type: "string", enum: ["increase", "decrease"] },
        },
        required: ["indicator", "unit", "measurement_method", "direction"],
      },
    },
  };
  const outcomeRequired: string[] = [
    "name",
    "measured_by",
    "indicators",
    "indicator_specs",
  ];
  if (outcomeCats.slugs.length > 0) {
    outcomeProps.sub_category = { type: "string", enum: outcomeCats.slugs };
    outcomeRequired.push("sub_category");
  }
  if (ragO.ragBlock.length > 0) {
    outcomeProps.citations = { type: "array", items: { type: "number" } };
    outcomeRequired.push("citations");
  }
  if (lensO.hasAnnotations) {
    outcomeProps.derived_from_annotations = {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          index: { type: "number" },
          facet: {
            type: "string",
            enum: [
              "fragility",
              "analogy",
              "tension",
              "dimension",
              "inference",
              "reading",
            ],
          },
        },
        required: ["index", "facet"],
      },
    };
    outcomeRequired.push("derived_from_annotations");
  }

  const user = `PARENT OBJECTIVE:\n"""\n${ctx.coreObjectiveText}\n"""\n\nSUB-OBJECTIVE:\n"""\n${ctx.subObjectiveTitle}\n"""${clarifyingBlock(ctx.clarifyingAnswers)}${ctx.constraintsBlock ?? ""}${ctx.crossRoomFindingsBlock ?? ""}${ctx.learningsBlock ?? ""}

PAIN POINTS (each with its negative_outcome):
${painPoints.map((p, i) => `  ${i + 1}. ${p.name} → ${p.negative_outcome}`).join("\n")}${outcomeCats.instructions}${lensO.lensBlock}${lensO.provenanceRule}${ragO.ragBlock}${ragO.citationRule}

Generate 3-5 outcomes that, taken together, would dissolve those pains and roll up to the parent objective.${
    outcomeCats.slugs.length > 0
      ? " Each outcome must include sub_category — the slug of the result sub-category it belongs to."
      : ""
  }${
    ragO.ragBlock.length > 0
      ? " Each outcome must include citations[] — 1-based source indices (use ONLY indices from the RESEARCH CONTEXT list above)."
      : ""
  }${
    lensO.hasAnnotations
      ? " Each outcome must include derived_from_annotations[] — prefer dimension / inference facets here, since outcomes name the factors and chains the annotations identified as load-bearing in the objective."
      : ""
  }`;

  const raw = await llmJSON<OutcomeShape>({
    system,
    user,
    responseSchema: {
      name: "outcomes_v2",
      schema: {
        type: "object",
        additionalProperties: false,
        properties: {
          items: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: outcomeProps,
              required: outcomeRequired,
            },
          },
        },
        required: ["items"],
      },
    },
    temperature: 0.5,
    maxTokens: 1800,
  });
  return cleanOutcomes(raw?.items, ctx);
}

// ── Stage C: Features (with first principles + positive outcome) ───

interface FeatureShape {
  items?: Array<{
    name?: unknown;
    positive_outcome?: unknown;
    first_principles?: unknown;
    /** Arc 3.2 — declared causal bindings. */
    addresses?: unknown;
    moves?: unknown;
    sub_category?: unknown;
    citations?: unknown;
    derived_from_annotations?: unknown;
  }>;
}

async function generateFeatures(
  ctx: RoomContext,
  painPoints: PainItem[],
  outcomes: OutcomeItem[],
): Promise<FeatureItem[]> {
  const system = `You design the features that BRIDGE pain points to outcomes — anchored on both ends with first principles named.

A FEATURE is a concrete solution / mechanism / capability the system provides. For each feature, surface:
  • first_principles — 2-4 short noun phrases (≤6 words each) explaining WHY this works. The mechanism it leverages, the lever it pulls.
  • positive_outcome — what this feature produces when it lands. Single line. Often paired with an outcome above.

Features are generated LAST because they're anchored by both ends. Every feature must plausibly counter ≥1 pain AND produce ≥1 outcome. Features without two anchors are useless — drop them.

FEATURE RULES:
- 3-6 features, ordered by how much pain → outcome they cover.
- ${TITLE_RULES}
- first_principles reuse across features is REQUIRED when two features pull the same lever — use the IDENTICAL verbatim string, don't paraphrase. The shared-principle UI pill depends on exact matches.

CRITICAL — FEATURE ≠ OUTCOME:
- Feature names describe the SYSTEM'S CAPABILITY ("AI-Powered Curiosity Paths"). Outcomes describe USER STATE ("Users complete 5+ topic dives").
- Your feature title MUST NOT verbatim match or trivially paraphrase any outcome name in the DESIRED OUTCOMES list below. If it does, you've named a user-state and pretended it's a feature — rewrite.

SUB-OBJECTIVE SCOPE TEST (mandatory — apply to EVERY feature before emitting it):
Each feature must be a mechanism THIS sub-objective specifically requires — not a standalone feature that could be its own sub-objective.

Self-test: "Could this feature title swap in as a SIBLING SUB-OBJECTIVE name on the user's main canvas alongside the parent?"
  • YES it could be its own sub-objective → REJECT. You are escaping the layer. Drop it OR rewrite as a tighter mechanism inside this sub-objective's scope.
  • NO it only makes sense AS A LEVER INSIDE this sub-objective → KEEP.

Heuristic: if the feature title doesn't reference (or specialize) the sub-objective's core noun directly or by clear implication, it's probably escaping. "Goal Matching Engine" is a feature INSIDE "Goal-Driven Search Optimization". "Personalized Recommendations Engine" is its OWN sub-objective — not a feature of goal-driven search.

❌ EXAMPLE — escapes the layer (parent sub-objective = "Goal-Driven Search Optimization"):
   "Personalized Recommendations Engine"  — own sub-objective on canvas
   "User Feedback Loop System"            — own sub-objective on canvas
   "Privacy-Value Marketplace"            — clearly sibling territory
✅ EXAMPLE — scoped feature (parent sub-objective = "Goal-Driven Search Optimization"):
   "Goal-Matching Ranker"          — specific mechanism inside goal-driven search
   "Goal-Context Query Rewriter"   — specific mechanism inside goal-driven search
   "Goal-Drift Re-Sort Trigger"    — specific mechanism inside goal-driven search

3 strong scoped features beat 6 mixed-layer ones. Drop weak escapes rather than padding to a count.

POSITIVE_OUTCOME RULES:
- positive_outcome is the DOWNSTREAM consequence the feature produces. Like negative_outcome on a pain — it must be more informative than restating the feature title.
- BAD (paraphrase — REJECT): "Personalized Interest Dashboards" → "Personalization satisfaction improves"
- GOOD (downstream — KEEP):  "Personalized Interest Dashboards" → "Users return next day at 70%+"

DECLARED BINDINGS (Arc 3.2 — two-phase grounding — THIS IS LOAD-BEARING):
These declarations become the ACTUAL causal edges of the room. The chain is built from what you declare here, not re-guessed later. Be precise.
- addresses[] — 1-2 entries. Each: { pain (VERBATIM from the PAIN POINTS list), root_cause (VERBATIM from THAT pain's root_causes — the specific underlying cause this feature neutralizes) }. Only declare a pain this feature genuinely attacks AT THE ROOT-CAUSE level. If you can't name a specific root_cause it counters, you don't understand the mechanism yet — sharpen the feature.
- moves[] — 1-2 entries. Each: { outcome (VERBATIM from the DESIRED OUTCOMES list), indicator (VERBATIM from THAT outcome's indicators), direction ("increase" or "decrease" — the GOOD direction for that indicator) }. Name the SPECIFIC indicator this feature shifts, not the whole outcome.
- A feature must have ≥1 addresses AND ≥1 moves. A feature that can't connect a real root_cause to a real indicator is too vague — drop it rather than declaring a hand-wavy binding.

DATA I/O (Foundation — features are the OPERATORS of the data-flow graph):
- consumes[] — 1-4 snake_case tokens for the data this feature READS as input (e.g. user_interest_vector, session_history).
- produces[] — 1-4 snake_case tokens for the data this feature EMITS as output (e.g. ranked_feed, relevance_score).
- A feature is a TRANSFORM: upstream data in → downstream data out. Use short noun tokens, not sentences.
- REUSE tokens: if the SIBLING ROOMS block lists a token for data you read or write, use that EXACT token so the whole app shares ONE data substrate. Coin a new token only when nothing fits.

${ANTI_PLATITUDE}

Return strict JSON.`;

  const featureCats = categoryBlock(ctx, "mechanism");
  const ragF = ragSection(ctx);
  const lensF = annotationLensSection(ctx);
  const featureProps: Record<string, unknown> = {
    name: { type: "string" },
    positive_outcome: { type: "string" },
    first_principles: { type: "array", items: { type: "string" } },
    // Arc 3.2 — declared causal bindings (two-phase grounding). These
    // become the room's Pain→Feature + Feature→Outcome edges directly.
    addresses: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          pain: { type: "string" },
          root_cause: { type: "string" },
        },
        required: ["pain", "root_cause"],
      },
    },
    moves: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          outcome: { type: "string" },
          indicator: { type: "string" },
          direction: { type: "string", enum: ["increase", "decrease"] },
        },
        required: ["outcome", "indicator", "direction"],
      },
    },
    // Foundation B — feature-level data I/O tokens (the operators of the
    // cross-room data-flow graph). snake_case data units in/out.
    consumes: { type: "array", items: { type: "string" } },
    produces: { type: "array", items: { type: "string" } },
  };
  const featureRequired: string[] = [
    "name",
    "positive_outcome",
    "first_principles",
    "addresses",
    "moves",
    "consumes",
    "produces",
  ];
  if (featureCats.slugs.length > 0) {
    featureProps.sub_category = { type: "string", enum: featureCats.slugs };
    featureRequired.push("sub_category");
  }
  if (ragF.ragBlock.length > 0) {
    featureProps.citations = { type: "array", items: { type: "number" } };
    featureRequired.push("citations");
  }
  if (lensF.hasAnnotations) {
    featureProps.derived_from_annotations = {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          index: { type: "number" },
          facet: {
            type: "string",
            enum: [
              "fragility",
              "analogy",
              "tension",
              "dimension",
              "inference",
              "reading",
            ],
          },
        },
        required: ["index", "facet"],
      },
    };
    featureRequired.push("derived_from_annotations");
  }

  const user = `PARENT OBJECTIVE:\n"""\n${ctx.coreObjectiveText}\n"""\n\nSUB-OBJECTIVE:\n"""\n${ctx.subObjectiveTitle}\n"""${clarifyingBlock(ctx.clarifyingAnswers)}${ctx.constraintsBlock ?? ""}${ctx.crossRoomFindingsBlock ?? ""}${ctx.learningsBlock ?? ""}${ctx.siblingDataBlock ?? ""}

PAIN POINTS (with negative_outcomes + root_causes — declare addresses[] against these):
${painPoints
  .map(
    (p, i) =>
      `  ${i + 1}. ${p.name} → ${p.negative_outcome}${
        p.root_causes.length > 0
          ? `\n     root_causes: ${p.root_causes.join(" · ")}`
          : ""
      }`,
  )
  .join("\n")}

DESIRED OUTCOMES (with indicators — declare moves[] against these):
${outcomes
  .map(
    (o, i) =>
      `  ${i + 1}. ${o.name} (measured by: ${o.measured_by})${
        o.indicators.length > 0
          ? `\n     indicators: ${o.indicators.join(" · ")}`
          : ""
      }`,
  )
  .join("\n")}${featureCats.instructions}${lensF.lensBlock}${lensF.provenanceRule}${ragF.ragBlock}${ragF.citationRule}

Generate 3-6 features that bridge the pains to the outcomes. Each feature must plausibly counter ≥1 pain AND produce ≥1 outcome, and DECLARE those bindings in addresses[] (pain + root_cause) and moves[] (outcome + indicator + direction). Each feature must ALSO declare consumes[] and produces[] — the snake_case data tokens it reads and emits (reuse tokens from the SIBLING ROOMS block when the data already flows there).${
    featureCats.slugs.length > 0
      ? " Each feature must include sub_category — the slug of the mechanism sub-category it belongs to."
      : ""
  }${
    ragF.ragBlock.length > 0
      ? " Each feature must include citations[] — 1-based source indices (use ONLY indices from the RESEARCH CONTEXT list above)."
      : ""
  }${
    lensF.hasAnnotations
      ? " Each feature must include derived_from_annotations[] — prefer analogy / inference facets here, since features are the LEVERS the annotations' cross-domain mappings and reasoning chains suggest."
      : ""
  }`;

  const raw = await llmJSON<FeatureShape>({
    system,
    user,
    responseSchema: {
      name: "features_v2",
      schema: {
        type: "object",
        additionalProperties: false,
        properties: {
          items: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: featureProps,
              required: featureRequired,
            },
          },
        },
        required: ["items"],
      },
    },
    temperature: 0.55,
    maxTokens: 2200,
  });
  return cleanFeatures(raw?.items, ctx);
}

// ── Stage D: Cross-layer correlations (with annotation provenance) ──

interface CorrelationShape {
  edges?: Array<{
    source?: unknown;
    target?: unknown;
    relationship?: unknown;
    strength?: unknown;
    polarity?: unknown;
    mechanism?: unknown;
    rationale?: unknown;
    /** Plural to align with the item schema. 0 or 1 entries; we
     *  collapse to a single AnnotationProvenance in the cleaner. */
    derived_from_annotations?: unknown;
  }>;
}

/** Item handed to the correlation pass.
 *
 *  Phase-2 content-aware edges: alongside id/name/layer the LLM now
 *  sees the BODY of each item — the actual semantic content from the
 *  generator's causal_chain output. This is what lets edges be
 *  grounded in real content overlaps (which root_cause × which
 *  first_principle) instead of label-matching guesses.
 *
 *  Body fields are optional — the correlation pass degrades to the
 *  legacy name-only mode when bodies aren't provided (older callers,
 *  partial-data paths, the side-panel "Generate correlations" retry
 *  button which only has ids). When bodies ARE provided, the tagged
 *  block expands to a structured per-item card the LLM can reason
 *  over directly. */
interface ItemRef {
  id: string;
  name: string;
  layer: "pain" | "outcomes" | "features" | "objective";
  /** Pain body — the negative outcome the pain produces. */
  negative_outcome?: string;
  /** Pain body — the underlying causes (3-5 typical). */
  root_causes?: string[];
  /** Feature body — the positive outcome the feature produces. */
  positive_outcome?: string;
  /** Feature body — the load-bearing principles (3-5 typical). */
  first_principles?: string[];
  /** Outcome body — the signal that confirms this outcome. */
  measured_by?: string;
}

/** Correlation result — items + an optional single-annotation
 *  provenance entry. Edges are atomic (one source → one target)
 *  so a single annotation is the natural granularity: most often
 *  a tension (X conflicts with Y) or an inference_chain hop
 *  (step A transitions to step B). */
export interface CorrelationResult {
  sourceId: string;
  targetId: string;
  relationship: string;
  strength: number;
  polarity: "positive" | "negative" | "ambiguous";
  rationale: string;
  mechanism: string;
  /** Annotation Lens — single resolved provenance entry the LLM
   *  tagged this edge with, if any. Persisted into
   *  edge.agent_feedback.derived_from_annotation. */
  derived_from_annotation?: AnnotationProvenance;
}

async function generateCorrelations(
  ctx: RoomContext,
  items: ItemRef[],
): Promise<CorrelationResult[]> {
  if (items.length < 2) return [];

  const tagged = items.map((it, i) => ({
    ...it,
    tag: `${it.layer[0].toUpperCase()}${i + 1}`,
  }));
  const idByTag = new Map(tagged.map((t) => [t.tag, t.id]));

  // Counts to enforce quotas in the prompt so the LLM doesn't
  // exclusively produce pain→feature edges and leave the outcome
  // lane disconnected from the rest.
  const layerCounts = items.reduce(
    (acc, it) => {
      acc[it.layer] = (acc[it.layer] ?? 0) + 1;
      return acc;
    },
    {} as Record<string, number>,
  );

  const lensC = annotationLensSection(ctx);

  // Phase-2 — does this room have body content? If so, the prompt
  // upgrades from name-only label matching to content-aware grounding.
  // The hasBodies flag also controls how the user prompt formats each
  // item (structured block with negative_outcome/root_causes/etc. vs.
  // single-line tagged label).
  const hasBodies = tagged.some(
    (it) =>
      (typeof it.negative_outcome === "string" && it.negative_outcome.length > 0) ||
      (Array.isArray(it.root_causes) && it.root_causes.length > 0) ||
      (typeof it.positive_outcome === "string" && it.positive_outcome.length > 0) ||
      (Array.isArray(it.first_principles) && it.first_principles.length > 0) ||
      (typeof it.measured_by === "string" && it.measured_by.length > 0),
  );

  const groundingRule = hasBodies
    ? `
CONTENT-AWARE GROUNDING (this is the most important rule):
Every item carries its BODY — pains carry { negative_outcome, root_causes }; features carry { positive_outcome, first_principles }; outcomes carry { measured_by }. Do NOT pick edges by label-matching the names. Pick edges by naming a SPECIFIC OVERLAP between bodies:
  • pain → features  : which feature's first_principle attacks which of the pain's root_causes? Name BOTH in the rationale.
  • features → outcomes : which feature's first_principle produces the signal the outcome is measured_by? Name both.
  • pain → outcomes : which root_cause's removal IS the measured_by signal? Name both.
  • outcomes → objective : which measured_by aggregates into the parent objective?

If you cannot name a specific content overlap, the edge does not exist — do not emit it. "X and Y share a domain" is NOT a grounding; only specific phrase-to-phrase overlap counts.

The mechanism field becomes the NAMED LEVER that bridges the two phrases. The rationale must reference the specific phrases on both ends.
`
    : "";

  const system = `You rank cross-layer correlations inside one sub-objective room.

Items live in four layers (Pain → Features → Outcomes → Objective). Produce edges that connect items ACROSS layers — never within the same layer, never "because they're in the same room."

ALLOWED DIRECTIONS (each is a distinct kind of insight):
  pain → features         (the feature ADDRESSES this pain)
  features → outcomes     (the feature PRODUCES this outcome)
  pain → outcomes         (the absence-of-this-pain IS the outcome)
  outcomes → objective    (the outcome ROLLS UP to the room objective)
  features → pain         (rare — only if a feature notably AGGRAVATES a pain)

QUOTAS — Phase 8 FULL-COVERAGE requirement (do NOT under-emit):
  EVERY feature MUST have ≥ 1 incoming pain → feature edge.
    No "dangling" features. If a feature has no pain it credibly
    addresses, the feature shouldn't exist in this room — surface
    that by emitting a weak edge (strength ≥ 0.3) labeled
    "weak — feature lacks a credible target pain."
  EVERY feature MUST have ≥ 1 outgoing feature → outcome edge.
    Same rule. A feature that produces no outcome is a feature
    that does nothing.
  ≥ 1 outcome → objective edge       (the room must visibly roll up)
  ≥ 1 pain → outcome edge            (when an outcome is literally "absence of this pain")

The above guarantees: every feature anchors at least one chain
(pain → feature → outcome triplet). Chains are the actionable unit
the user sees in the Category View — leaving features dangling means
those features won't appear in any experiment frame.

Total edges: target N_features × 2 + 2 (roll-up + pain→outcome) at
minimum; up to N_features × 3 if multiple pains/outcomes connect to
the same feature. Don't artificially cap. Quality > coverage on any
SINGLE edge (drop strength<0.3), but cover EVERY feature on both
sides.

If a feature genuinely can't be bridged on one side, emit the
strongest weak edge available AND mark its rationale "weak — feature
lacks a credible {source|target}" so the user can see the gap rather
than the feature silently disappearing from the experiment view.
${groundingRule}
EDGE PROPERTIES:
- relationship: SHORT lowercase verb phrase (1-3 words). Examples: "addresses", "produces", "rolls up to", "dissolves", "depends on", "aggravates".
- strength ∈ [0,1]: load-bearing-ness. ≥0.7 critical, 0.4-0.7 supportive, <0.4 weak.${
    hasBodies
      ? `
    Strength is now grounded in content overlap — count and quality of the specific phrase-to-phrase overlaps between source and target bodies. A feature whose first_principles each map to a different root_cause of the pain is a strong (0.8+) edge. A feature that touches one weak peripheral aspect is a 0.3-0.4 edge.`
      : ""
  }
- polarity: positive | negative | ambiguous.
- mechanism: 2-5 word NOUN PHRASE naming the SPECIFIC LEVER this edge pulls.
    Examples: "reward feedback loop", "predictive query expansion", "social proof cue",
    "intrinsic motivation hook", "cognitive load reduction".
    NOT generic ("user engagement", "personalization improvement") — those are restatements,
    not levers. The mechanism is the THING THAT MAKES THE EDGE WORK.${
      hasBodies
        ? `
    With body content available, the mechanism MUST be the bridge between named phrases — e.g. if pain.root_causes contains "overwhelmed by choices" and feature.first_principles contains "session memory", the mechanism might be "decision residue caching" (the thing the session memory implements that resolves the overwhelm).`
        : ""
    }
- rationale: ONE or TWO sentences explaining WHY this specific source attacks this specific target
    via the named mechanism. Reference the user's actual domain. NOT a tautology
    ("X helps Y because X helps Y" is forbidden).${
      hasBodies
        ? `
    With body content, rationale MUST quote or paraphrase the specific source-side phrase (root_cause or first_principle) and the specific target-side phrase (first_principle or measured_by) that the mechanism bridges.`
        : ""
    }

Quality over coverage: drop any edge whose strength would be < 0.3.

Return strict JSON.`;

  // Edge-level annotation provenance — array of 0 or 1 entries so
  // the schema can stay strict-mode (every field required, no
  // optional). 0 entries = no annotation justifies the edge; 1
  // entry = a specific lens reading seeded it. Tensions and
  // inference hops are the most natural facets here (X conflicts
  // with Y is already a relationship; an inference hop names a
  // step → step transition).
  const EDGE_PROVENANCE_RULE = `EDGE PROVENANCE: For each edge, include derived_from_annotations[] — an array of AT MOST ONE entry. When this edge is rooted in one of the ANNOTATION LENS readings, emit a single { index: 1-based lens index, facet: "tension" | "inference" | "fragility" | "analogy" | "dimension" | "reading" } entry. PREFER tension (the annotation explicitly named conflict / harmony between source and target concepts) or inference (the edge IS a hop in the annotation's reasoning chain). Emit an EMPTY array [] when no annotation justifies the edge — DO NOT invent links.`;

  /** Render a single item — structured block when bodies are
   *  present, single-line tag when they aren't. Trims long fields
   *  to keep the prompt compact (~50 words per item ceiling). */
  function renderItem(it: typeof tagged[number]): string {
    const head = `  ${it.tag} [${it.layer.toUpperCase()}] "${it.name.trim()}"`;
    if (!hasBodies) return head;
    const lines: string[] = [head];
    if (it.layer === "pain") {
      if (it.negative_outcome) {
        lines.push(`    negative_outcome: ${it.negative_outcome.trim().slice(0, 180)}`);
      }
      if (Array.isArray(it.root_causes) && it.root_causes.length > 0) {
        const causes = it.root_causes
          .filter((c): c is string => typeof c === "string" && c.length > 0)
          .slice(0, 5)
          .map((c) => c.trim().slice(0, 80));
        if (causes.length > 0) {
          lines.push(`    root_causes: ${causes.join(" · ")}`);
        }
      }
    } else if (it.layer === "features") {
      if (it.positive_outcome) {
        lines.push(`    positive_outcome: ${it.positive_outcome.trim().slice(0, 180)}`);
      }
      if (Array.isArray(it.first_principles) && it.first_principles.length > 0) {
        const principles = it.first_principles
          .filter((c): c is string => typeof c === "string" && c.length > 0)
          .slice(0, 5)
          .map((c) => c.trim().slice(0, 80));
        if (principles.length > 0) {
          lines.push(`    first_principles: ${principles.join(" · ")}`);
        }
      }
    } else if (it.layer === "outcomes") {
      if (it.measured_by) {
        lines.push(`    measured_by: ${it.measured_by.trim().slice(0, 180)}`);
      }
    }
    return lines.join("\n");
  }

  const user = `SUB-OBJECTIVE: ${ctx.subObjectiveTitle}

ITEMS${hasBodies ? " (with bodies)" : " BY TAG"}:
${tagged.map(renderItem).join(hasBodies ? "\n\n" : "\n")}

INVENTORY: ${layerCounts.pain ?? 0} pain, ${layerCounts.features ?? 0} features, ${layerCounts.outcomes ?? 0} outcomes, ${layerCounts.objective ?? 0} objective.${lensC.lensBlock}${lensC.hasAnnotations ? `\n\n${EDGE_PROVENANCE_RULE}\n` : ""}

Phase 8 FULL-COVERAGE: every one of the ${layerCounts.features ?? 0} feature(s) MUST have ≥1 incoming pain edge AND ≥1 outgoing outcome edge. This is required so EVERY feature anchors at least one (pain → feature → outcome) chain in the user's Category View. Total edges should be ≥ 2 × (features count) + 2 (roll-up + pain→outcome) at minimum. Don't under-emit — leaving features dangling drops them from the experiment view entirely.${
    hasBodies
      ? " Ground each edge in a specific content overlap per the system instructions — name the source-side phrase and the target-side phrase that the mechanism bridges."
      : ""
  }${
    lensC.hasAnnotations
      ? " Each edge must include derived_from_annotations[] — 0 or 1 entries (empty [] when no annotation seeds the edge)."
      : ""
  }`;

  // Build the per-edge schema. derived_from_annotations is only
  // required when the lens has entries — keeps backward compat with
  // rooms whose parent has no annotations.
  const edgeProps: Record<string, unknown> = {
    source: { type: "string" },
    target: { type: "string" },
    relationship: { type: "string" },
    strength: { type: "number" },
    polarity: {
      type: "string",
      enum: ["positive", "negative", "ambiguous"],
    },
    mechanism: { type: "string" },
    rationale: { type: "string" },
  };
  const edgeRequired: string[] = [
    "source",
    "target",
    "relationship",
    "strength",
    "polarity",
    "mechanism",
    "rationale",
  ];
  if (lensC.hasAnnotations) {
    edgeProps.derived_from_annotations = {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          index: { type: "number" },
          facet: {
            type: "string",
            enum: [
              "fragility",
              "analogy",
              "tension",
              "dimension",
              "inference",
              "reading",
            ],
          },
        },
        required: ["index", "facet"],
      },
    };
    edgeRequired.push("derived_from_annotations");
  }

  const raw = await llmJSON<CorrelationShape>({
    system,
    user,
    responseSchema: {
      name: "correlations",
      schema: {
        type: "object",
        additionalProperties: false,
        properties: {
          edges: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: edgeProps,
              required: edgeRequired,
            },
          },
        },
        required: ["edges"],
      },
    },
    temperature: 0.4,
    // Phase 8 — bumped from 2800 to cover the new full-coverage
    // quota. Each edge ~180 tokens (relationship + strength +
    // mechanism + rationale + provenance). 20 edges × 180 = 3600
    // tokens — leave headroom at 4200.
    maxTokens: 4200,
  });
  const lens = lensForResolution(ctx);
  const cleaned: CorrelationResult[] = [];
  for (const e of raw?.edges ?? []) {
    const srcTag =
      typeof e?.source === "string" ? e.source.trim().toUpperCase() : "";
    const tgtTag =
      typeof e?.target === "string" ? e.target.trim().toUpperCase() : "";
    const srcId = idByTag.get(srcTag);
    const tgtId = idByTag.get(tgtTag);
    if (!srcId || !tgtId || srcId === tgtId) continue;
    const relationship =
      typeof e?.relationship === "string"
        ? e.relationship.trim().toLowerCase().slice(0, 40)
        : "";
    if (relationship.length === 0) continue;
    const strength =
      typeof e?.strength === "number" && Number.isFinite(e.strength)
        ? Math.max(0, Math.min(1, e.strength))
        : 0.5;
    if (strength < 0.3) continue;
    const polarity =
      e?.polarity === "positive" ||
      e?.polarity === "negative" ||
      e?.polarity === "ambiguous"
        ? e.polarity
        : "positive";
    const rationale =
      typeof e?.rationale === "string" ? e.rationale.trim() : "";
    const mechanism =
      typeof e?.mechanism === "string" ? e.mechanism.trim().slice(0, 60) : "";
    // Edge provenance: at most 1 entry. The LLM emits derived_from_annotations[]
    // even on edges that aren't seeded by an annotation — empty array there.
    // resolveProvenance() shape-cleans + resolves indices against the lens;
    // we take the first valid entry as the edge's single provenance.
    const provList = resolveProvenance(e?.derived_from_annotations, lens);
    const derivedFrom: AnnotationProvenance | undefined =
      provList && provList.length > 0 ? provList[0] : undefined;
    cleaned.push({
      sourceId: srcId,
      targetId: tgtId,
      relationship,
      strength,
      polarity,
      rationale,
      mechanism,
      derived_from_annotation: derivedFrom,
    });
  }
  // Phase 8 full-coverage — cap grows with feature count so every
  // feature can be bridged on both sides. Floor at 14 (legacy);
  // ceiling at 2 × features + 4 to leave headroom for cross-lane
  // quotas (pain→outcome, outcome→objective) + a small slack.
  const featureCount = layerCounts.features ?? 0;
  const maxEdges = Math.max(14, featureCount * 2 + 4);
  return cleaned.slice(0, maxEdges);
}

// ── Orchestrator ───────────────────────────────────────────────────

// ── Checkpoint split (Arc 3.6) ─────────────────────────────────────
//
// The room generator's natural order is problem (pain) → result
// (outcome) → mechanism (feature). To let the user REVIEW + EDIT +
// SHARPEN the problem and result BEFORE mechanisms commit, the
// orchestrator is split into two stages the route can run
// independently:
//
//   runDefineStage    — stages A+B (pain + outcome). Produces the
//                       "problem & result" substrate the checkpoint UI
//                       renders. Carries indicator_specs (Arc 3.2) so
//                       results are measurable from the start.
//   runMechanismStage — stage C (features), fed the (possibly user-
//                       EDITED) pains + outcomes. Because Arc 3.2 makes
//                       each feature DECLARE addresses[]/moves[] against
//                       specific root_causes + indicators, editing a
//                       root_cause/indicator at the checkpoint changes
//                       which binding the mechanism declares — the edit
//                       propagates straight into the causal chain.
//
// runLayeredGeneration stays as the one-shot wrapper (autopilot +
// phase:"all" back-compat) — it just calls both in sequence.

export async function runDefineStage(ctx: RoomContext): Promise<{
  pain: PainItem[];
  outcomes: OutcomeItem[];
  top_negative_outcome: string;
  lane_labels: LaneLabels;
}> {
  const painPass = await generatePainPoints(ctx);
  const outcomes = await generateOutcomes(ctx, painPass.items);
  return {
    pain: painPass.items,
    outcomes,
    top_negative_outcome: painPass.top_negative_outcome,
    lane_labels: painPass.lane_labels,
  };
}

export async function runMechanismStage(
  ctx: RoomContext,
  pain: PainItem[],
  outcomes: OutcomeItem[],
): Promise<{ features: FeatureItem[] }> {
  const features = await generateFeatures(ctx, pain, outcomes);
  return { features };
}

export async function runLayeredGeneration(ctx: RoomContext): Promise<{
  pain: PainItem[];
  outcomes: OutcomeItem[];
  features: FeatureItem[];
  top_negative_outcome: string;
  lane_labels: LaneLabels;
}> {
  const define = await runDefineStage(ctx);
  const { features } = await runMechanismStage(
    ctx,
    define.pain,
    define.outcomes,
  );
  return {
    pain: define.pain,
    outcomes: define.outcomes,
    features,
    top_negative_outcome: define.top_negative_outcome,
    lane_labels: define.lane_labels,
  };
}

export async function linkCorrelations(
  ctx: RoomContext,
  items: ItemRef[],
) {
  return generateCorrelations(ctx, items);
}

// ── Phase 8b — Within-Layer Links ─────────────────────────────────
//
// Companion to generateCorrelations. The cross-layer pass connects
// pain → feature → outcome — the chain spine. This second pass
// connects features ↔ features WITHIN the mechanism lane to surface
// COMPOSITION (one feature builds on another) or CONFLICT (two
// features would step on each other if both elected).
//
// Why a separate pass:
//   • Different prompt shape — focus on internal first_principles
//     overlap + implementation collision, not on causal direction
//   • Different schema — relationship_type takes only two values
//     (composes_with / interferes_with)
//   • Different cardinality — typical room emits 0-3 within-layer
//     edges; we don't need quota gates
//
// Surfaces in the UI as:
//   • Small chips on each Category Card ("composes with X" / "conflicts with X")
//   • Lateral wires in the SVG overlay (dashed, lane-tinted)
//   • Input to the R&D refine prompt (Phase 5b) so candidates
//     respect sibling elections

export interface WithinLayerLink {
  sourceId: string;
  targetId: string;
  /** Two values only — composition (build-on) or conflict (collision).
   *  Other kinds (e.g. "depends_on") collapse to composes_with for now. */
  kind: "composes_with" | "interferes_with";
  /** 0-1 — how load-bearing the relationship is. <0.3 dropped. */
  strength: number;
  /** 1 sentence why — quoting the first_principle overlap or the
   *  specific conflict. */
  rationale: string;
}

interface WithinLayerShape {
  links?: Array<{
    source?: unknown;
    target?: unknown;
    kind?: unknown;
    strength?: unknown;
    rationale?: unknown;
  }>;
}

async function generateWithinLayerLinks(
  ctx: RoomContext,
  features: ItemRef[],
): Promise<WithinLayerLink[]> {
  // Within-layer makes sense only for FEATURES in this MVP — pain
  // manifestations and outcome facets aren't IVs you compose or
  // conflict. We could extend later.
  const mechFeatures = features.filter((it) => it.layer === "features");
  if (mechFeatures.length < 2) return [];

  const tagged = mechFeatures.map((it, i) => ({
    ...it,
    tag: `M${i + 1}`,
  }));
  const idByTag = new Map(tagged.map((t) => [t.tag, t.id]));

  const system = `You evaluate WITHIN-LAYER relationships between mechanisms (features) in a sub-objective room. The cross-layer pass already connected each mechanism to a pain it addresses and an outcome it produces. Your job now is sibling-to-sibling:

COMPOSES_WITH — one mechanism BUILDS ON or EXTENDS another. Their first_principles compose (M1's output is M2's input, OR they share a load-bearing principle, OR they're complementary phases of the same intervention).

INTERFERES_WITH — two mechanisms CONFLICT. Their first_principles contradict (electing both would require contradictory implementations, OR they compete for the same scarce resource, OR they target the same root_cause in incompatible ways).

OUTPUT RULES:
- Quality over quantity. If no clear relationship exists, emit nothing. Most pairs have neither.
- Each entry: source tag (e.g. M1), target tag (e.g. M3), kind, strength 0-1, rationale (1 sentence quoting the SPECIFIC first_principle that drives the composition or conflict).
- Strength: ≥0.7 means "electing both as-is requires explicit coordination." 0.4-0.7 "worth flagging." <0.3 drop.
- Pairs are SYMMETRIC for composes_with (order doesn't matter) but emit only ONE entry per pair. Use tag-alphabetical order (M1→M3, not M3→M1).
- Rationale MUST cite a specific first_principle phrase from one of the mechanisms — not a generic restatement.

Return strict JSON.`;

  const itemBlock = tagged
    .map((it) => {
      const principles = Array.isArray(it.first_principles)
        ? it.first_principles
            .filter((s): s is string => typeof s === "string" && s.length > 0)
            .slice(0, 5)
            .join(" · ")
        : "";
      const positive = it.positive_outcome ?? "";
      return `  ${it.tag} "${it.name.trim()}"
    positive_outcome: ${positive.slice(0, 180)}
    first_principles: ${principles}`;
    })
    .join("\n\n");

  const user = `SUB-OBJECTIVE: ${ctx.subObjectiveTitle}

MECHANISMS (sibling features in this room):

${itemBlock}

Identify composition or conflict pairs among these mechanisms per the system instructions. Emit only pairs where the first_principles cite a specific overlap or collision — generic "they could work together" pairs MUST be dropped.`;

  const raw = await llmJSON<WithinLayerShape>({
    system,
    user,
    responseSchema: {
      name: "within_layer_links",
      schema: {
        type: "object",
        additionalProperties: false,
        properties: {
          links: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: {
                source: { type: "string" },
                target: { type: "string" },
                kind: {
                  type: "string",
                  enum: ["composes_with", "interferes_with"],
                },
                strength: { type: "number" },
                rationale: { type: "string" },
              },
              required: [
                "source",
                "target",
                "kind",
                "strength",
                "rationale",
              ],
            },
          },
        },
        required: ["links"],
      },
    },
    temperature: 0.3,
    maxTokens: 1200,
  });

  const out: WithinLayerLink[] = [];
  const seenPairs = new Set<string>();
  for (const e of raw?.links ?? []) {
    const srcTag =
      typeof e?.source === "string" ? e.source.trim().toUpperCase() : "";
    const tgtTag =
      typeof e?.target === "string" ? e.target.trim().toUpperCase() : "";
    const srcId = idByTag.get(srcTag);
    const tgtId = idByTag.get(tgtTag);
    if (!srcId || !tgtId || srcId === tgtId) continue;
    // Dedupe symmetric pairs — composes_with is undirected, the LLM
    // sometimes emits both M1→M3 and M3→M1.
    const pairKey = [srcId, tgtId].sort().join("|");
    if (seenPairs.has(pairKey)) continue;
    seenPairs.add(pairKey);
    const kind =
      e?.kind === "interferes_with"
        ? "interferes_with"
        : "composes_with";
    const strength =
      typeof e?.strength === "number" && Number.isFinite(e.strength)
        ? Math.max(0, Math.min(1, e.strength))
        : 0.5;
    if (strength < 0.3) continue;
    const rationale =
      typeof e?.rationale === "string" ? e.rationale.trim().slice(0, 240) : "";
    if (rationale.length === 0) continue;
    out.push({
      sourceId: srcId,
      targetId: tgtId,
      kind,
      strength,
      rationale,
    });
  }
  // Cap at 6 — within-layer should be sparse; more than that is noise.
  return out.slice(0, 6);
}

export async function linkWithinLayer(
  ctx: RoomContext,
  items: ItemRef[],
): Promise<WithinLayerLink[]> {
  return generateWithinLayerLinks(ctx, items);
}

// ── Cleaners (with verb-prefix safety net) ─────────────────────────

const VERB_PREFIX_PATTERN =
  /^(develop|implement|create|design|build|enhance|establish|drive|deliver|provide|enable|generate|produce|conduct)\s+(a\s+|the\s+)?/i;

function stripVerbPrefix(s: string): string {
  const stripped = s.replace(VERB_PREFIX_PATTERN, "").trim();
  if (stripped.length === 0) return s.trim();
  return stripped.charAt(0).toUpperCase() + stripped.slice(1);
}

function trimList(raw: unknown, max: number, maxLen: number): string[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .filter((s): s is string => typeof s === "string" && s.trim().length > 0)
    .map((s) => s.trim().slice(0, maxLen))
    .slice(0, max);
}

/** Normalize lane_labels: each label is trimmed, capped at 24 chars
 *  (compact enough to fit in a lane header), and falls back to the
 *  canonical name when missing so the UI always has something to
 *  show. */
function cleanLaneLabels(raw: unknown): LaneLabels {
  const fallback: LaneLabels = {
    pain: "Pain points",
    features: "Features",
    outcomes: "Outcomes",
    objective: "Objective",
  };
  if (!raw || typeof raw !== "object") return fallback;
  const r = raw as Record<string, unknown>;
  const one = (key: keyof LaneLabels): string => {
    const v = r[key];
    if (typeof v !== "string") return fallback[key];
    const cleaned = v.trim().replace(/[.!?,:;]+$/g, "").slice(0, 24).trim();
    return cleaned.length > 0 ? cleaned : fallback[key];
  };
  return {
    pain: one("pain"),
    features: one("features"),
    outcomes: one("outcomes"),
    objective: one("objective"),
  };
}

function cleanSubCategory(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const t = raw.trim();
  return t.length > 0 ? t.slice(0, 40) : null;
}

/** Sanitize the LLM-emitted citations[] — keep only positive
 *  integers, dedup, cap at 5. Returns undefined when the input
 *  wasn't an array (let callers omit the field cleanly). */
function cleanCitations(raw: unknown): number[] | undefined {
  if (!Array.isArray(raw)) return undefined;
  const out = new Set<number>();
  for (const v of raw) {
    if (typeof v === "number" && Number.isFinite(v) && v >= 1) {
      out.add(Math.floor(v));
    }
  }
  return Array.from(out).slice(0, 5);
}

const ANNOTATION_FACETS = new Set([
  "fragility",
  "analogy",
  "tension",
  "dimension",
  "inference",
  "reading",
]);

/** Sanitize the LLM-emitted derived_from_annotations[]. Each entry
 *  is { index, facet }. Indices are clamped to the available lens
 *  list (resolved by the caller against ctx.annotations); facets
 *  default to "reading" when the LLM emits an unknown string.
 *  Returns undefined when input wasn't an array (callers omit the
 *  field for legacy/no-annotation rooms). Caller is responsible
 *  for resolving 1-based indices into the actual annotation
 *  records — this cleaner only normalizes shape. */
function cleanDerivedFromAnnotations(
  raw: unknown,
): Array<{ index: number; facet: AnnotationProvenance["facet"] }> | undefined {
  if (!Array.isArray(raw)) return undefined;
  const seen = new Set<number>();
  const out: Array<{ index: number; facet: AnnotationProvenance["facet"] }> = [];
  for (const v of raw) {
    if (!v || typeof v !== "object") continue;
    const r = v as Record<string, unknown>;
    const rawIndex =
      typeof r.index === "number" && Number.isFinite(r.index)
        ? Math.floor(r.index)
        : NaN;
    if (!Number.isFinite(rawIndex) || rawIndex < 1) continue;
    if (seen.has(rawIndex)) continue;
    seen.add(rawIndex);
    const facet =
      typeof r.facet === "string" && ANNOTATION_FACETS.has(r.facet)
        ? (r.facet as AnnotationProvenance["facet"])
        : "reading";
    out.push({ index: rawIndex, facet });
    if (out.length >= 3) break;
  }
  return out;
}

/** Resolve raw {index, facet} pairs against the lens (the weight-sorted
 *  top-8 annotations the LLM saw) into AnnotationProvenance records
 *  that carry the verbatim phrase. Out-of-range indices are dropped.
 *  Pass undefined when no annotations were available — returns
 *  undefined so the field is cleanly omitted on the item. */
function resolveProvenance(
  raw: unknown,
  lens: ObjectiveAnnotation[],
): AnnotationProvenance[] | undefined {
  if (lens.length === 0) return undefined;
  const cleaned = cleanDerivedFromAnnotations(raw);
  if (!cleaned) return undefined;
  const out: AnnotationProvenance[] = [];
  for (const entry of cleaned) {
    const ann = lens[entry.index - 1];
    if (!ann) continue;
    out.push({
      index: entry.index,
      phrase: ann.phrase,
      facet: entry.facet,
      // Phase 2 — bake the canonical concept identity into the
      // persisted provenance so downstream cross-room analyses can
      // group by hard-keyed slug instead of re-deriving from phrase
      // text. The lens IS the parent objective's annotations, so the
      // ObjectiveAnnotation type already carries concept_slug from
      // the v3 generator + the normalizer's slugify(phrase) backfill.
      concept_slug: ann.concept_slug,
      concept: ann.concept,
    });
  }
  return out;
}

/** The lens the prompt actually saw (weight-sorted, capped at 8).
 *  Cleaners need this to resolve 1-based indices the LLM emitted. */
function lensForResolution(ctx: RoomContext): ObjectiveAnnotation[] {
  const anns = ctx.annotations ?? [];
  if (anns.length === 0) return [];
  return [...anns]
    .sort((a, b) => (b.weight ?? 0.5) - (a.weight ?? 0.5))
    .slice(0, 8);
}

function cleanPains(raw: unknown, ctx: RoomContext): PainItem[] {
  if (!Array.isArray(raw)) return [];
  const lens = lensForResolution(ctx);
  return raw
    .map((p): PainItem | null => {
      if (!p || typeof p !== "object") return null;
      const r = p as Record<string, unknown>;
      const name = typeof r.name === "string" ? r.name.trim() : "";
      if (name.length === 0) return null;
      const neg =
        typeof r.negative_outcome === "string" ? r.negative_outcome.trim() : "";
      const causes = trimList(r.root_causes, 4, 80);
      const rank =
        typeof r.influence_rank === "number" && Number.isFinite(r.influence_rank)
          ? Math.max(0, Math.min(5, r.influence_rank))
          : 2.5;
      return {
        name: stripVerbPrefix(name).slice(0, 200),
        negative_outcome: neg.slice(0, 200),
        root_causes: causes,
        influence_rank: rank,
        sub_category: cleanSubCategory(r.sub_category),
        citations: cleanCitations(r.citations),
        derived_from_annotations: resolveProvenance(
          r.derived_from_annotations,
          lens,
        ),
      };
    })
    .filter((p): p is PainItem => p !== null)
    .slice(0, 5);
}

/** Foundation B — normalize a raw produces/consumes array into clean
 *  snake_case data tokens. Lowercases, collapses non-alphanumerics to
 *  underscores, drops empties + dupes, caps at 6 tokens × 48 chars. The
 *  space data-unit registry canonicalizes further on registration. */
function cleanTokens(raw: unknown): string[] {
  if (!Array.isArray(raw)) return [];
  const out: string[] = [];
  const seen = new Set<string>();
  for (const v of raw) {
    if (typeof v !== "string") continue;
    const tok = v
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 48);
    if (tok.length === 0 || seen.has(tok)) continue;
    seen.add(tok);
    out.push(tok);
    if (out.length >= 6) break;
  }
  return out;
}

function cleanFeatures(raw: unknown, ctx: RoomContext): FeatureItem[] {
  if (!Array.isArray(raw)) return [];
  const lens = lensForResolution(ctx);
  return raw
    .map((p): FeatureItem | null => {
      if (!p || typeof p !== "object") return null;
      const r = p as Record<string, unknown>;
      const name = typeof r.name === "string" ? r.name.trim() : "";
      if (name.length === 0) return null;
      const pos =
        typeof r.positive_outcome === "string" ? r.positive_outcome.trim() : "";
      const principles = trimList(r.first_principles, 4, 80);
      // Arc 3.2 — clean declared bindings. Drop entries missing the
      // load-bearing endpoint (pain / outcome name); cap at 4 each.
      const addresses = Array.isArray(r.addresses)
        ? (r.addresses as unknown[])
            .map((a) => {
              if (!a || typeof a !== "object") return null;
              const o = a as Record<string, unknown>;
              const pain =
                typeof o.pain === "string" ? o.pain.trim().slice(0, 200) : "";
              if (!pain) return null;
              const root_cause =
                typeof o.root_cause === "string"
                  ? o.root_cause.trim().slice(0, 160)
                  : "";
              return { pain, root_cause };
            })
            .filter(
              (a): a is { pain: string; root_cause: string } => a !== null,
            )
            .slice(0, 4)
        : [];
      const moves = Array.isArray(r.moves)
        ? (r.moves as unknown[])
            .map((m) => {
              if (!m || typeof m !== "object") return null;
              const o = m as Record<string, unknown>;
              const outcome =
                typeof o.outcome === "string"
                  ? o.outcome.trim().slice(0, 200)
                  : "";
              if (!outcome) return null;
              const indicator =
                typeof o.indicator === "string"
                  ? o.indicator.trim().slice(0, 100)
                  : "";
              const direction =
                o.direction === "decrease" ? "decrease" : "increase";
              return { outcome, indicator, direction: direction as "increase" | "decrease" };
            })
            .filter(
              (m): m is { outcome: string; indicator: string; direction: "increase" | "decrease" } =>
                m !== null,
            )
            .slice(0, 4)
        : [];
      const consumes = cleanTokens(r.consumes);
      const produces = cleanTokens(r.produces);
      return {
        name: stripVerbPrefix(name).slice(0, 200),
        positive_outcome: pos.slice(0, 200),
        first_principles: principles,
        addresses: addresses.length > 0 ? addresses : undefined,
        moves: moves.length > 0 ? moves : undefined,
        sub_category: cleanSubCategory(r.sub_category),
        citations: cleanCitations(r.citations),
        derived_from_annotations: resolveProvenance(
          r.derived_from_annotations,
          lens,
        ),
        consumes: consumes.length > 0 ? consumes : undefined,
        produces: produces.length > 0 ? produces : undefined,
      };
    })
    .filter((p): p is FeatureItem => p !== null)
    .slice(0, 6);
}

function cleanOutcomes(raw: unknown, ctx: RoomContext): OutcomeItem[] {
  if (!Array.isArray(raw)) return [];
  const lens = lensForResolution(ctx);
  return raw
    .map((p): OutcomeItem | null => {
      if (!p || typeof p !== "object") return null;
      const r = p as Record<string, unknown>;
      const name = typeof r.name === "string" ? r.name.trim() : "";
      if (name.length === 0) return null;
      const measured =
        typeof r.measured_by === "string" ? r.measured_by.trim() : "";
      // Phase 8 — clean indicators[]. Drop empties, cap at 4,
      // trim each to 100 chars. Backward-compat: when LLM
      // didn't emit indicators (older prompt) or returned empty,
      // synthesize a single-entry array from measured_by so the
      // UI can render consistently.
      const indicatorsRaw = Array.isArray(r.indicators)
        ? (r.indicators as unknown[])
            .filter((s): s is string => typeof s === "string" && s.trim().length > 0)
            .map((s) => s.trim().slice(0, 100))
            .slice(0, 4)
        : [];
      const indicators =
        indicatorsRaw.length > 0
          ? indicatorsRaw
          : measured.length > 0
            ? [measured]
            : [];
      // Arc 3.2 — clean the per-indicator measurement scaffold. Drop
      // entries without an indicator name; cap at 6; tolerate missing
      // unit/method/direction (soft signals).
      const indicatorSpecs = Array.isArray(r.indicator_specs)
        ? (r.indicator_specs as unknown[])
            .map((s) => {
              if (!s || typeof s !== "object") return null;
              const o = s as Record<string, unknown>;
              const indicator =
                typeof o.indicator === "string"
                  ? o.indicator.trim().slice(0, 100)
                  : "";
              if (!indicator) return null;
              const unit =
                typeof o.unit === "string" && o.unit.trim().length > 0
                  ? o.unit.trim().slice(0, 60)
                  : undefined;
              const measurement_method =
                typeof o.measurement_method === "string" &&
                o.measurement_method.trim().length > 0
                  ? o.measurement_method.trim().slice(0, 160)
                  : undefined;
              const direction =
                o.direction === "increase" || o.direction === "decrease"
                  ? (o.direction as "increase" | "decrease")
                  : undefined;
              return { indicator, unit, measurement_method, direction };
            })
            .filter(
              (s): s is NonNullable<typeof s> => s !== null,
            )
            .slice(0, 6)
        : [];
      return {
        name: stripVerbPrefix(name).slice(0, 200),
        measured_by: measured.slice(0, 150),
        indicators,
        indicator_specs:
          indicatorSpecs.length > 0 ? indicatorSpecs : undefined,
        sub_category: cleanSubCategory(r.sub_category),
        citations: cleanCitations(r.citations),
        derived_from_annotations: resolveProvenance(
          r.derived_from_annotations,
          lens,
        ),
      };
    })
    .filter((p): p is OutcomeItem => p !== null)
    .slice(0, 5);
}
