// ── Objective Canvas — middle-out 4-stage room generator (v2) ──
//
// Generates the contents of one sub-objective's room with a real
// causal chain per item:
//
//   PAIN POINT     root_causes[] →  pain title (effect)  →  negative_outcome
//   FEATURE        first_principles[] →  feature title  →  positive_outcome
//   OUTCOME        title + measured_by (a concrete signal)
//   OBJECTIVE      a single anchor (the sub-objective title)
//
// Middle-out order: pain points first (they anchor the bottom);
// outcomes next (anchored by pains + the objective); features last
// (anchored by both ends). After entities exist a separate pass
// produces ranked cross-layer correlation edges.
//
// We also surface a room-level `top_negative_outcome`: the single
// most-impactful downstream consequence across all pain points,
// used as the room's header anchor ("Counters: …").

import { llmJSON } from "@/lib/llm";

interface LayerRow {
  id: string;
  slug: string;
  label: string;
}

export interface RoomCategoryEnum {
  /** slug → label. The LLM must pick one slug per item from this map. */
  friction: Record<string, string>;
  mechanism: Record<string, string>;
  result: Record<string, string>;
}

export interface RoomContext {
  spaceId: string;
  userId: string;
  subObjectiveId: string;
  subObjectiveTitle: string;
  subObjectiveDescription: string | null;
  coreObjectiveText: string;
  clarifyingAnswers: Array<{ question: string; answer: string }>;
  layersBySlug: Map<"pain" | "features" | "outcomes" | "objective", LayerRow>;
  /** Tier 3 — adaptive sub-categories generated by the pre-room
   *  step. When empty, items are emitted with sub_category=null
   *  (legacy behavior). When populated, each item MUST be tagged
   *  with one slug from its lane's enum. */
  categories?: RoomCategoryEnum;
  /** Commit-2 research integration — pre-built RESEARCH CONTEXT
   *  block from research-service.buildRagBlock(). When present
   *  (and non-empty), prepended to every stage's user prompt so
   *  the LLM grounds items in real sources and emits citations[]
   *  per item. When absent / empty, generation falls back to
   *  pure first-principles reasoning with no citations. */
  ragBlock?: string;
}

// ── Output shapes ──────────────────────────────────────────────────

export interface PainItem {
  name: string;
  /** What this pain leads to downstream — a single concrete state. */
  negative_outcome: string;
  /** 2-4 short noun phrases (≤6 words each) — the underlying causes. */
  root_causes: string[];
  /** 0-5 LLM self-assessment of how central this pain is. Higher =
   *  this pain influences / contributes to more other pains. The
   *  highest-ranked pain in the room renders with the Root ⭐ badge. */
  influence_rank: number;
  /** Tier 3 — sub-category slug picked from RoomCategories.friction.
   *  null when categories weren't provided for this room. */
  sub_category?: string | null;
  /** Commit-2 research integration — 1-based indices into the
   *  RESEARCH CONTEXT source list that informed this item. Empty
   *  when the item is pure first-principles or research is
   *  unavailable. */
  citations?: number[];
}

export interface FeatureItem {
  name: string;
  /** What this feature produces when it lands — single concrete state. */
  positive_outcome: string;
  /** 2-4 short noun phrases (≤6 words each) — why this works. */
  first_principles: string[];
  /** Tier 3 — sub-category slug picked from RoomCategories.mechanism. */
  sub_category?: string | null;
  /** Commit-2 — 1-based source indices informing this feature. */
  citations?: number[];
}

export interface OutcomeItem {
  name: string;
  /** A concrete proxy / signal that says "yes this happened". */
  measured_by: string;
  /** Tier 3 — sub-category slug picked from RoomCategories.result. */
  sub_category?: string | null;
  /** Commit-2 — 1-based source indices informing this outcome. */
  citations?: number[];
}

// ── Shared scaffolding ─────────────────────────────────────────────

const ANTI_PLATITUDE = `ANTI-PLATITUDE: every item references something specific from the sub-objective or clarifying answers. Items that could appear unchanged on a different sub-objective MUST be rewritten.`;

/** Shared citation rule injected into every stage prompt when RAG
 *  context is present. The 1-based indices match the source list
 *  rendered in buildRagBlock(). Strict: don't invent ids. */
const CITATION_RULE = `CITATIONS: For each item, include a citations[] array of 1-based source indices from the RESEARCH CONTEXT block above when the item is informed by those sources. Use ONLY indices that exist in the source list — never invent. Empty array [] when the item is pure first-principles. Cite 0-3 sources per item; quality over quantity.`;

/** Render the RAG block + citation rule for prompt prepend. When
 *  no rag block is provided, returns empty strings so callers can
 *  template uniformly without conditional logic. */
function ragSection(ctx: RoomContext): {
  ragBlock: string;
  citationRule: string;
} {
  if (!ctx.ragBlock || ctx.ragBlock.length === 0) {
    return { ragBlock: "", citationRule: "" };
  }
  return {
    ragBlock: `\n\n${ctx.ragBlock}\n`,
    citationRule: `\n\n${CITATION_RULE}\n`,
  };
}

const TITLE_RULES = `TITLE: noun phrase, ≤6 words. Do NOT start with action verbs (develop/implement/create/design/build/enhance/establish). Title-case OK; no terminal punctuation.`;

function clarifyingBlock(
  answers: RoomContext["clarifyingAnswers"],
): string {
  if (answers.length === 0) return "";
  return `\n\nCLARIFYING ANSWERS:\n${answers
    .map((a, i) => `  ${i + 1}. ${a.question} → ${a.answer}`)
    .join("\n")}`;
}

// ── Stage A: Pain points (with causal chain) ───────────────────────

interface PainShape {
  items?: Array<{
    name?: unknown;
    negative_outcome?: unknown;
    root_causes?: unknown;
    influence_rank?: unknown;
    sub_category?: unknown;
    citations?: unknown;
  }>;
  top_negative_outcome?: unknown;
  lane_labels?: {
    pain?: unknown;
    features?: unknown;
    outcomes?: unknown;
    objective?: unknown;
  };
}

/** Builds the categories block injected into stage prompts. Returns
 *  empty string when no categories are configured for this room. */
function categoryBlock(
  ctx: RoomContext,
  lane: keyof RoomCategoryEnum,
): { instructions: string; slugs: string[] } {
  const cats = ctx.categories?.[lane];
  if (!cats) return { instructions: "", slugs: [] };
  const entries = Object.entries(cats);
  if (entries.length === 0) return { instructions: "", slugs: [] };
  const list = entries
    .map(([slug, label]) => `    "${slug}" → ${label}`)
    .join("\n");
  const slugs = entries.map(([slug]) => slug);
  return {
    slugs,
    instructions: `\n\nSUB-CATEGORIES (every item in this lane MUST be tagged with one of these slugs — pick the best fit; never invent new slugs):\n${list}\n`,
  };
}

/** Adaptive lane labels — the four bucket nouns chosen by the LLM
 *  to match the sub-objective's domain. Empty strings collapse to
 *  the canonical fallbacks in the room view. */
export interface LaneLabels {
  pain: string;
  features: string;
  outcomes: string;
  objective: string;
}

interface PainPassResult {
  items: PainItem[];
  /** Single line synthesizing the worst downstream consequence
   *  across all pains — the room header anchor. */
  top_negative_outcome: string;
  /** Domain-specific 4 lane labels (≤2 words each). */
  lane_labels: LaneLabels;
}

async function generatePainPoints(
  ctx: RoomContext,
): Promise<PainPassResult> {
  const system = `You map the load-bearing pain points a sub-objective must address — with their causal chain made explicit.

A pain point is an observable EFFECT in the user's world. Every pain has TWO ENDS we want named:
  • root_causes — the underlying reasons it exists. 2-4 short noun phrases (≤6 words each). Concrete and orthogonal. These are what a SOLUTION would attack.
  • negative_outcome — what this pain leads to downstream if not addressed. Single line, one concrete state.

Also include an INFLUENCE_RANK (0-5): how much does this pain feed / amplify other pains? A pain that causes 3 other pains scores high; an isolated pain scores low.

ROOM SYNTHESIS:
After listing the pains, produce a single TOP_NEGATIVE_OUTCOME: the worst downstream consequence the room exists to counter, synthesizing across all pains. One short line — used as the room's header anchor.

LANE LABELS (adaptive):
Also pick four short noun labels that match the user's DOMAIN — these rename the four lanes of the room so they speak the user's language. Each label is ≤2 words, title-case, no terminal punctuation:
  • lane_labels.pain      → the bucket name for "problems / frictions / symptoms" in this domain
  • lane_labels.features  → the bucket name for "solutions / mechanisms / levers / bets" in this domain
  • lane_labels.outcomes  → the bucket name for "results / states / wins" in this domain
  • lane_labels.objective → name the umbrella anchor for this domain (often "Objective" or "Goal")

Examples by domain:
  App / product:        { pain: "Frictions",  features: "Features",    outcomes: "Outcomes",         objective: "Objective" }
  Curriculum / course:  { pain: "Gaps",       features: "Lessons",     outcomes: "Skills",           objective: "Mastery"   }
  Clinical / therapy:   { pain: "Symptoms",   features: "Mechanisms",  outcomes: "Functional gains", objective: "Recovery"  }
  Strategy / business:  { pain: "Frictions",  features: "Bets",        outcomes: "Wins",             objective: "Goal"      }
  Research:             { pain: "Open Qs",    features: "Investigations", outcomes: "Findings",      objective: "Thesis"    }
  Workout / health:     { pain: "Limits",     features: "Movements",   outcomes: "Capacities",       objective: "Goal"      }
  Operations:           { pain: "Frictions",  features: "Levers",      outcomes: "Throughput",       objective: "Target"    }

Pick labels FROM the user's actual domain. Never invent jargon. Stay specific.

PAIN RULES:
- 3-5 pains, ordered by influence_rank descending.
- ${TITLE_RULES}
- Pain titles name the EFFECT ("Low engagement depth"), not the cause ("Generic results") and not the outcome ("Superficial browsing"). Those go in the root_causes and negative_outcome fields respectively.

NEGATIVE_OUTCOME RULES (critical — read carefully):
- Must be the DOWNSTREAM CONSEQUENCE of the pain, not a paraphrase of the title.
- Self-test: if removing the title's key noun makes the negative_outcome still meaningful and informative, you've done it right. If they read as synonyms, REWRITE.
- BAD (synonyms — REJECT):
    title: "Low Interface Engagement"     → negative_outcome: "Users lose interest quickly"
    title: "Poor Personalization"         → negative_outcome: "Users feel disconnected"
- GOOD (downstream — KEEP):
    title: "Low Interface Engagement"     → negative_outcome: "Product churn within the first session"
    title: "Poor Personalization"         → negative_outcome: "Users never reach an aha moment"
    title: "Slow Onboarding"              → negative_outcome: "Trial users abandon before activating value"
- Single line, ≤14 words, concrete and observable.

SHARED ROOT CAUSES (required, not optional):
- If two pains share an underlying mechanism, you MUST use the IDENTICAL verbatim root_cause string in both items. Don't paraphrase. Don't pluralize. Don't re-case.
- Aim for 1-2 root causes that recur across ≥2 pains. The shared-cause UI pill above the lane EXISTS to surface these — if no root_causes overlap, the user sees no systemic insight.

${ANTI_PLATITUDE}

Return strict JSON.`;

  const painCats = categoryBlock(ctx, "friction");
  const rag = ragSection(ctx);
  const itemProps: Record<string, unknown> = {
    name: { type: "string" },
    negative_outcome: { type: "string" },
    root_causes: { type: "array", items: { type: "string" } },
    influence_rank: { type: "number" },
  };
  const itemRequired: string[] = [
    "name",
    "negative_outcome",
    "root_causes",
    "influence_rank",
  ];
  if (painCats.slugs.length > 0) {
    itemProps.sub_category = { type: "string", enum: painCats.slugs };
    itemRequired.push("sub_category");
  }
  if (rag.ragBlock.length > 0) {
    itemProps.citations = { type: "array", items: { type: "number" } };
    itemRequired.push("citations");
  }

  const user = `PARENT OBJECTIVE:\n"""\n${ctx.coreObjectiveText}\n"""\n\nSUB-OBJECTIVE (room scope):\n"""\n${ctx.subObjectiveTitle}${
    ctx.subObjectiveDescription
      ? `\n\n${ctx.subObjectiveDescription}`
      : ""
  }\n"""${clarifyingBlock(ctx.clarifyingAnswers)}${painCats.instructions}${rag.ragBlock}${rag.citationRule}

Generate 3-5 pain points with full causal chains, plus the single TOP_NEGATIVE_OUTCOME for the room.${
    painCats.slugs.length > 0
      ? " Each pain must include sub_category — the slug of the friction sub-category it belongs to."
      : ""
  }${
    rag.ragBlock.length > 0
      ? " Each pain must include citations[] — 1-based source indices (use ONLY indices from the RESEARCH CONTEXT list above)."
      : ""
  }`;

  const raw = await llmJSON<PainShape>({
    system,
    user,
    responseSchema: {
      name: "pain_points_v2",
      schema: {
        type: "object",
        additionalProperties: false,
        properties: {
          top_negative_outcome: { type: "string" },
          lane_labels: {
            type: "object",
            additionalProperties: false,
            properties: {
              pain: { type: "string" },
              features: { type: "string" },
              outcomes: { type: "string" },
              objective: { type: "string" },
            },
            required: ["pain", "features", "outcomes", "objective"],
          },
          items: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: itemProps,
              required: itemRequired,
            },
          },
        },
        required: ["items", "top_negative_outcome", "lane_labels"],
      },
    },
    temperature: 0.5,
    maxTokens: 2400,
  });

  const items = cleanPains(raw?.items);
  const top =
    typeof raw?.top_negative_outcome === "string"
      ? raw.top_negative_outcome.trim().slice(0, 200)
      : "";
  const lane_labels = cleanLaneLabels(raw?.lane_labels);
  return { items, top_negative_outcome: top, lane_labels };
}

// ── Stage B: Outcomes ──────────────────────────────────────────────

interface OutcomeShape {
  items?: Array<{
    name?: unknown;
    measured_by?: unknown;
    sub_category?: unknown;
    citations?: unknown;
  }>;
}

async function generateOutcomes(
  ctx: RoomContext,
  painPoints: PainItem[],
): Promise<OutcomeItem[]> {
  const system = `You name the outcomes the sub-objective should produce — anchored on both ends.

An OUTCOME is what's OBSERVABLY TRUE about the USER (or their world) when the sub-objective lands. Outcomes describe a STATE or a BEHAVIOR — never a capability the system has.

CRITICAL — OUTCOME ≠ FEATURE:
- Outcomes describe what HAPPENS to the user. Features describe what the system DOES.
- A feature can produce an outcome, but they are NEVER the same object.
- ❌ NEVER restate a feature name as an outcome. If a feature is "Gamification Layer", the outcome is NOT "Integrated Gamification Features" — the outcome is "Users complete 5+ topic dives per session" or "Self-reported curiosity score 4/5".
- ❌ NEVER name an outcome after a system capability ("Simplified User Interface", "Personalized Dashboard"). Those are features.
- ✅ Outcomes start with the user: "Users return next day at 70%+", "Self-reported flow during sessions", "Time-to-first-aha drops below 90 seconds".
- Self-test: read your outcome aloud. If it sounds like something an engineer would build, it's a feature — rewrite as the user's experienced state.

For each outcome include MEASURED_BY: a concrete proxy/signal that says "yes this happened" (e.g. "8+ min/session", "85% return next day", "self-reported flow 4/5"). One short line.

OUTCOME RULES:
- 3-5 outcomes, ordered by how directly they signal sub-objective success.
- ${TITLE_RULES}
- name describes the user-side STATE or BEHAVIOR, not the action and not a feature. "Sustained deep-dive sessions" ✅. "Increase session length" ❌ (action). "Engagement Tracking" ❌ (feature).
- Avoid feature-style nouns ("Engine", "Dashboard", "Layer", "Interface", "System", "Tool", "Feature", "Mechanism") in outcome titles — they signal you're naming a system part instead of a user state.

${ANTI_PLATITUDE}

Return strict JSON.`;

  const outcomeCats = categoryBlock(ctx, "result");
  const ragO = ragSection(ctx);
  const outcomeProps: Record<string, unknown> = {
    name: { type: "string" },
    measured_by: { type: "string" },
  };
  const outcomeRequired: string[] = ["name", "measured_by"];
  if (outcomeCats.slugs.length > 0) {
    outcomeProps.sub_category = { type: "string", enum: outcomeCats.slugs };
    outcomeRequired.push("sub_category");
  }
  if (ragO.ragBlock.length > 0) {
    outcomeProps.citations = { type: "array", items: { type: "number" } };
    outcomeRequired.push("citations");
  }

  const user = `PARENT OBJECTIVE:\n"""\n${ctx.coreObjectiveText}\n"""\n\nSUB-OBJECTIVE:\n"""\n${ctx.subObjectiveTitle}\n"""${clarifyingBlock(ctx.clarifyingAnswers)}

PAIN POINTS (each with its negative_outcome):
${painPoints.map((p, i) => `  ${i + 1}. ${p.name} → ${p.negative_outcome}`).join("\n")}${outcomeCats.instructions}${ragO.ragBlock}${ragO.citationRule}

Generate 3-5 outcomes that, taken together, would dissolve those pains and roll up to the parent objective.${
    outcomeCats.slugs.length > 0
      ? " Each outcome must include sub_category — the slug of the result sub-category it belongs to."
      : ""
  }${
    ragO.ragBlock.length > 0
      ? " Each outcome must include citations[] — 1-based source indices (use ONLY indices from the RESEARCH CONTEXT list above)."
      : ""
  }`;

  const raw = await llmJSON<OutcomeShape>({
    system,
    user,
    responseSchema: {
      name: "outcomes_v2",
      schema: {
        type: "object",
        additionalProperties: false,
        properties: {
          items: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: outcomeProps,
              required: outcomeRequired,
            },
          },
        },
        required: ["items"],
      },
    },
    temperature: 0.5,
    maxTokens: 1800,
  });
  return cleanOutcomes(raw?.items);
}

// ── Stage C: Features (with first principles + positive outcome) ───

interface FeatureShape {
  items?: Array<{
    name?: unknown;
    positive_outcome?: unknown;
    first_principles?: unknown;
    sub_category?: unknown;
    citations?: unknown;
  }>;
}

async function generateFeatures(
  ctx: RoomContext,
  painPoints: PainItem[],
  outcomes: OutcomeItem[],
): Promise<FeatureItem[]> {
  const system = `You design the features that BRIDGE pain points to outcomes — anchored on both ends with first principles named.

A FEATURE is a concrete solution / mechanism / capability the system provides. For each feature, surface:
  • first_principles — 2-4 short noun phrases (≤6 words each) explaining WHY this works. The mechanism it leverages, the lever it pulls.
  • positive_outcome — what this feature produces when it lands. Single line. Often paired with an outcome above.

Features are generated LAST because they're anchored by both ends. Every feature must plausibly counter ≥1 pain AND produce ≥1 outcome. Features without two anchors are useless — drop them.

FEATURE RULES:
- 3-6 features, ordered by how much pain → outcome they cover.
- ${TITLE_RULES}
- first_principles reuse across features is REQUIRED when two features pull the same lever — use the IDENTICAL verbatim string, don't paraphrase. The shared-principle UI pill depends on exact matches.

CRITICAL — FEATURE ≠ OUTCOME:
- Feature names describe the SYSTEM'S CAPABILITY ("AI-Powered Curiosity Paths"). Outcomes describe USER STATE ("Users complete 5+ topic dives").
- Your feature title MUST NOT verbatim match or trivially paraphrase any outcome name in the DESIRED OUTCOMES list below. If it does, you've named a user-state and pretended it's a feature — rewrite.

POSITIVE_OUTCOME RULES:
- positive_outcome is the DOWNSTREAM consequence the feature produces. Like negative_outcome on a pain — it must be more informative than restating the feature title.
- BAD (paraphrase — REJECT): "Personalized Interest Dashboards" → "Personalization satisfaction improves"
- GOOD (downstream — KEEP):  "Personalized Interest Dashboards" → "Users return next day at 70%+"

${ANTI_PLATITUDE}

Return strict JSON.`;

  const featureCats = categoryBlock(ctx, "mechanism");
  const ragF = ragSection(ctx);
  const featureProps: Record<string, unknown> = {
    name: { type: "string" },
    positive_outcome: { type: "string" },
    first_principles: { type: "array", items: { type: "string" } },
  };
  const featureRequired: string[] = [
    "name",
    "positive_outcome",
    "first_principles",
  ];
  if (featureCats.slugs.length > 0) {
    featureProps.sub_category = { type: "string", enum: featureCats.slugs };
    featureRequired.push("sub_category");
  }
  if (ragF.ragBlock.length > 0) {
    featureProps.citations = { type: "array", items: { type: "number" } };
    featureRequired.push("citations");
  }

  const user = `PARENT OBJECTIVE:\n"""\n${ctx.coreObjectiveText}\n"""\n\nSUB-OBJECTIVE:\n"""\n${ctx.subObjectiveTitle}\n"""${clarifyingBlock(ctx.clarifyingAnswers)}

PAIN POINTS (with negative_outcomes):
${painPoints.map((p, i) => `  ${i + 1}. ${p.name} → ${p.negative_outcome}`).join("\n")}

DESIRED OUTCOMES:
${outcomes.map((o, i) => `  ${i + 1}. ${o.name} (measured by: ${o.measured_by})`).join("\n")}${featureCats.instructions}${ragF.ragBlock}${ragF.citationRule}

Generate 3-6 features that bridge the pains to the outcomes. Each feature must plausibly counter ≥1 pain AND produce ≥1 outcome.${
    featureCats.slugs.length > 0
      ? " Each feature must include sub_category — the slug of the mechanism sub-category it belongs to."
      : ""
  }${
    ragF.ragBlock.length > 0
      ? " Each feature must include citations[] — 1-based source indices (use ONLY indices from the RESEARCH CONTEXT list above)."
      : ""
  }`;

  const raw = await llmJSON<FeatureShape>({
    system,
    user,
    responseSchema: {
      name: "features_v2",
      schema: {
        type: "object",
        additionalProperties: false,
        properties: {
          items: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: featureProps,
              required: featureRequired,
            },
          },
        },
        required: ["items"],
      },
    },
    temperature: 0.55,
    maxTokens: 2200,
  });
  return cleanFeatures(raw?.items);
}

// ── Stage D: Cross-layer correlations (unchanged from v1) ──────────

interface CorrelationShape {
  edges?: Array<{
    source?: unknown;
    target?: unknown;
    relationship?: unknown;
    strength?: unknown;
    polarity?: unknown;
    mechanism?: unknown;
    rationale?: unknown;
  }>;
}

interface ItemRef {
  id: string;
  name: string;
  layer: "pain" | "outcomes" | "features" | "objective";
}

async function generateCorrelations(
  ctx: RoomContext,
  items: ItemRef[],
): Promise<
  Array<{
    sourceId: string;
    targetId: string;
    relationship: string;
    strength: number;
    polarity: "positive" | "negative" | "ambiguous";
    rationale: string;
    mechanism: string;
  }>
> {
  if (items.length < 2) return [];

  const tagged = items.map((it, i) => ({
    ...it,
    tag: `${it.layer[0].toUpperCase()}${i + 1}`,
  }));
  const idByTag = new Map(tagged.map((t) => [t.tag, t.id]));

  // Counts to enforce quotas in the prompt so the LLM doesn't
  // exclusively produce pain→feature edges and leave the outcome
  // lane disconnected from the rest.
  const layerCounts = items.reduce(
    (acc, it) => {
      acc[it.layer] = (acc[it.layer] ?? 0) + 1;
      return acc;
    },
    {} as Record<string, number>,
  );

  const system = `You rank cross-layer correlations inside one sub-objective room.

Items live in four layers (Pain → Features → Outcomes → Objective). Produce edges that connect items ACROSS layers — never within the same layer, never "because they're in the same room."

ALLOWED DIRECTIONS (each is a distinct kind of insight):
  pain → features         (the feature ADDRESSES this pain)
  features → outcomes     (the feature PRODUCES this outcome)
  pain → outcomes         (the absence-of-this-pain IS the outcome)
  outcomes → objective    (the outcome ROLLS UP to the room objective)
  features → pain         (rare — only if a feature notably AGGRAVATES a pain)

QUOTAS (required minimums — do NOT skip any layer pair):
  ≥ 2 pain → features edges
  ≥ 2 features → outcomes edges      (outcomes that have NO incoming feature edge are a failure of the analysis)
  ≥ 1 outcome → objective edge        (the room must visibly roll up)
  ≥ 1 pain → outcome edge             (when an outcome is literally "absence of this pain")
Total: 6-14 edges across the room. If quotas can't be met because an outcome / objective genuinely has no upstream link, you MUST surface why in the rationale (e.g. "weak — outcome lacks a producing mechanism").

EDGE PROPERTIES:
- relationship: SHORT lowercase verb phrase (1-3 words). Examples: "addresses", "produces", "rolls up to", "dissolves", "depends on", "aggravates".
- strength ∈ [0,1]: load-bearing-ness. ≥0.7 critical, 0.4-0.7 supportive, <0.4 weak.
- polarity: positive | negative | ambiguous.
- mechanism: 2-5 word NOUN PHRASE naming the SPECIFIC LEVER this edge pulls.
    Examples: "reward feedback loop", "predictive query expansion", "social proof cue",
    "intrinsic motivation hook", "cognitive load reduction".
    NOT generic ("user engagement", "personalization improvement") — those are restatements,
    not levers. The mechanism is the THING THAT MAKES THE EDGE WORK.
- rationale: ONE or TWO sentences explaining WHY this specific source attacks this specific target
    via the named mechanism. Reference the user's actual domain. NOT a tautology
    ("X helps Y because X helps Y" is forbidden).

Quality over coverage: drop any edge whose strength would be < 0.3.

Return strict JSON.`;

  const user = `SUB-OBJECTIVE: ${ctx.subObjectiveTitle}

ITEMS BY TAG:
${tagged.map((it) => `  ${it.tag} [${it.layer}] ${it.name}`).join("\n")}

INVENTORY: ${layerCounts.pain ?? 0} pain, ${layerCounts.features ?? 0} features, ${layerCounts.outcomes ?? 0} outcomes, ${layerCounts.objective ?? 0} objective.

Generate 6-14 cross-layer edges per the quotas in the system instructions. Every outcome should have ≥1 incoming feature edge; if it doesn't, the analysis has a gap.`;

  const raw = await llmJSON<CorrelationShape>({
    system,
    user,
    responseSchema: {
      name: "correlations",
      schema: {
        type: "object",
        additionalProperties: false,
        properties: {
          edges: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: {
                source: { type: "string" },
                target: { type: "string" },
                relationship: { type: "string" },
                strength: { type: "number" },
                polarity: {
                  type: "string",
                  enum: ["positive", "negative", "ambiguous"],
                },
                mechanism: { type: "string" },
                rationale: { type: "string" },
              },
              required: [
                "source",
                "target",
                "relationship",
                "strength",
                "polarity",
                "mechanism",
                "rationale",
              ],
            },
          },
        },
        required: ["edges"],
      },
    },
    temperature: 0.4,
    maxTokens: 2800,
  });
  const cleaned: Array<{
    sourceId: string;
    targetId: string;
    relationship: string;
    strength: number;
    polarity: "positive" | "negative" | "ambiguous";
    rationale: string;
    mechanism: string;
  }> = [];
  for (const e of raw?.edges ?? []) {
    const srcTag =
      typeof e?.source === "string" ? e.source.trim().toUpperCase() : "";
    const tgtTag =
      typeof e?.target === "string" ? e.target.trim().toUpperCase() : "";
    const srcId = idByTag.get(srcTag);
    const tgtId = idByTag.get(tgtTag);
    if (!srcId || !tgtId || srcId === tgtId) continue;
    const relationship =
      typeof e?.relationship === "string"
        ? e.relationship.trim().toLowerCase().slice(0, 40)
        : "";
    if (relationship.length === 0) continue;
    const strength =
      typeof e?.strength === "number" && Number.isFinite(e.strength)
        ? Math.max(0, Math.min(1, e.strength))
        : 0.5;
    if (strength < 0.3) continue;
    const polarity =
      e?.polarity === "positive" ||
      e?.polarity === "negative" ||
      e?.polarity === "ambiguous"
        ? e.polarity
        : "positive";
    const rationale =
      typeof e?.rationale === "string" ? e.rationale.trim() : "";
    const mechanism =
      typeof e?.mechanism === "string" ? e.mechanism.trim().slice(0, 60) : "";
    cleaned.push({
      sourceId: srcId,
      targetId: tgtId,
      relationship,
      strength,
      polarity,
      rationale,
      mechanism,
    });
  }
  // Don't aggressively cap at 12 anymore — the prompt allows up to 14
  // to make room for the cross-layer quotas (pain→outcome, outcome→objective).
  return cleaned.slice(0, 14);
}

// ── Orchestrator ───────────────────────────────────────────────────

export async function runLayeredGeneration(ctx: RoomContext): Promise<{
  pain: PainItem[];
  outcomes: OutcomeItem[];
  features: FeatureItem[];
  top_negative_outcome: string;
  lane_labels: LaneLabels;
}> {
  const painPass = await generatePainPoints(ctx);
  const outcomes = await generateOutcomes(ctx, painPass.items);
  const features = await generateFeatures(ctx, painPass.items, outcomes);
  return {
    pain: painPass.items,
    outcomes,
    features,
    top_negative_outcome: painPass.top_negative_outcome,
    lane_labels: painPass.lane_labels,
  };
}

export async function linkCorrelations(
  ctx: RoomContext,
  items: ItemRef[],
) {
  return generateCorrelations(ctx, items);
}

// ── Cleaners (with verb-prefix safety net) ─────────────────────────

const VERB_PREFIX_PATTERN =
  /^(develop|implement|create|design|build|enhance|establish|drive|deliver|provide|enable|generate|produce|conduct)\s+(a\s+|the\s+)?/i;

function stripVerbPrefix(s: string): string {
  const stripped = s.replace(VERB_PREFIX_PATTERN, "").trim();
  if (stripped.length === 0) return s.trim();
  return stripped.charAt(0).toUpperCase() + stripped.slice(1);
}

function trimList(raw: unknown, max: number, maxLen: number): string[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .filter((s): s is string => typeof s === "string" && s.trim().length > 0)
    .map((s) => s.trim().slice(0, maxLen))
    .slice(0, max);
}

/** Normalize lane_labels: each label is trimmed, capped at 24 chars
 *  (compact enough to fit in a lane header), and falls back to the
 *  canonical name when missing so the UI always has something to
 *  show. */
function cleanLaneLabels(raw: unknown): LaneLabels {
  const fallback: LaneLabels = {
    pain: "Pain points",
    features: "Features",
    outcomes: "Outcomes",
    objective: "Objective",
  };
  if (!raw || typeof raw !== "object") return fallback;
  const r = raw as Record<string, unknown>;
  const one = (key: keyof LaneLabels): string => {
    const v = r[key];
    if (typeof v !== "string") return fallback[key];
    const cleaned = v.trim().replace(/[.!?,:;]+$/g, "").slice(0, 24).trim();
    return cleaned.length > 0 ? cleaned : fallback[key];
  };
  return {
    pain: one("pain"),
    features: one("features"),
    outcomes: one("outcomes"),
    objective: one("objective"),
  };
}

function cleanSubCategory(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const t = raw.trim();
  return t.length > 0 ? t.slice(0, 40) : null;
}

/** Sanitize the LLM-emitted citations[] — keep only positive
 *  integers, dedup, cap at 5. Returns undefined when the input
 *  wasn't an array (let callers omit the field cleanly). */
function cleanCitations(raw: unknown): number[] | undefined {
  if (!Array.isArray(raw)) return undefined;
  const out = new Set<number>();
  for (const v of raw) {
    if (typeof v === "number" && Number.isFinite(v) && v >= 1) {
      out.add(Math.floor(v));
    }
  }
  return Array.from(out).slice(0, 5);
}

function cleanPains(raw: unknown): PainItem[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .map((p): PainItem | null => {
      if (!p || typeof p !== "object") return null;
      const r = p as Record<string, unknown>;
      const name = typeof r.name === "string" ? r.name.trim() : "";
      if (name.length === 0) return null;
      const neg =
        typeof r.negative_outcome === "string" ? r.negative_outcome.trim() : "";
      const causes = trimList(r.root_causes, 4, 80);
      const rank =
        typeof r.influence_rank === "number" && Number.isFinite(r.influence_rank)
          ? Math.max(0, Math.min(5, r.influence_rank))
          : 2.5;
      return {
        name: stripVerbPrefix(name).slice(0, 200),
        negative_outcome: neg.slice(0, 200),
        root_causes: causes,
        influence_rank: rank,
        sub_category: cleanSubCategory(r.sub_category),
        citations: cleanCitations(r.citations),
      };
    })
    .filter((p): p is PainItem => p !== null)
    .slice(0, 5);
}

function cleanFeatures(raw: unknown): FeatureItem[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .map((p): FeatureItem | null => {
      if (!p || typeof p !== "object") return null;
      const r = p as Record<string, unknown>;
      const name = typeof r.name === "string" ? r.name.trim() : "";
      if (name.length === 0) return null;
      const pos =
        typeof r.positive_outcome === "string" ? r.positive_outcome.trim() : "";
      const principles = trimList(r.first_principles, 4, 80);
      return {
        name: stripVerbPrefix(name).slice(0, 200),
        positive_outcome: pos.slice(0, 200),
        first_principles: principles,
        sub_category: cleanSubCategory(r.sub_category),
        citations: cleanCitations(r.citations),
      };
    })
    .filter((p): p is FeatureItem => p !== null)
    .slice(0, 6);
}

function cleanOutcomes(raw: unknown): OutcomeItem[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .map((p): OutcomeItem | null => {
      if (!p || typeof p !== "object") return null;
      const r = p as Record<string, unknown>;
      const name = typeof r.name === "string" ? r.name.trim() : "";
      if (name.length === 0) return null;
      const measured =
        typeof r.measured_by === "string" ? r.measured_by.trim() : "";
      return {
        name: stripVerbPrefix(name).slice(0, 200),
        measured_by: measured.slice(0, 150),
        sub_category: cleanSubCategory(r.sub_category),
        citations: cleanCitations(r.citations),
      };
    })
    .filter((p): p is OutcomeItem => p !== null)
    .slice(0, 5);
}
