-- ── Flights — first-class causal pathways ─────────────────────────
--
-- Phase 7 of the temporal-rigor plan. A "flight" is a named,
-- categorized, multi-step pathway through the knowledge graph —
-- the operational unit that surfaces "this is the inflammation→
-- cognition cascade" or "this is the HPA→hippocampus axis" as
-- something the user can point at, compare, and reason over.
--
-- DESIGN
--
-- Until now, the closest analogue to a flight was the buried
-- `probability_spaces.critical_path` (Phase 4 §4.x), which lived
-- inside an edge's probability sub-graph and was never exposed as a
-- first-class object. This table promotes the concept:
--
--   • named           → "MAPK/ERK Cascade" / "Sleep→Glymphatic→PFC"
--   • categorized     → tied to a domain-specific category
--   • ordered         → steps_entity_ids[] is a path through entities
--   • cited           → score_breakdown rolls up Phase 3+5 substrate
--                       (joint probability, evidence depth, time-to-
--                       outcome, calibration drift) into one breakdown
--                       a reviewer can audit
--   • promoted from   → critical_path / root_trace / template_seeded /
--                       user_curated; provenance preserved on every
--                       row
--
-- POOLED FIELDS
--
--   total_peak_days        — sum of peak_days_p50 along steps_edge_ids
--                            (denormalized for fast strategizer queries;
--                            recomputed when underlying edge timings
--                            change)
--   total_persistence_days — min persistence_days_p50 along the path
--                            (bottleneck; weakest link sets ceiling)
--   joint_probability      — ∏ edge.strength × edge.confidence along
--                            the path (placeholder; real Bayesian rollup
--                            is Phase 8 follow-up)
--   evidence_count         — total evidence_registries rows across
--                            steps_edge_ids
--   heterogeneity_i2       — max I² across the path (bottleneck on
--                            study agreement)
--
-- LIFECYCLE
--
--   draft   → autogenerated from critical_path; not yet user-confirmed
--   active  → user accepted; participates in ranking + UI
--   archived → user rejected or superseded by a newer version
--
-- BACKWARD COMPAT — this is a NEW table. Nothing depends on it
-- pre-creation; consumers (Phase 6 UI, future flight-aware ranker)
-- read additively.

create table if not exists public.flights (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,

  -- Identity
  name text not null,
  description text,
  category text,                      -- domain-specific (e.g. "inflammation",
                                       --  "neuroplasticity", "stress_axis")

  -- Path
  steps_entity_ids uuid[] not null default '{}'::uuid[],
  steps_edge_ids uuid[] not null default '{}'::uuid[],

  -- Provenance
  origin text not null default 'user_curated',  -- 'auto_critical_path' |
                                                 -- 'auto_root_trace' |
                                                 -- 'template_seeded' |
                                                 -- 'user_curated'
  template_seed_id text,              -- when origin='template_seeded',
                                       --  the seed_id from the template

  -- Lifecycle
  status text not null default 'active',  -- 'draft' | 'active' | 'archived'

  -- Pooled scalars (denormalized; recomputed on edge changes)
  total_peak_days numeric,
  total_persistence_days numeric,
  joint_probability numeric,
  evidence_count integer not null default 0,
  heterogeneity_i2 numeric,

  -- Phase structure (optional pre-baked roadmap; JSONB so templates
  -- can encode Phase 1: baseline → Phase 2: foundational → ...
  -- transitions with criteria expressed in terms of metric/timing
  -- thresholds. Shape:
  --   [{ phase: 1, name, duration_weeks, entry_criteria, exit_criteria,
  --       step_entity_ids[] }, ...]
  phases jsonb,

  -- Score breakdown (the audit panel surface — "where does this 0.72
  -- come from"). Shape:
  --   {
  --     joint_probability,
  --     evidence_depth,
  --     time_to_effect,
  --     persistence_match,
  --     controllability,
  --     risk_factor
  --   }
  score_breakdown jsonb,

  -- Audit
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

-- ── Constraints ──

alter table public.flights
  drop constraint if exists flights_origin_check;
alter table public.flights
  add constraint flights_origin_check
  check (
    origin in (
      'auto_critical_path',
      'auto_root_trace',
      'template_seeded',
      'user_curated'
    )
  );

alter table public.flights
  drop constraint if exists flights_status_check;
alter table public.flights
  add constraint flights_status_check
  check (status in ('draft', 'active', 'archived'));

alter table public.flights
  drop constraint if exists flights_steps_nonempty_check;
alter table public.flights
  add constraint flights_steps_nonempty_check
  check (array_length(steps_entity_ids, 1) is null or array_length(steps_entity_ids, 1) >= 2);

alter table public.flights
  drop constraint if exists flights_heterogeneity_check;
alter table public.flights
  add constraint flights_heterogeneity_check
  check (
    heterogeneity_i2 is null
    or (heterogeneity_i2 >= 0 and heterogeneity_i2 <= 1)
  );

alter table public.flights
  drop constraint if exists flights_joint_probability_check;
alter table public.flights
  add constraint flights_joint_probability_check
  check (
    joint_probability is null
    or (joint_probability >= 0 and joint_probability <= 1)
  );

-- ── Indexes ──

-- Standard space-scoped lookup, latest first (the gallery view).
create index if not exists flights_space_status_idx
  on public.flights (space_id, status, created_at desc);

-- Per-category surfacing (e.g. "show me all inflammation flights").
create index if not exists flights_space_category_idx
  on public.flights (space_id, category)
  where category is not null and status = 'active';

-- "Find flights citing entity X" — drives the entity-detail drawer's
-- "flights through this concept" surface.
create index if not exists flights_steps_entity_gin_idx
  on public.flights using gin (steps_entity_ids);

-- "Find flights citing edge X" — when an edge's timing changes, we
-- can mark dependent flights stale.
create index if not exists flights_steps_edge_gin_idx
  on public.flights using gin (steps_edge_ids);

-- ── updated_at trigger ──

create or replace function public.flights_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists flights_set_updated_at on public.flights;
create trigger flights_set_updated_at
  before update on public.flights
  for each row execute function public.flights_set_updated_at();

-- ── RLS ──

alter table public.flights enable row level security;

create policy "flights select own space"
  on public.flights for select
  using (
    exists (
      select 1 from public.spaces s
      where s.id = flights.space_id
        and s.user_id = auth.uid()
    )
  );

create policy "flights insert own space"
  on public.flights for insert
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.spaces s
      where s.id = flights.space_id
        and s.user_id = auth.uid()
    )
  );

create policy "flights update own space"
  on public.flights for update
  using (
    exists (
      select 1 from public.spaces s
      where s.id = flights.space_id
        and s.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.spaces s
      where s.id = flights.space_id
        and s.user_id = auth.uid()
    )
  );

create policy "flights delete own space"
  on public.flights for delete
  using (
    exists (
      select 1 from public.spaces s
      where s.id = flights.space_id
        and s.user_id = auth.uid()
    )
  );

-- ── Comments ──

comment on table public.flights is
  'Phase 7 — first-class named, categorized, multi-step pathways through the knowledge graph. Promotes critical-path / root-trace / template-seeded / user-curated routes from buried sub-objects into a cited, comparable, audit-ready surface. Steps reference entities + edges; pooled scalars roll up Phase 3 (temporal pools) + Phase 5 (calibration history) substrate.';

comment on column public.flights.origin is
  'How this flight was created. auto_critical_path = promoted from a probability_space''s critical path. auto_root_trace = promoted from converges_chains backward trace. template_seeded = pre-baked from a research template (e.g. cognition''s inflammation→cognition flight). user_curated = drawn by hand on the canvas.';

comment on column public.flights.phases is
  'Optional pre-baked phase roadmap. JSONB array of { phase, name, duration_weeks, entry_criteria, exit_criteria, step_entity_ids[] }. Cognition template ships flights with 4 phases each (baseline → foundational → accelerator → consolidation). User-curated flights typically leave this null.';

comment on column public.flights.score_breakdown is
  'Audit panel substrate: { joint_probability, evidence_depth, time_to_effect, persistence_match, controllability, risk_factor }. Lets the UI render "where does this 0.72 come from?" without recomputing. Recomputed when underlying edges'' Phase 3+5 columns change.';
