-- ── improvement_goals.room_categories ──────────────────────────────
--
-- Tier 3: adaptive sub-categorization. After a user picks a
-- sub-objective, a pre-room LLM step enumerates the macro-domain
-- categories that apply to THIS specific sub-objective. Each of
-- the three room lanes (friction / mechanism / result) gets its
-- own category set (3-5 categories each), domain-adapted.
--
-- Shape:
--   {
--     "friction":  [{ "slug": "ux", "label": "UX", "color": "#..." }, ...],
--     "mechanism": [{ "slug": "ai_driven", "label": "AI-driven", "color": "#..." }, ...],
--     "result":    [{ "slug": "engagement", "label": "Engagement", "color": "#..." }, ...]
--   }
--
-- Empty `{}` = not yet generated. Default is empty so existing
-- rooms continue rendering without categories (their items just
-- have sub_category = null and show in an "Uncategorized" group).
--
-- The category set drives:
--   1. enum constraint for every item the room generator emits
--      (each pain/feature/outcome must be tagged with one slug
--      from its lane's set)
--   2. group-by-category toggle in each lane
--   3. archetype derivation on chain triples (the LLM names a
--      cross-category archetype using these category labels)
--   4. macro portfolio dashboard at the top of the room (coverage
--      diagnostics, diversity score)

alter table public.improvement_goals
  add column if not exists room_categories jsonb not null default '{}'::jsonb;

comment on column public.improvement_goals.room_categories is
  'Tier 3 — adaptive sub-category sets generated by the pre-room LLM step. Keyed by lane (friction/mechanism/result). Each lane carries 3-5 categories with {slug, label, color}. Empty {} = not yet generated; the room still renders without categories. Drives lane-card chips, group-by toggle, chain archetype derivation, and portfolio dashboard.';
