-- ── Pain metrics + apps-as-interventions wiring ───────────────────
--
-- The dual-framing companion to twin_state. Where twin_state answers
-- "what is true about the system," pain_metrics answers "what
-- inefficiency / friction / cost the twin is here to reduce."
--
-- Generated by the PainExtractor agent during synthesis. Updated on
-- observation calibration (current_value moves toward or away from
-- target). Apps reference these via apps.target_pain_metric_ids so
-- the Twin Detail Page can show "Pomodoro Cog -0.8 fatigue" per
-- app variant.
--
-- Three changes in one migration (logically coupled):
--   1. pain_metrics table + RLS
--   2. apps.target_pain_metric_ids + apps.measured_impact columns
--   3. apps.app_type + user_app_preferences.app_type constraints
--      extended to include 'twin_visualization' (apps that DEPICT
--      the twin rather than ARE interventions)

-- ── 1. pain_metrics table ──────────────────────────────────────────

create table if not exists public.pain_metrics (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,

  -- Human-readable label. The PainExtractor generates these in the
  -- user's voice (e.g. "Cognitive fatigue after 90 minutes").
  name text not null,

  -- Stable category enum for grouping + filtering. The agent maps
  -- the inferred pattern onto one of these; "other" is the escape
  -- hatch for genuinely novel pains.
  category text not null check (category in (
    'cognitive_fatigue',
    'time_to_flow',
    'attention_drift',
    'high_cost',
    'user_friction',
    'inefficiency',
    'context_switch_overhead',
    'other'
  )),

  -- Quantitative anchor. baseline = where the user started.
  -- current = where they are now (updated on observation log).
  -- target = where they want to be. unit = "minutes" / "rating" /
  -- "dollars" / etc. direction = which way is "better."
  baseline_value numeric not null,
  current_value numeric not null,
  target_value numeric not null,
  unit text not null,
  direction text not null check (direction in ('minimize', 'maximize')),

  -- Source entities the PainExtractor flagged as the cause of this
  -- pain. Lets the UI navigate "show me what's causing this pain"
  -- by jumping to those entities on the canvas.
  source_entity_ids uuid[] not null default '{}',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_pain_metrics_space
  on public.pain_metrics(space_id, created_at desc);
create index if not exists idx_pain_metrics_user
  on public.pain_metrics(user_id, created_at desc);

alter table public.pain_metrics enable row level security;

drop policy if exists "pain_metrics_owner" on public.pain_metrics;
create policy "pain_metrics_owner" on public.pain_metrics
  for all using (auth.uid() = user_id);

-- ── 2. apps-as-interventions wiring ────────────────────────────────

-- Array column instead of join table — apps are read en-masse for
-- canvas + dashboard, and target_pain_metric_ids stays small
-- (typically 1-3 per app).
alter table public.apps
  add column if not exists target_pain_metric_ids uuid[] not null default '{}';

-- Per-pain measured impact, shape: { [pain_metric_id]: delta_numeric }
-- Updated when an app variant's experiment completes. Drives the
-- "Pomodoro Cog -0.8 fatigue" comparison on the Outcomes tab.
alter table public.apps
  add column if not exists measured_impact jsonb;

-- ── 3. Extend app_type to include twin_visualization ──────────────
--
-- Apps come in two flavors:
--   - Intervention apps (existing) — designed to MOVE pain metrics
--   - Visualization apps (new) — designed to DEPICT the twin
--     (simulators, what-if explorers, interactive graphs)
-- The Twin Detail Page's "Build a visualization app" action creates
-- the latter; existing pipeline creates the former.

alter table public.apps
  drop constraint if exists apps_app_type_check;
alter table public.apps
  add constraint apps_app_type_check check (app_type in (
    'dashboard',
    'workflow',
    'tool',
    'monitor',
    'integration',
    'twin_visualization'
  ));

-- user_app_preferences has its own inline check; keep them in sync.
-- The original constraint is unnamed (Postgres auto-named), so we
-- can't drop-by-name reliably. Inspect the table for the actual
-- constraint name. We use a do-block to discover + drop + recreate.
do $$
declare
  c_name text;
begin
  select conname into c_name
  from pg_constraint
  where conrelid = 'public.user_app_preferences'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) like '%dashboard%workflow%tool%monitor%integration%';
  if c_name is not null then
    execute format('alter table public.user_app_preferences drop constraint %I', c_name);
  end if;
end$$;

alter table public.user_app_preferences
  add constraint user_app_preferences_app_type_check
  check (app_type is null or app_type in (
    'dashboard',
    'workflow',
    'tool',
    'monitor',
    'integration',
    'twin_visualization'
  ));
