-- ── Library object micro-objectives ────────────────────────────────────
--
-- The per-card SUCCESS RUBRIC: 3–5 micro-objectives derived for each
-- feature / variable / insight / mechanism card, framed AROUND the space's
-- main objective. Each micro carries:
--   - slug         kebab id, unique within the card
--   - label        ≤ 6-word display
--   - why          1 sentence on why it matters for the OBJECTIVE
--   - success_signal  optional measurable threshold
--   - laddersTo    intake optimization factor slugs this micro inherits
--   - confidence   0..1 honest model take
-- Plus a small wrapper (derivedFrom snapshot + modelVersion + generatedAt)
-- so the cache can self-invalidate on card-body edits.
--
-- Why a top-level column rather than content_snapshot.micro_objectives:
--   • cross-card queries — "every card laddering into factor X", "every
--     card whose dominant micro is Y" — without unpacking JSON in every
--     reader.
--   • GIN index for jsonb path queries (e.g. micros[*].slug = ...) and
--     for the future "show me cards covering the same micros" graph.
--   • drawer + brief surfaces stop having to merge two JSONB roots.
-- We keep WRITING to content_snapshot.micro_objectives too for one cycle
-- (back-compat with the parallel session's writer) — the column is the
-- authoritative reader from here on.
--
-- Additive + idempotent.

ALTER TABLE public.library_objects
  ADD COLUMN IF NOT EXISTS micro_objectives jsonb;

COMMENT ON COLUMN public.library_objects.micro_objectives IS
  'Per-card success rubric: { cardId, derivedFrom: { headline, body, role }, micros: [{slug,label,why,success_signal?,laddersTo:[factor_slug],confidence}], generatedAt, modelVersion }. Generated by derive-micro-objectives, cached here; invalidates on card body diff or modelVersion bump.';

-- GIN index on the JSONB column so future queries like "every card whose
-- micros ladder into <slug>" or "every card with a fresh rubric" stay fast
-- as the cache fills.
CREATE INDEX IF NOT EXISTS idx_library_objects_micro_objectives
  ON public.library_objects USING gin (micro_objectives jsonb_path_ops);
