-- ── Objective Canvas — sub-objective scoping for entities + edges ──
--
-- Phase 5/6 of the Objective Canvas module. Sub-objective rooms
-- generate their own pain/feature/outcome/objective entities + the
-- cross-layer correlations between them. We scope those to the
-- specific sub-objective (a row in improvement_goals) so the room
-- only renders its own items, and the main canvas can later promote
-- approved ones onto the parent canvas.
--
-- Pattern matches what the legacy intake does with parent_expansion_id
-- on expansions: a nullable FK that downstream queries filter by.
--
-- Both columns are nullable for back-compat with all existing
-- entities/edges — they were created before the canvas module.

alter table public.entities
  add column if not exists parent_sub_objective_id uuid
    references public.improvement_goals(id) on delete cascade;

create index if not exists entities_parent_sub_objective_idx
  on public.entities (parent_sub_objective_id)
  where parent_sub_objective_id is not null;

comment on column public.entities.parent_sub_objective_id is
  'FK to the improvement_goals row that owns this entity inside an Objective Canvas sub-objective room. Null for entities generated by the legacy intake pipeline. Cascade-delete on parent removal — the room is the owner of these items.';

alter table public.edges
  add column if not exists parent_sub_objective_id uuid
    references public.improvement_goals(id) on delete cascade;

create index if not exists edges_parent_sub_objective_idx
  on public.edges (parent_sub_objective_id)
  where parent_sub_objective_id is not null;

comment on column public.edges.parent_sub_objective_id is
  'FK to the improvement_goals row that owns this edge inside an Objective Canvas sub-objective room. Mirrors entities.parent_sub_objective_id; cascade-delete keeps room contents self-contained.';

-- A small generated-at marker on improvement_goals so the room
-- knows whether layered generation has run yet without re-counting
-- child entities every render. Nullable; set when stage_d_correlate
-- finishes; cleared on regenerate. Keeps the room's "Generate" UX
-- decision local to one column.
alter table public.improvement_goals
  add column if not exists room_layers_generated_at timestamptz;

comment on column public.improvement_goals.room_layers_generated_at is
  'When the Objective Canvas room''s 4-stage layered generation completed for this sub-objective. Null = never generated; non-null = at least one Pain/Outcome/Feature pass landed. The room''s "Generate" CTA reads this to decide whether to show "Generate" vs "Regenerate".';
